### ISSUE TITLE
Step timeout while throw an error

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#1007]
### What is version of KubeSphere DevOps has the issue?

v3.4.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

![企业微信截图_16980498481621](https://github.com/kubesphere/ks-devops/assets/5917832/fc5ffd68-771d-4727-8ca4-23d13761881f)

https://github.com/kubesphere-sigs/pipeline-templates/blob/main/featured/steps/timeout.yaml#L44

need change to :

kubectl edit clustersteptemplates.devops.kubesphere.io  timeout

        {
          "key": "activity",
          "value": {
            "isLiteral": true,
            "value": {{.param.activity}}
          }
        },

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/6b11715e-78c0-4b97-b345-d4e5ae81d785)
