### ISSUE TITLE
support apidocs

### ISSUE THREAD

**Issue by yudong2015** [kubesphere/ks-devops#1008]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### Describe this feature

add apidocs with swagger.json that generated by swagger-UI

**Comment by yudong2015** [comment]
Update swagger info and filter out APIs that not start with /kapis/ ;

Visit SwaggerUI:
update service type of devops-apiserver to NodePort , then via `http://ip:NodePort/apidocs/?url=http://ip:NodePort/apidocs.json`.

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/f48a34ac-700c-4fd7-b3ec-4f121f703602)
