### ISSUE TITLE
Potential issues due to URI is too long

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#101]
The Jenkins client puts all map data into the HTTP query. It might cause the URI to be too long to get 414. Such as the following example:

It put all the content of credentials into the HTTP query.

* https://github.com/kubesphere/ks-devops/blob/7714e9c334ad2f2c68bad2260415047eea71b7e2/pkg/client/devops/jenkins/credential.go#L210
* https://github.com/kubesphere/ks-devops/blob/7714e9c334ad2f2c68bad2260415047eea71b7e2/pkg/client/devops/jenkins/request.go#L205

## References
* https://kubesphere.com.cn/forum/d/5257-devops/19 (in the Chinese forum)

/priority high
/kind bug
/milestone v3.2

**Comment by shihaoH** [comment]
If you use the mirror johnniang/ks-installer:remove-devops-comp enable ks-devops, unable to synchronize the credentials created on the kubesphere interface to jenkins. 
What should i do now
