### ISSUE TITLE
When build settings are not selected in the pipeline configuration, the option 'Delete old builds' is still checked in Jenkins.

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#1018]
### What is version of KubeSphere DevOps has the issue?

v3.4.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

![image](https://github.com/kubesphere/ks-devops/assets/5917832/2b490913-ddd5-41a3-9b95-6dc50d396f11)
![image](https://github.com/kubesphere/ks-devops/assets/5917832/3e70e9a0-6312-4cea-ae8d-6baaea2d2887)

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/26f404ef-1160-44c2-9048-fafc6abb6545)



![Image](https://github.com/kubesphere/ks-devops/assets/18654693/42c43575-69b9-4718-8afe-da101ab13467)
