### ISSUE TITLE
The name of 'DevOps Project' is wrong in branch detail page

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#105]
**Versions Used**
KubeSphere:  `dev:latest`

![image](https://user-images.githubusercontent.com/68640256/116214895-bd13b980-a779-11eb-9164-aeb5bd541f23.png)

/priority low
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone BackLog

**Comment by JohnNiang** [comment]
hi @xuliwenwenwen, please point out which PR fixed this issue.

**Comment by xuliwenwenwen** [comment]
> hi @xuliwenwenwen, please point out which PR fixed this issue.

https://github.com/kubesphere/console/pull/2133

**Comment by wenxin-01** [comment]
issue fixed `ks3.2-alpha.0`
