### ISSUE TITLE
shell and script input box content is not correct after keyboard oper

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/ks-devops#106]
**Describe the Bug**
after use the keyboard Ctrl +A --> Ctrl +C, shell and script input box content is not correct
![image](https://user-images.githubusercontent.com/36271543/121456966-78ff1000-c9d9-11eb-88d1-cc30cee6932b.png)

![image](https://user-images.githubusercontent.com/36271543/121457111-b6fc3400-c9d9-11eb-8ddd-94f3afe7c4d6.png)

**Versions Used**
KubeSphere:  v3.1.0

/kind bug
/milestone v3.1.1
/assign @harrisonliu5
/priority Medium

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`
