### ISSUE TITLE
Didn't show the full changeset of a pipeline run

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#108]
As you can see from the following screenshot, there're two commits from the HTTP response. But the front-end only shows the first one.

![image](https://user-images.githubusercontent.com/1450685/128303599-7d727048-5216-4574-8ef7-967f804b3ee2.png)

The front-end git repository is https://github.com/kubesphere/console

/kind bug

**Comment by JohnNiang** [comment]
After some investigation, we found another similar issue fixed before. please see also <https://github.com/kubesphere/console/issues/1029>.

**Comment by ruibaby** [comment]
Another problem has been found and needs to be confirmed.

https://github.com/kubesphere/console/blob/master/src/stores/devops/run.js#L111

I think the timestamp field in changeSet should be used here. 

like this:

![image](https://user-images.githubusercontent.com/21301288/128362644-67a7c138-c276-4743-b5bc-eb7a6088d138.png)

![image](https://user-images.githubusercontent.com/21301288/128362727-036e5090-e95b-4961-ac20-22c787b4d607.png)

**Comment by LinuxSuRen** [comment]
> I think the timestamp field in changeSet should be used here.

+1 from me

**Comment by ruibaby** [comment]
So, do I need to deal with this problem in one pr?

@LinuxSuRen

**Comment by LinuxSuRen** [comment]
I prefer to fix the multiple records issue (commits and time) in one PR. What's your opinion?
