### ISSUE TITLE
Failed to create pipeline and credential in a multi-cluster environment

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#109]
**Environment**

`host 3.1 + member 3.1` 
http://139.198.9.112:30883

**How To Reproduce**
1. Go to workspace 'ws3'
2. Go to devops project  'dev3-1'
3. Create credential and pipeline

**Expected behavior**
Pipeline and credential created successfully

**Actual behavior**
Failed to create pipeline and credential
![image](https://user-images.githubusercontent.com/68640256/113106759-b4d96480-9235-11eb-9a7a-15604be01bc7.png)
![image](https://user-images.githubusercontent.com/68640256/113106832-c9b5f800-9235-11eb-90af-f1d6f2423ba5.png)
![image](https://user-images.githubusercontent.com/68640256/113107411-78f2cf00-9236-11eb-83fa-ede1ef463e16.png)

/priority high
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
this issue was fixed by https://github.com/kubesphere/kubesphere/pull/4228

**Comment by wenxin-01** [comment]
issue fixed in `nightly-20211011`

**Comment by lishuyanla** [comment]
> > UsernameNotFOundException：在目录中找不到用户。
> 
> 解决方法：使用以下命令更改启用 DevOps 的集群中的用户密码。此操作将触发用户控制器将数据同步到 OpenLDAP。
> 
> ```
> kubectl patch users <USERNAME> -p '{"spec":{"password":"<PASSWORD>"}}' --type='merge' && kubectl annotate users <USERNAME> iam.kubesphere.io/password-encrypted-
> ```并无效果，更改用户密码重新登录，回到devops，还是报一样的错！
