### ISSUE TITLE
Correct repository owner comparison condition in GitHub action configuration

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#113]
Recently, we have transferred organization of ks-devops from `kubesphere-sigs` to `kubesphere`.

But, [in GitHub action configuration](https://github.com/kubesphere/ks-devops/blob/7714e9c334ad2f2c68bad2260415047eea71b7e2/.github/workflows/build.yaml), `kubesphere-sigs` is still be used to compare with `github.repository_owner`.

I'm not sure if we are supposed to label this issue as `good-first-issue`, because this problem will affect docker image build triggered by subsequent commit.

**Comment by LinuxSuRen** [comment]
Please see also https://github.com/kubesphere/ks-devops/runs/3258512601?check_suite_focus=true#step:10:1015

**Comment by JohnNiang** [comment]
The GitHub action steps of official repository is incorrect. Please see below:

https://github.com/kubesphere/ks-devops/blob/7714e9c334ad2f2c68bad2260415047eea71b7e2/.github/workflows/build.yaml#L20-L25

![image](https://user-images.githubusercontent.com/16865714/128464861-8d3dcf86-b9ea-4e5d-b4ec-c344d679aaa4.png)

**Comment by LinuxSuRen** [comment]
This is not a good first issue. We should fix it as soon as possible.

/priority high
