### ISSUE TITLE
UI: Inconsistent status in the multi-branch pipeline list page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#125]
Screenshot from DevOps page:

![image](https://user-images.githubusercontent.com/1450685/128802197-c13b1f66-e2cf-407a-9956-469a7d2ecfac.png)

Screenshot from Jenkins page:
![image](https://user-images.githubusercontent.com/1450685/128802210-c8026412-3c40-4de7-9dd2-645bc53b98ca.png)

As you can see from the above screenshot pages. The color of deleted git branch Pipeline was gray in Jenkins UI. But there's no difference on the DevOps page. It makes people feel confused.

The backend response already has the data of that status. Please see also the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/128802624-d0935506-a7a5-4474-9b2b-c1ff11a30b15.png)

/good-first-issue

**Comment by chilianyi** [comment]
same as:https://github.com/kubesphere/ks-devops/issues/946

already fixed.
