### ISSUE TITLE
There is no use to click "show yaml editor" at "Edit Pipeline" page

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/ks-devops#148]
**Describe the Bug**

click "show yaml editor"

![image](https://user-images.githubusercontent.com/18692628/115985613-3c20ba80-a5df-11eb-970f-761e07429b45.png)

got

![image](https://user-images.githubusercontent.com/18692628/115985624-4ba00380-a5df-11eb-9623-4b52542f6156.png)

**Versions Used**
KubeSphere: nightly-20210422
Kubernetes: v1.18.14

/kind bug
/area console
/area devops

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.0`
