### ISSUE TITLE
Let ks support displaying more types of pipeline health status

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/ks-devops#150]
**What's it about?**

![image](https://user-images.githubusercontent.com/18692628/115534468-62d2ae80-a2ca-11eb-8a09-54fe42bdccff.png)

When the Pipeline has just been created or deleted, it will show "Warning" here, maybe it would be more appropriate to show "Creating/Deleting" ...

/area devops
/kind feature-request

**Comment by chilianyi** [comment]
There are three kind of health status now. 
If new created pipeline, the health status will be healthy
<img width="1177" alt="截屏2023-07-31 11 16 29" src="https://github.com/kubesphere/ks-devops/assets/5917832/3f40c8d4-b100-4300-a11c-1c2d24684ab5">
