### ISSUE TITLE
Request to have an option to console if trigger the pipeline when git repository changes

### ISSUE THREAD

**Issue by jerryhu1234** [kubesphere/ks-devops#157]
创建多分支时，请考虑通过webhook出发构建，能否有一个功能开关，控制是否进行自动构建流水线，
目的主要只是检出分支名称，而不需要自动构建
目前jenkins支持此项功能，只是界面上kubesphere界面上没有此配置，是否添加此配置同步到jenkins上
https://kubesphere.com.cn/forum/d/3981-devopsgitlabjenkins/2

**Comment by LinuxSuRen** [comment]
Considering we will have the new webhook feature. I'm going to close this issue.

See also https://github.com/kubesphere/ks-devops/issues/598
/close
