### ISSUE TITLE
ks-installer will overwrite configmap kubesphere-config once ks-installer restart

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#16]
Recently, I restarted my cluster and found that config map kubesphere-config was overwritten by ks-installer. So that devops.devopsServiceAddress configured by migrate job would disappear.

**Comment by LinuxSuRen** [comment]
We already change `devopsServiceAddress` to `endpoint`. It works well with `kubespheredev/ks-installer:nightly-20210924`.

So, I guess we can close this issue. Right? @JohnNiang

**Comment by JohnNiang** [comment]
Right.

/close
