### ISSUE TITLE
Suggest to improve DevOps

### ISSUE THREAD

**Issue by fairychild1** [kubesphere/ks-devops#168]
1.devops要支持编排。就像咱们的云平台，能把整套环境导出，然后倒入到另外一个可用区。我们的devops工作流，如果能编排，让用户导出已有的流水线，然后倒入到另外一个里面，这样能少些工作；
2.支持流水线的复制。包括整体的或者局部的。同一个项目下面，不同的用户登进去后，新的用户看到老的项目的流水线，直接复制部分过来，然后稍微修改下，也能省些工作；
3.支持流水线导出成jenkins文件，这样有的人喜欢编辑jenkins文件的，可以让他直接在文件里修改；
4.咱们的基础模块可以再进一步细化。比如拉代码的模块，只保留参数，用户指定他的git的项目名，直接把整个url搞出来；

**Comment by LinuxSuRen** [comment]
/retitle Suggest to improve DevOps

This is a super big topic. Normally, we only discuss one thing in one issue. Please consider splitting your ideas into serval issues if you're still interested in it.

/close
