### ISSUE TITLE
Bump the version (v0.2.5) of controller-gen

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#189]
## Why?
* controller-gen v0.2.5 maintains the CRD file in version `apiVersion: apiextensions.k8s.io/v1beta1`. But other CRD files rely on `apiVersion: apiextensions.k8s.io/v1`. See also [here](https://github.com/kubesphere/ks-devops/blob/63c99e17a2a744c8321a4e71b05889dee151e51b/config/crd/bases/devops.kubesphere.io_pipelines.yaml#L3).
* The latest version of it is v0.6.2
  * v0.2.5 was released on Jan 30, 2020, it's time to consider bumping it

## Suggestions
These files might need to be updated:

* https://github.com/kubesphere/ks-devops/blob/63c99e17a2a744c8321a4e71b05889dee151e51b/Makefile#L157

## TODO
Please consider letting users upgrade controller-gen version.

**Comment by JohnNiang** [comment]
I found a potential solution [here](https://github.com/kubernetes-sigs/kubebuilder/blob/2b3a589c7a43b932072e347c4d2f1fd032803ef3/docs/book/src/cronjob-tutorial/testdata/project/Makefile#L88-L108).

**Comment by LinuxSuRen** [comment]
> I found a potential solution [here](https://github.com/kubernetes-sigs/kubebuilder/blob/2b3a589c7a43b932072e347c4d2f1fd032803ef3/docs/book/src/cronjob-tutorial/testdata/project/Makefile#L88-L108).

So, I guess this issue might be a good first issue. I'll give it a label.

/good-first-issue

**Comment by JohnNiang** [comment]
In fact, this issue was resolved by #247 instead of #246.
