### ISSUE TITLE
Lint failed due to outdated package usage of term

### ISSUE THREAD

**Issue by flamywhale** [kubesphere/ks-devops#192]
The current workflow of checking code, in the process of a pull request, failed due to outdated package usage.

An error message in my pull request is at [here](https://github.com/kubesphere/ks-devops/actions/runs/1135689078).

The main reason is:
```bash
Lint
SA1019: package github.com/docker/docker/pkg/term is deprecated: use github.com/moby/term instead (staticcheck)
```

By searching in the whole repository, the related source code is [this](https://github.com/kubesphere/ks-devops/blob/481526eff7e6e7c996cd85e1ad5720797b4bd76d/pkg/utils/term/term.go#L23) and the related function [`TerminalSize`](https://github.com/kubesphere/ks-devops/blob/481526eff7e6e7c996cd85e1ad5720797b4bd76d/pkg/utils/term/term.go#L29) is used at [`cmd/controller/server.go`](https://github.com/kubesphere/ks-devops/blob/481526eff7e6e7c996cd85e1ad5720797b4bd76d/cmd/controller/app/server.go#L83) and [`cmd/apiserver/server.go`](https://github.com/kubesphere/ks-devops/blob/481526eff7e6e7c996cd85e1ad5720797b4bd76d/cmd/apiserver/app/server.go#L69).

Do we need to update the package reference link to ` github.com/moby/term` or to delete related codes?

**Comment by LinuxSuRen** [comment]
IMO, we can just delete the package `github.com/docker/docker/pkg/term`. There's no reason to rely on Docker tech.
