### ISSUE TITLE
Incompatible PipelineRuns history

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#232]
I've provided a new API in PR #230 for listing PipelineRuns. But this API queries PipelineRun CR only.

Consider if the history of Pipeline runs already exist, the API won't be able to query them.

Therefore, we need to solve the backward compatible problem.

/kind bug
/assign

**Comment by JohnNiang** [comment]
Potential solution: create PipelineRuns(CR) for the history of Pipeline runs(Jenkins build) in a batch job. And controller will fetch run status automatically.

**Comment by LinuxSuRen** [comment]
I guess this issue was fixed by https://github.com/kubesphere/ks-devops/pull/244

@JohnNiang , plese help me to confirm it.

**Comment by JohnNiang** [comment]
Confirmed and I'm going to close it.

/close
