### ISSUE TITLE
CRDs upgrade problem with Helm

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#234]
By default, helm won't upgrade our CRDs. This behavior might introduce some unexpected result.

```text
There is no support at this time for upgrading or deleting CRDs using Helm. 
This was an explicit decision after much community discussion due to the 
danger for unintentional data loss. Furthermore, there is currently no community 
consensus around how to handle CRDs and their lifecycle. As this evolves, 
Helm will add support for those use cases.
```

- https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
- https://github.com/helm/helm/issues/5871

**Comment by LinuxSuRen** [comment]
We have fixed it in https://github.com/kubesphere/ks-installer/pull/1931
/close
