### ISSUE TITLE
Last message is wrong in activity of pipeline list

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#249]
Versions Used
KubeSphere: `v3.2.0-alpha.0`

![image](https://user-images.githubusercontent.com/68640256/134466091-442a04da-cdaa-4204-bd05-a4455589f428.png)

/kind bug
/cc @kubesphere/sig-devops
/priority Medium

**Comment by LinuxSuRen** [comment]
This is not a bug. We get the message directly from Jenkins. All Pipeline was triggered by a single user. This should be an improvement. We don't have a plan to fix this.

**Comment by JohnNiang** [comment]
This issue has been resolved by 
- https://github.com/kubesphere/ks-devops/pull/384

I'm going to close this issue.
/close
