### ISSUE TITLE
pipeline name is wrong in gitlab branch

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#250]
Versions Used
KubeSphere: `v3.2.0-alpha.0`

![image](https://user-images.githubusercontent.com/68640256/134472791-970a7644-b33b-4859-a647-e4529cbad28e.png)

**precondition**
pipeline created base on `Gitlab Code Repository`

**Expected result**
`pipeline: gitlab-test`

/kind bug
/cc @kubesphere/sig-devops
/priority Medium

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/149060809-f55e27b1-ee9a-4853-b942-c0b07a8552c9.png)

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-alpha.2`
