### ISSUE TITLE
Error  activity synchronization for Github pipeline

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#260]
`Versions used`
KubeSphere: v3.2.0-alpha.0

To Reproduce
1、Create a GitHub pipeline
2、See pipeline activities

![image](https://user-images.githubusercontent.com/68640256/134792241-17b3bcad-2429-407d-a08e-e9561a5abf08.png)
![image](https://user-images.githubusercontent.com/68640256/134792246-52d22ff5-9342-42a1-9d31-8ad64f15a6a1.png)

/kind bug
/cc @kubesphere/sig-devops
/priority high

**Comment by JohnNiang** [comment]
Please follow up https://github.com/kubesphere/ks-devops/issues/257
