### ISSUE TITLE
Time Used of  failed stage display error

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/ks-devops#265]
**Versions used**
KubeSphere: `v3.2.0-alpha.0`

![image](https://user-images.githubusercontent.com/68640256/134800708-a67f0e43-b69e-4ed1-a8b5-743d9152628a.png)

**Expected behavior**
when stage failed, `time used -`

/kind bug
/assign @kubesphere/sig-console 
/priority low

**Comment by chilianyi** [comment]
<img width="1059" alt="截屏2023-07-28 10 23 13" src="https://github.com/kubesphere/ks-devops/assets/5917832/0295beab-40d9-4a65-a37c-34457a3b2b05">
