### ISSUE TITLE
When the pipeline is executed by replay, the activity is not synchronized from jenkins 

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#272]
**Versions Used**
KubeSphere: `v3.2.0-alpha.0`

**precondition**
pipeline created based on jenkinsfile

**To Reproduce**
1、run pipeline 'test'
2、click on replay in activity list

![image](https://user-images.githubusercontent.com/68640256/134842359-aefe0394-7eec-4201-a350-9f2291614305.png)
![image](https://user-images.githubusercontent.com/68640256/134842380-e6f054ee-35c1-4e82-8596-851dba4336fe.png)

/kind bug
/cc @kubesphere/sig-devops
/priority Medium

**Comment by LinuxSuRen** [comment]
According to my tests, the PipelineRun list page didn't refresh the data regularly. You can see the new record if you refresh the page.

So, I'd like to suggest we refresh the list regularly.

**Comment by wenxin-01** [comment]
issue fixed `nightly-20211008`
