### ISSUE TITLE
Add flags to enable each feature Controllers

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#274]
There are serval controllers that exist in the [controllers](https://github.com/kubesphere/ks-devops/tree/master/controllers) directory. They have different responsibilities. Some of them are possible to use as an independent component.

So, I'd like to suggest adding some flags to make it happened. If you are interested in it, please take a look at the [controller-manager command](https://github.com/kubesphere/ks-devops/blob/332a5d5764e377c52acc34d35de910e7a84efc8f/cmd/controller/app/server.go#L42)

## Requirements

* Be familiar with Golang develop
* Be familiar with the Golang CLI library ([cobra](https://github.com/spf13/cobra))
* Understand what controller-manager is

## References

* https://github.com/spf13/cobra#flags

/good-first-issue

**Comment by DiptoChakrabarty** [comment]
Hey so what kind of flag options should be added here , for example there is a function to get the jenkinsbuildnumber https://github.com/kubesphere/ks-devops/blob/625e555ddd5df7f5a2fa5681ebc86af632979b16/controllers/jenkins/pipelinerun/pipelinerun_controller.go#L264 , should a flag bt added to retrieve that kind of information. Am I thinking in the right way ?

**Comment by LinuxSuRen** [comment]
hi @DiptoChakrabarty thanks for being interested in this issue.

Some controllers can work dependently. Such [jenkins config controller](https://github.com/kubesphere/ks-devops/blob/625e555ddd5df7f5a2fa5681ebc86af632979b16/controllers/jenkins/config/jenkinsconfig_controller.go). So the idea is that we can add a flag to enable them. For example: `cmd --enabled-controllers jenkins-config`. See the code lines [here](https://github.com/kubesphere/ks-devops/blob/625e555ddd5df7f5a2fa5681ebc86af632979b16/cmd/controller/app/controllers.go#L77).

For the default case, we can enable them all.

Hopefully, I provided clear information.
