### ISSUE TITLE
Optimize the default configuration of Devops

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/ks-devops#275]
**Why we need it**
There is no clear basis for the current default parameters of Devops, and more tests are needed to determine an optimal configuration.

![image](https://user-images.githubusercontent.com/68640256/134875837-78753d94-2645-46f2-8b08-2d2071f34df1.png)

/kind feature
/cc @kubesphere/sig-devops

**Comment by chilianyi** [comment]
The default configuration is : https://github.com/kubesphere/ks-installer/blob/62d60e496926e07391b78a19357c6ea94d125b92/roles/ks-devops/defaults/main.yaml#L2
