### ISSUE TITLE
Unstable CI task: BuildTools

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#281]
Recently, we have encountered two failing CI checks in `BuildTools` task. It would be better to improve stability of our CI as soon as possible. But for now, it's not urge for us.

> Please see: 
> - https://github.com/kubesphere/ks-devops/runs/3728639972
> - https://github.com/kubesphere/ks-devops/runs/3673141916

/kind bug

**Comment by chilianyi** [comment]
Can not open the link now.
