### ISSUE TITLE
Support searching logs by devops.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/ks-devops#284]
![image](https://user-images.githubusercontent.com/41519383/135213977-44d923f4-a9ab-4ba3-b0d0-879f25c2bed4.png)
Now we can't search logs by devops.

User story:
When the pipeline status shows queued all the time,the users will need to check the logs.But when the pipeline is queued,we can't check the logs on the pipeline page.So we'd better provide a way by which the users will check logs easiely.
![image](https://user-images.githubusercontent.com/41519383/135214341-f62384d1-683d-4284-b2b3-789259ab0600.png)

**Comment by JohnNiang** [comment]
Maybe we can display event list of PipelineRun here to let users know what happened just now. Below is an example of event list:

```bash
╰─○ kubectl get events -n my-devops-projecttgggn --field-selector involvedObject.name=copied-github-pipeline-rqggk
LAST SEEN   TYPE     REASON    OBJECT                                     MESSAGE
4m14s       Normal   Updated   pipelinerun/copied-github-pipeline-rqggk   Updated running data for PipelineRun my-devops-projecttgggn/copied-github-pipeline-rqggk
```

**Comment by chilianyi** [comment]
<img width="1440" alt="截屏2023-07-28 19 10 05" src="https://github.com/kubesphere/ks-devops/assets/5917832/90a3c9dc-69d1-4211-b66e-5b7444fea9bf">

Users can view the status of the pipeline pod through the event page.
