### ISSUE TITLE
When the agent type is set to node, the pipeline cannot be saved

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/ks-devops#294]
Versions used
KubeSphere:  `nightly-20211008`

![image](https://user-images.githubusercontent.com/68640256/136744863-a46de161-3395-48c4-b5b8-3c161c8ea00f.png)

/kind bug
/cc @kubesphere/sig-devops
/priority high

**Comment by LinuxSuRen** [comment]
It looks like an API call is failed.

![image](https://user-images.githubusercontent.com/1450685/136745242-5ba8bd8a-fa90-4807-a89a-56fc3049f80a.png)
