### ISSUE TITLE
Avoid return secret value of the DevOps credential

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#299]
This is the backend part.

The API is `devops.kubesphere.io/v1alpha3/devops/test6r9qx/credentials/admin?content=1`

https://github.com/kubesphere/ks-devops/blob/be019b7a7c1b2917e9ec5216bc4143dd9551945e/pkg/kapis/devops/v1alpha3/register.go#L78

## References
* https://github.com/kubesphere/console/issues/2131

**Comment by JohnNiang** [comment]
This API `devops.kubesphere.io/v1alpha3/devops/test6r9qx/credentials` still needs to be masked.

https://github.com/kubesphere/ks-devops/blob/be019b7a7c1b2917e9ec5216bc4143dd9551945e/pkg/kapis/devops/v1alpha3/register.go#L59
