### ISSUE TITLE
Role cannot be deleted in Devops project

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/ks-devops#311]
**Versions used**
KubeSphere:  `nightly-20211014`

![image](https://user-images.githubusercontent.com/68640256/137505001-c42f9548-7931-4efb-ab48-377890ae830c.png)

**How To Reproduce**
1. Go to devops project detail page
2.  Click on 'DevOps Project Roles'
3.  Delete any created role
4.  See error

/kind bug
/cc @kubesphere/sig-devops 
/priority  high

**Comment by JohnNiang** [comment]
This issue has been fixed by https://github.com/kubesphere/console/pull/2507. I'm going to close this issue.
/close

**Comment by JohnNiang** [comment]
> /need-to-verify

I've verified the deletion issue. It works well. Please feel free to reopen this issue if you encounter it again.
