### ISSUE TITLE
When Jenkins is closed, after copying pipeline, you cannot enter the detail page of pipeline

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#321]
**Versions used**
KubeSphere:  `v3.2.0-rc.1`

**How To Reproduce**
1、 Stop jenkins
2、Copy pipeline
3、Enter any detail page of pipeline  through click pipeline-name

/kind bug
/cc @kubesphere/sig-devops
/priority low

**Comment by JohnNiang** [comment]
This issue has been fixed by https://github.com/kubesphere/console/pull/2544. I'm going to close this issue.
/close
