### ISSUE TITLE
PipelineRun will still be repeated here

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#325]
Please see the repeated PipelineRuns:

![image](https://user-images.githubusercontent.com/16865714/138235965-79b6897e-a30f-47d3-9658-a420163c4ad8.png)

**How to reproduce?**

1. Create a Pipeline which Jenkinsfile is as below:

```groovy
pipeline {
    agent any
    stages {
        stage('Non-Parallel Stage') {
            steps {
                echo 'This stage will be executed first.'
            }
        }
        stage('Parallel Stage') {
            when {
                branch 'master'
            }
            failFast true
            parallel {
                stage('Branch A') {
                    agent {
                        label "for-branch-a"
                    }
                    steps {
                        echo "On Branch A"
                    }
                }
                stage('Branch B') {
                    agent {
                        label "for-branch-b"
                    }
                    steps {
                        echo "On Branch B"
                    }
                }
            }
        }
    }
}
```

2. Click `Run` button to create PipelineRun

> Please note that this scenario does not happen every time. But more will happen for the first time.

/kind bug
/priority high
/area devops
/assign
/milestone v3.2

**Comment by JohnNiang** [comment]
I have temporary solution here: Remove duplicate PipelineRuns in [PipelineRun synchronizer](https://github.com/kubesphere/ks-devops/blob/master/controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go) for ks-devops 3.2.x. We will complete better solution mentioned at https://github.com/kubesphere/ks-devops/issues/325#issuecomment-952658047 in the future.

@LinuxSuRen , what do you reckon about this solution?

**Comment by LinuxSuRen** [comment]
I prefer to have a good-enough solution. Because we have enough time to do it before the next release.
