### ISSUE TITLE
integrate external jenkins into kubesphere,    jenkins  Operate in full accordance with the tutorial, but you can't synchronize the pipeline to Jenkins

### ISSUE THREAD

**Issue by tengxunchao** [kubesphere/ks-devops#333]
Tutorial link:
https://jenkins-zh.cn/wechat/articles/2021/01/2021-01-11-exteranl-jenkins-in-kubesphere

I operate according to the tutorial above. The current error is: after creating a new Devops project and pipeline in the project on kubesphere, click the pipeline to report an error like the picture below:
<img width="952" alt="FC9EFF8F-D094-4d9d-99A8-36D4B99263B3" src="https://user-images.githubusercontent.com/54707265/139027826-4730c9aa-2564-4362-9d32-85f4d33e7ed1.png">

And,  the pipeline created by kubesphere cannot be synchronized to the external Jenkins!

Now I want to know the following questions:
1. Does the kubesphere Jenkins auth plug-in of Jenkins need to configure the kubesphere account and password? If necessary, where to configure it?
    Now I click test connection and an error will occur:
<img width="952" alt="F7A2C867-9AE0-44dd-AF37-555E873E6927" src="https://user-images.githubusercontent.com/54707265/139029084-e329ab88-735b-4218-8684-ad1ae0b595e1.png">

2. In kubesphere configuration, the configuration in configmap: kubesphere system / kubesphere config: how to fill in devops.password: fill in the plaintext or ciphertext of the login password?
<img width="736" alt="0ED89A02-11EB-417a-96E9-E93149C46BCC" src="https://user-images.githubusercontent.com/54707265/139029586-6c451fdb-ef04-4e36-9caa-7cec58b90492.png">

Kubesphere and Jenkins can't see the log of  errors. Please provide me with ideas  to solve the problem. Thank you very much!

**Comment by gitzhuww** [comment]
![image](https://user-images.githubusercontent.com/40748699/160776135-207f33f4-6c16-45c1-a225-f83a6330b0f2.png)

**Comment by gitzhuww** [comment]
@tengxunchao help please!
