### ISSUE TITLE
B2I : Missing fontconfig in kubesphere/java-8-runtime

### ISSUE THREAD

**Issue by chaunceyjiang** [kubesphere/ks-devops#337]
**Describe the Bug**
B2I : Missing fontconfig in kubesphere/java-8-runtime
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
1 master: 16cpu/32g 8 nodes :16cpu/32g

**How To Reproduce**
Select jar b2i, upload the jar package.check the log

```
 sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
```

**Expected behavior**
Rebuild the image and add `fontconfig ttf-dejavu`

**Comment by JohnNiang** [comment]
Hi @Feeeenng , please refer to https://github.com/kubesphere/s2i-java-container/blob/master/java/images/centos/Dockerfile

**Comment by JohnNiang** [comment]
Anyone wants to contribute this feature can add `fontconfig` to https://github.com/kubesphere/s2i-java-container/blob/master/java/images/centos/Dockerfile.
