### ISSUE TITLE
ks-jenkins often restart for an unknown reason

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/ks-devops#339]
ks-jenkins经常莫名其妙重启，健康检查失败导致，但为何检测失败不知道，是否是有什么兼容性问题，ks版本：3.1.0，ks-jenkins镜像：kubespheredev/ks-jenkins:3.2.0-rc0-2.249.1，ks-j enkins日志如附件
[ks-jenkins.log](https://github.com/kubesphere/kubesphere/files/7452909/ks-jenkins.log)

**Comment by LinuxSuRen** [comment]
Thanks for reaching out to us. But we encourage everyone to communicate with each other in GitHub in English. Please visit [the Chinese forum](https://kubesphere.com.cn/forum/) if you prefer to use Chinese.

In most cases, Jenkins might restart itself for the following reasons:

* out the of the memory/cpu
  * in this case, please try to get the monitor data during the Jenkins restart time
* with some incompatible plugins
  * please check if you have installed other plugins which do not come from [ks-jenkins](https://github.com/kubesphere/ks-jenkins/) 

/kind support

**Comment by knowwinter** [comment]
How much memory and CPU are appropriate? There are about 50 concurrent tasks

**Comment by knowwinter** [comment]
How to determine whether the plug-in has compatibility problems? We use the image source provided by you. We have not installed any plug-ins, except for loading some shared pipelines libraries

**Comment by LinuxSuRen** [comment]
ks-jenkins does not have plugin `ssh-server`

![image](https://user-images.githubusercontent.com/1450685/139830053-ed9ec57c-10d1-447c-876f-e5990086e437.png)

**Comment by JohnNiang** [comment]
> How much memory and CPU are appropriate? There are about 50 concurrent tasks

You could monitor `ks-jenkins` deployment like this:

![image](https://user-images.githubusercontent.com/16865714/139864448-d550bba1-bc72-4b50-87a7-2896463876a3.png)

**Comment by LinuxSuRen** [comment]
Please feel to open this issue if you have more clues on this issue. But I'm going to close this issue due to no response for a long time.
