### ISSUE TITLE
Request to upgrade dependencies in go.mod

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#353]
At present, our project dependencies defined in go.mod file that are too old may not be able to run in Kubernetes 1.22 correctly, especially when we create a webhook targeting for some CRDs.

I suggest upgrading dependencies related Kubernetes, such as `sigs.k8s.io/controller-runtime`, `k8s.io/api` and so on.

There was an example for that: https://github.com/kubesphere/s2ioperator/pull/163.

/kind enhancement

**Comment by lxm** [comment]
So, let's continue our discussion here.
I want to express whether there has been some tentative work before to help people who want to work on this PR figure out what needs to be done. @LinuxSuRen @kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
This is great to do the upgrade work. Because we will have enough to do the test work.
