### ISSUE TITLE
升级文档中的sonarqube组件版本

### ISSUE THREAD

**Issue by LeonDevLifeLog** [kubesphere/ks-devops#354]
由于SonarQube安全问题，建议升级文档中SonarQube组件版本。虽然说SonarQube组件也算是内网环境。

https://kubesphere.com.cn/docs/devops-user-guide/how-to-integrate/sonarqube/

参考： https://www.freebuf.com/vuls/303951.html

**Comment by LeonDevLifeLog** [comment]
helm 部署方式，用户可以手动指定版本。

**Comment by LeonDevLifeLog** [comment]
可以升级一下仓库的默认版本号到安全的版本

**Comment by LinuxSuRen** [comment]
Thanks so much for letting us know this. I'm thinking if you could help to create an issue on the website repo. It must be helpful to let more users know about it.

https://github.com/kubesphere/website/issues

**Comment by JohnNiang** [comment]
The problem is more suitable for submitting an issue in [kubesphere/helm-charts](https://github.com/kubesphere/helm-charts).

Because the SonarQube chart is hosted in [here](https://github.com/kubesphere/helm-charts/tree/master/src/main/sonarqube).
