### ISSUE TITLE
When executing a pipeline that requires input parameters, no input box pops up

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/ks-devops#361]
**Versions used**
KubeSphere:  `v3.2.0`

How To Reproduce

1、Go to pipeline list
2、Select pipeline 
3、Click on 'Run'
![image](https://user-images.githubusercontent.com/68640256/142796806-03ed3def-197d-446b-9ceb-dab04b0c70f7.png)

```
pipeline {
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    stages {
        stage('Example') {
            steps {
                echo "Hello ${params.PERSON}"
            }
        }
    }
}
```

**Expected behavior**
When you click to run, the following pop-up window is displayed.
![image](https://user-images.githubusercontent.com/68640256/142797000-a766a159-b3a1-40a4-8808-4b615e7479a9.png)

/kind bug
/cc @kubesphere/sig-devops
/priority medium

**Comment by chilianyi** [comment]
same as：https://github.com/kubesphere/ks-devops/issues/839
