### ISSUE TITLE
Cannot delete pipeline when Jenkins is closed

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#362]
**Versions used**
KubeSphere:  `v3.2.0`

How To Reproduce

1、Close Jenkins  `kubectl scale deploy devops-jenkins -n kubesphere-devops-system --replicas=0`
2、Delete any pipeline in pipeline list

**Except Behavior**
successfully deleted，pipeline do not exists in pipeline list

**Actual Behavior**
The deletion failed, and the pipeline still exists in pipeline list.
when Jenkins restart, viewing the details of the pipeline, it prompts that the pipeline does not exist, and then it disappears from the pipeline list

/kind bug
/cc @kubesphere/sig-devops
/priority medium

**Comment by LinuxSuRen** [comment]
This is by design. We need to remove the corresponding Jenkins job when users want to delete a Pipeline.

/close
/remove-kind bug
