### ISSUE TITLE
v3.2   pipeline  approval error reported

### ISSUE THREAD

**Issue by cla52013** [kubesphere/ks-devops#363]
![image](https://user-images.githubusercontent.com/7485132/142821152-85d517d6-eb74-405d-bf54-7655f47b5901.png)

![image](https://user-images.githubusercontent.com/7485132/142821284-383f65c8-2513-4893-8d35-5436d7d18750.png)

But I can run it through Jenkins 'system
![image](https://user-images.githubusercontent.com/7485132/142821582-868ab8b9-11ec-499e-8cb4-6a4b847f50c8.png)

jenkinsfile
```
        stage('部署生产环境') {
          when{
            expression{
              return params.TAG_NAME =~ /v.*/
            }
          }
          steps {
            input(id: 'deploy-to-prod', message: 'deploy to prod?')
            kubernetesDeploy(configs: 'deploy/yaml/**', enableConfigSubstitution: true, kubeconfigId: "$KUBECONFIG_CREDENTIAL_ID_PROD")
          }
        }
```

**Comment by JohnNiang** [comment]
After you clicked the `Proceed` button, please try to refresh the current page manually.

**Comment by cla52013** [comment]
> After you clicked the `Proceed` button, please try to refresh the current page manually.

This is another situation ，the pipeline invalid

**Comment by JohnNiang** [comment]
> > After you clicked the `Proceed` button, please try to refresh the current page manually.
> 
> This is another situation ，the pipeline invalid

Auto-refresh function is no longer working in KubeSphere 3.2.0, but we have fixed it in
- https://github.com/kubesphere/console/pull/2594

This problem is caused by another issue which auto-refresh function dose not work. In fact, you have already approved your Pipeline.

**Comment by cla52013** [comment]
> > > After you clicked the `Proceed` button, please try to refresh the current page manually.
> > 
> > 
> > This is another situation ，the pipeline invalid
> 
> Auto-refresh function is no longer working in KubeSphere 3.2.0, but we have fixed it in
> 
> * [fix:  Fix the running status and log not be auto-updated in the pipeline console#2594](https://github.com/kubesphere/console/pull/2594)
> 
> Your problem is caused by the issue above which auto-refresh function dose not work. In fact, you have already approved your Pipeline.

https://github.com/kubesphere/console/pull/2594   I Know

Is not the case，I hit refresh and still waiting for approval，this is new case

**Comment by JohnNiang** [comment]
Which user and corresponding role are you operating?

**Comment by cla52013** [comment]
> Which user and corresponding role are you operating?
accouns is the platform-admin  and devops  project-admin

Not all assembly lines cannot be approved

**Comment by JohnNiang** [comment]
My test Jenkinsfile is as follows:

```groovy
pipeline {
  agent none
  stages{
    stage('Input test') {
      steps {
        input(id: 'deploy-to-prod', message: 'deploy to prod?')
      }
    }
  }
}
```

And it always behaviors as expected:

![image](https://user-images.githubusercontent.com/16865714/142838965-4c100d30-e197-457b-8dd8-edd8075d96a3.png)

**Comment by JohnNiang** [comment]
Hi @cla52013 , there is no chance to catch the error log anywhere.

I've submitted related issue at https://github.com/kubesphere/ks-devops/issues/366, please follow up it.

**Comment by cla52013** [comment]
> Hi @cla52013 , there is no chance to catch the error log anywhere.
> 
> I've submitted related issue at #366, please follow up it.


Why did this error occur? Do I need to modify my pipeline? Or a bug?

**Comment by JohnNiang** [comment]
Have you test Jenkinsfile described at https://github.com/kubesphere/ks-devops/issues/363#issuecomment-975339137 in your environment?

If that dose not work well, please provide your Jenkinsfile for us.
