### ISSUE TITLE
Choice parameter is not rendered correctly

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#365]
### What happened?

`Build Parameters` setting was as follows:
![image](https://user-images.githubusercontent.com/16865714/142872684-edb079e3-4512-41b2-aafa-4b17a26e5586.png)

But when I ran the Pipeline, I got an `input` instead of `select`:

![image](https://user-images.githubusercontent.com/16865714/142872912-a2d1c9d8-9b23-479f-a293-8d4c8eec5046.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/16865714/142877535-a4d9d96f-6944-4bc9-8fb3-986058e23ac9.png)

**Note:** I'm not sure whether this issue is caused by frontend or backend, so I submit this issue at here currently.

> https://kubesphere.com.cn/forum/d/6126-v32-devops-choice [In Chinese]

/kind bug
/priority high

**Comment by LinuxSuRen** [comment]
I prefer to file the front-end issues to https://github.com/kubesphere/console/issues

**Comment by JohnNiang** [comment]
> I'm not sure whether this issue is caused by frontend or backend, so I submit this issue at here currently.

I'm not sure whether this issue is caused by frontend or backend, so I submit this issue at here currently.
