### ISSUE TITLE
3.1.1 Upgrade 3.2.0 The devops status cannot be updated automatically, and the user information is not correct.

### ISSUE THREAD

**Issue by xwb-spec** [kubesphere/ks-devops#372]
![image](https://user-images.githubusercontent.com/13009409/143158564-eda18dbb-3ae1-4579-b944-20ed273735fd.png)

The publishing user is not admin, but all show admin，The devops status cannot be updated automatically

**Comment by LinuxSuRen** [comment]
hi @gzdreamfly thanks for reaching out to us. But please only create different issues for each problem. IMO you just reported two problems.

For the status part, we already fixed it. See https://github.com/kubesphere/console/pull/2594

For the users' part, this is a historical issue. We will improve it.

/kind bug
