### ISSUE TITLE
Does kubesphere support multijob pipelining?

### ISSUE THREAD

**Issue by tengxunchao** [kubesphere/ks-devops#390]
Does kubesphere support multijob pipelining?

like this: 

<img width="815" alt="394969F0-45A5-4771-98A5-3AD03CA6A77A" src="https://user-images.githubusercontent.com/54707265/144223098-359392cb-3a20-4ed8-9814-e76435555cf2.png">
<img width="825" alt="4B40D11C-781A-48ae-92B8-7BA87E469578" src="https://user-images.githubusercontent.com/54707265/144223178-cd77ae60-5111-40c3-9a78-46a6c97cc441.png">

**Comment by LinuxSuRen** [comment]
Not yet. I'm glad to know the use cases about how to use multi-job.

/kind support

**Comment by tengxunchao** [comment]
> Not yet. I'm glad to know the use cases about how to use multi-job.
> 
> /kind support

Our usage scenario is to create a multitask to trigger multiple pipeline execution

**Comment by LinuxSuRen** [comment]
You can use the Jenkins Pipeline step `build` as well. See the official document.

https://www.jenkins.io/doc/pipeline/steps/pipeline-build-step/

So, users don't need to install more plugins.

**Comment by tengxunchao** [comment]
> You can use the Jenkins Pipeline step `build` as well. See the official document.
> 
> https://www.jenkins.io/doc/pipeline/steps/pipeline-build-step/
> 
> So, users don't need to install more plugins.

ok  thanks!
