### ISSUE TITLE
The pipelined task cannot be run and terminated properly.

### ISSUE THREAD

**Issue by luoyuctl** [kubesphere/ks-devops#400]
![image](https://user-images.githubusercontent.com/51604064/144752879-f7d75433-ea13-4b0c-834e-ebe91b7b98f1.png)

1. Terminating the mission is wrong. A parameter in url is undefined.
2. I think it is due to the failure of the task to create successfully.
3. After I switched the mirror back to 3.20, the task was running and terminated normally.

**Versions Used**
kubespheredev/devops-controller:master
kubespheredev/devops-apiserver:master
Kubernetes: 1.20

**How To Reproduce**
1. Click the stop run button (All branches behave the same)

**Comment by LinuxSuRen** [comment]
hi @luoyuctl ， thanks for reporting this issue. I guess we need to disable the `Stop` button or hide it. Because the Pipeline has not started yet. We cannot stop it as well.

By the way, I suggest users use a nightly version instead of the master tag. There is no way to know which version is by the master.

**Comment by luoyuctl** [comment]
> hi @luoyuctl ， thanks for reporting this issue. I guess we need to disable the `Stop` button or hide it. Because the Pipeline has not started yet. We cannot stop it as well.
> 
> By the way, I suggest users use a nightly version instead of the master tag. There is no way to know which version is by the master.

1205nightly version can reproduce the problem.

**Comment by luoyuctl** [comment]
> hi @luoyuctl ， thanks for reporting this issue. I guess we need to disable the `Stop` button or hide it. Because the Pipeline has not started yet. We cannot stop it as well.
> 
> By the way, I suggest users use a nightly version instead of the master tag. There is no way to know which version is by the master.

and another problem the tasks wouldn't be running

**Comment by luoyuctl** [comment]
@JohnNiang Help me to have a look. After fixing this problem, I can use the devops assembly line normally.

**Comment by JohnNiang** [comment]
@luoyuctl, IMO, this problem won't stop you use DevOps normally. If you upgraded to v3.2.1, they would be gone.

Anyway, this is not a bug, on the contrary, it's an improvement. Do you want to have a try to solve this problem?😃 

I have a brief plan to improve that:
- Firstly, backend service needs to provide a `Delete` API for PipelineRun.
- Secondly, console need to let a PipelineRun be deleted.

**Comment by luoyuctl** [comment]
> @JohnNiang Help me to have a look. After fixing this problem, I can use the devops assembly line normally.

![image](https://user-images.githubusercontent.com/51604064/144824019-1f45dda9-66a4-45c9-ac05-9ac76965250f.png)

The assembly line has not been running since it was clicked to run.

i used kubespheredev/devops-controller/3.2.1-rc.2 and kubespheredev/devops-apiserver/3.2.1-rc.2 image with newest ks-console can reproduce the problem.

**Comment by LinuxSuRen** [comment]
hi @luoyuctl I'm wondering if you could check the status of this job on Jenkins. If there is no corresponding Pipeline build. You can delete the pipelinerun from k8s by `kubectl`

**Comment by luoyuctl** [comment]
> hi @luoyuctl I'm wondering if you could check the status of this job on Jenkins. If there is no corresponding Pipeline build. You can delete the pipelinerun from k8s by `kubectl`


I looked at the Jenkins, where no corresponding task was created or run

**Comment by luoyuctl** [comment]
> hi @luoyuctl I'm wondering if you could check the status of this job on Jenkins. If there is no corresponding Pipeline build. You can delete the pipelinerun from k8s by `kubectl`

but when i change devops-apiserver and devops-controller version to 3.2.0, these tasks start running in Jenkins

**Comment by LinuxSuRen** [comment]
hi @luoyuctl is that possible to let others reproduce the problem. By the way, I'd like to invite you to join the DevOps SIG WeChat group. If you add me as a contact: `linuxsuren`.

**Comment by luoyuctl** [comment]
After my investigation, it was the problem of LDAP permission synchronization between clusters. I connected the LDAP of Jenkins to the Host cluster and repaired it.

**Comment by LinuxSuRen** [comment]
If I understand it correctly, https://github.com/kubesphere/kubesphere/pull/4436 fixed the LDAP issue.

**Comment by LinuxSuRen** [comment]
/kind support

Consider you have fixed it. I guess we can close this issue. You can close it with command: `/close`

**Comment by JohnNiang** [comment]
> 

I've fired [another issue](https://github.com/kubesphere/console/issues/2780) against the remaining problem: Error occurred while clicking `Stop` button on Pipeline run record which is not run yet.
