### ISSUE TITLE
The default webhook cannot be triggered in the case of multiple clusters.

### ISSUE THREAD

**Issue by luoyuctl** [kubesphere/ks-devops#402]
![image](https://user-images.githubusercontent.com/51604064/144781357-8e13e1f0-d9cb-46aa-8b03-db4b1f29d6b2.png)

Here is the default webhook url : 
> http://xxx/devops_webhook/git/?url= Git HTTP URL

Webhook address that works in a multi-cluster state: 
>http://xxx/kapis/clusters/ clustername  /devops.kubesphere.io/v1alpha2/webhook/git/?url= Git HTTP URL

#### Please fix it to enhance the developer experience.

**Versions Used**
kubespheredev/devops-controller:v3.2.0
kubespheredev/devops-apiserver:v3.2.0
Kubernetes: 1.20

**Comment by luoyuctl** [comment]
@LinuxSuRen @harrisonliu5 @JohnNiang

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen @harrisonliu5 @JohnNiang

Thanks for reaching out to us. We have a SIG team on this project. So, you can ping the whole team instead of the individual.

/cc @kubesphere/sig-devops

**Comment by luoyuctl** [comment]
> > @LinuxSuRen @harrisonliu5 @JohnNiang
> 
> Thanks for reaching out to us. We have a SIG team on this project. So, you can ping the whole team instead of the individual.
> 
> /cc @kubesphere/sig-devops

any address?

**Comment by LinuxSuRen** [comment]
Considering we will have the new webhook feature. I'm going to close this issue.

See also https://github.com/kubesphere/ks-devops/issues/598
/close
