### ISSUE TITLE
The state is still not refreshed after pipeline input   v3.2.1-rc.2 

### ISSUE THREAD

**Issue by cla52013** [kubesphere/ks-devops#405]
I am using 3.2.1 rc2

When I type the button becomes unclickable, but the status still doesn't refresh, I need to manually refresh the browser

![image](https://user-images.githubusercontent.com/7485132/144989166-47f15fe6-5949-4716-a3e7-6020c4d18e5a.png)

**Comment by LinuxSuRen** [comment]
@cla52013 thanks for reporting this issue. Would you mind telling us which user (role name) do you use?

**Comment by cla52013** [comment]
> 

my role is admin

**Comment by cla52013** [comment]
> @cla52013 thanks for reporting this issue. Would you mind telling us which user (role name) do you use?

my role is  admin

**Comment by JohnNiang** [comment]
Hi @cla52013 , how do you upgrade to KubeSphere v3.2.1-rc.2? And what's the image name of `ks-console`?

**Comment by wenxin-01** [comment]
HI @cla52013 , do you have input data?

**Comment by cla52013** [comment]
> how do you upgrade to KubeSphere v3.2.1-rc.2? And what's the image name of `ks-console`?
image name：kubespheredev/ks-console:v3.2.1-rc.2

I used  kubectl apply -f  cluster.yaml  ks-install.yaml

**Comment by cla52013** [comment]
> do you have input data?


> HI @cla52013 , do you have input data?
yes ， I  click  proceed or  break

**Comment by wenxin-01** [comment]
> > do you have input data?
> 
> > HI @cla52013 , do you have input data?
> > yes ， I  click  proceed or  break
Did you create and run this pipeline?  because I find I can not  proceed or break the pipeline created by others.

**Comment by cla52013** [comment]
> > > do you have input data?
> > 
> > 
> > > HI @cla52013 , do you have input data?
> > > yes ， I  click  proceed or  break
> > > Did you create and run this pipeline?  because I find I can not  proceed or break the pipeline created by others.

yes，At first it was clickable, It becomes unclickable after being clicked， but the status was not updated

**Comment by JohnNiang** [comment]
This issue has been fixed by https://github.com/kubesphere/console/pull/2544. I'm going to close this issue.
/close

**Comment by JohnNiang** [comment]
I'm sorry for wrongly closing this issue.
/reopen

**Comment by LinuxSuRen** [comment]
hi @harrisonliu5 , I'm wondering if you could help us to confirm if this issue still exists. Thanks.

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/164144844-66613ec2-9b97-497b-9687-921e2287fc2a.mov

@LinuxSuRen

**Comment by LinuxSuRen** [comment]
hi @harrisonliu5 , thanks. It looks good. I'm going to close this issue.
/close
