### ISSUE TITLE
Can not proceed or break the pipeline created by others

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#407]
**Versions used**
KubeSphere: `v3.2.1-rc.2`

How To Reproduce

1、Create pipeline use the following Jenkinsfile with account 'A'
```
pipeline {
    agent any
    stages {
        stage('Example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
    }
}

```
2、Run the pipeline created in step 1 with account 'admin'
3、Proceed or break the pipeline in 'Record details' page

**Actual behavior**

user admin can not  proceed or break the pipeline

https://user-images.githubusercontent.com/68640256/145140855-77c59d94-2787-44d4-abb8-f3d92cb2df6b.mov

/kind bug
/cc @kubesphere/sig-devops 
/priority high

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/145142286-42b44ac3-c20a-4244-8a08-f08cfd8decc9.png)

**Comment by JohnNiang** [comment]
@wenxin-01 , thank you for reaching out here! I've already reproduced this problem and am trying to figure out it.
