### ISSUE TITLE
Support trigger Pipeline run by manipulate CRDs instead of calling Jenkins API

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#41]
## Background

Currently, the flow of triggering a Pipeline likes blew:

`front-end send HTTP request -> apiserver receive -> call Jenkins API`

There're some big obvious problems with it.

* Users will get an error if Jenkins is offline
* The UI cannot give users a quick response due to it relies on Jenkins API directly
* This is not a k8s native way
  * Everything is a resource

## Proposal

There're two potential solutions that we can take. I've not spent time researching them. Please consider adding more details on them, or I'm glad to hear other solutions.

* Invest a new CRD `PipelineRun`
* Trigger a Pipeline by creating a K8S job
  * There's an example. Trigger an S2I run by K8S job now

Before we really get started on any proposal. Please provide the pros and cons for each of them.

## What do I need to do?

* Support trigger a PipelineRun via CLI (aka [ks](https://github.com/kubesphere-sigs/ks))
* TBD

## Compitable

* Make sure to provide a compatible solution with the current API.

**Comment by JohnNiang** [comment]
After some investigation,


- Invest CRD `PipelineRun`

  - pros
    We could abstract PipelineRun and store pipeline run status and comunicate with other CI/CD tools, like Jenkins, Tekton, ArgoCD.
  - cons
    Currently, no obvious cons found.

- Triggered Pipeline by K8s Job
  - pros
    For different clients, like Jenkins, Tekton, we could start different jobs to call clients.
  - cons
    But it's more complicated than controller and cannot abstract PipelineRun. And this approach is more like Pod generated by TaksRun in Tekton.

I prefer to invest a new CRD `PipelineRun` to implement this feature.

**Comment by JohnNiang** [comment]
Design details: https://shimo.im/docs/wpQQw3jrxwhc8xtG (in Chinese).

**Comment by shihaoH** [comment]
> Design details: https://shimo.im/docs/wpQQw3jrxwhc8xtG (in Chinese).

Permission denied

**Comment by JohnNiang** [comment]
@shihaoH , thanks for your reminding, I've changed document share permission.

**Comment by JohnNiang** [comment]
> Design details: https://shimo.im/docs/wpQQw3jrxwhc8xtG (in Chinese).

I've updated design detail. Please have a look at and I would appreciate it if you could give me a feedback.

**Comment by LinuxSuRen** [comment]
I guess we can close this issue.

**Comment by JohnNiang** [comment]
> I guess we can close this issue.

I'm going to close this issue because we have almost completed it, although there still are some remaining functions, like replay, stop.
