### ISSUE TITLE
Unable to delete Jenkins build while PipelineRun was deleted

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#417]
### What happened

When we try to delete a PipelineRun, the build in Jenkins won't be deleted. And something wrong happens:

Log details in `devops-controller`:
```go
E1222 06:23:58.829460       1 pipelinerun_controller.go:71] pipelinerun-controller "msg"="unable to fetch PipelineRun" "error"="PipelineRun.devops.kubesphere.io \"multi-branch-test-f7mwq\" not found" "PipelineRun"={"Namespace":"my-devops-projectdq8jj","Name":"multi-branch-test-f7mwq"} 
```

### Steps to reproduce

1. Create a Pipeline and run it
1. Delete a PipelineRun  
    ```bash
    kubectl -n $NAMESPACE delete pipelineruns.devops.kubesphere.io $PIPELINE_RUN
    ```
1. See the build in Jenkins dashboard

/kind bug

**Comment by LinuxSuRen** [comment]
After I did some work, this issue only happen on the multi-branch Pipeline.
