### ISSUE TITLE
Request to push nightly images to a separate repo

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#419]
As you can see from the following screenshot. There are too many image tags. It's hard to find useful tags.

So, I suggest that we push the nightly images to a separate repo. For instance, we can push `ghcr.io/kubesphere/devops-tools:nightly-20211221` to `ghcr.io/kubesphere-nightly/devops-tools:nightly-20211221`.

![image](https://user-images.githubusercontent.com/1450685/147061620-14563a79-f54f-40a3-abfd-d7d790f1533c.png)

## References
* https://github.com/kubesphere/ks-devops/blob/master/.github/workflows/nightly-build.yaml

/good-first-issue

**Comment by gotoworld** [comment]
maybe it's not only tag and push to another separate repo, it's good to tigger by git source code branch or git tag, by this we   can relate  feature code to image version。 and make the separate repo image version is meanfull.
