### ISSUE TITLE
External Jenkins, kubesphere open pipeline error

### ISSUE THREAD

**Issue by tengxunchao** [kubesphere/ks-devops#421]
Kubesphere is externally connected to Jenkins, and the pipeline synchronization has passed (the pipeline can be seen by external Jenkins), but an error is reported when entering the pipeline on kubespehre:

![image](https://user-images.githubusercontent.com/54707265/147218675-cc640d6e-a89d-4678-840a-3f5a1f4f4bcd.png)

The pipeline "6666" has been synchronized in the external Jenkins: 
![image](https://user-images.githubusercontent.com/54707265/147219607-20860129-d7b5-448e-b6c3-216595861d76.png)

Jenkins and kubesphere use the same account password.

External Jenkins version: 2.285
Kubesphere version: 3.1.1

kubesphere's  ks-controller-manager error log:
`I1223 17:14:27.309784 1 event.go:278] Event(v1.ObjectReference{Kind:"User", Namespace:"", Name:"yanyuzhuo-qm", UID:"626f1591-7fc0-4322-8798-82aa1801993b", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"5780435", FieldPath:""}): type: 'Normal' reason: 'Synced' User synced successfully

E1223 17:19:29.013852 1 project_pipeline.go:147] GET http://10.133.67.55:8080/job/s1krf8l/job/6666/api/json: 404 <html>

<head>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>

<title>Error 404 Not Found</title>

</head>

<body><h2>HTTP ERROR 404 Not Found</h2>

<table>

<tr><th>URI:</th><td>/job/s1krf8l/job/6666/api/json</td></tr>

<tr><th>STATUS:</th><td>404</td></tr>

<tr><th>MESSAGE:</th><td>Not Found</td></tr>

<tr><th>SERVLET:</th><td>Stapler</td></tr>

</table>

<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.38.v20210224</a><hr/>

</body>

</html>`

This is an external Jenkins log:

```
December 23, 2021 5:19:28 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:29 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:29 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:29 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:29 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:30 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:30 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
```

**Comment by tengxunchao** [comment]
@LinuxSuRen   could you help me?   errors are below:  i can't find the error in  code on github([KubesphereApiTokenAuthenticator](https://github.com/kubesphere/kubesphere-token-auth-plugin))
December 23, 2021 5:19:30 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin

**Comment by LinuxSuRen** [comment]
So, what is the real URL of the Jenkins job `6666`?

By the way, for the external Jenkins, I'm not sure what extra plugins have you installed. So, it might be not easy to do the troubleshooting work. You could help us to improve the [build-in ks-jenkins](https://github.com/kubesphere/ks-jenkins) if you're interested in it.

/kind support

**Comment by tengxunchao** [comment]
> So, what is the real URL of the Jenkins job `6666`?
> 
> By the way, for the external Jenkins, I'm not sure what extra plugins have you installed. So, it might be not easy to do the troubleshooting work. You could help us to improve the [build-in ks-jenkins](https://github.com/kubesphere/ks-jenkins) if you're interested in it.
> 
> /kind support

real url is :  http://10.133.67.175:30880/22222/clusters/default/devops/s1krf8l/pipelines/6666 

And I can open the 666 link of controller manager. The only problem may be the opening permission. In kubesphere config configuration, I fill in the newly generated API token, which should not be a problem, 
![image](https://user-images.githubusercontent.com/54707265/147335345-06805551-df08-485f-8d6e-32327b0f39ff.png)

The key to the problem lies in Jenkins' error reporting: is it caused by the problem of account and password?
```
December 23, 2021 5:19:30 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
December 23, 2021 5:19:30 PM serious io kubesphere. jenkins. devops. auth. KubesphereApiTokenAuthenticator authenticate
cannot get the review response or status is null by admin
```

**Comment by tengxunchao** [comment]
already ok,  the reason is some Jenkins plugins are not installed,  should install as   https://github.com/kubesphere/ks-jenkins/formula.yaml .
