### ISSUE TITLE
upgrade 3.2.1, run  pipeline  failure 

### ISSUE THREAD

**Issue by myokok** [kubesphere/ks-devops#427]
centos 7.9系统,一个master,多个worker节点,，
使用kk直接安装k8s和 kubesphere ；升级也是使用kk升级的。

安装的时候kk版本是 v1.2.0；
升级的时候  kk版本是v1.2.1

orgin version:
k8s 1.20.4
kuebsphere 3.2.0

upgrade versions:
k8s 1.21.5
kubesphere 3.2.1

--------------------------------------
build the orgin pipeline  failure.  and the  pods of   kubesphere-devops-worker  is  been  ContainerCreating-->Terminating --->Destroy   。
升级过后，devops项目中运行流水线，一直卡在如下的界面，查看了下pods，发现 相关devops-worker的pods也是一直在创建和销毁中循环。

![image](https://user-images.githubusercontent.com/44723876/147518345-152e02ec-38d4-4759-b417-e84acbc7941e.png)

![image](https://user-images.githubusercontent.com/44723876/147518923-c5d2ce9b-2828-4b95-b161-537923bb8b87.png)

**Comment by JohnNiang** [comment]
Please describe Pod `base-*` and see the events.

**Possible reason**:
- Pulling image `kubesphere/builder-base` timeout. Please wait for a while.

**Comment by myokok** [comment]
> describe

[root@k8smaster fone]# kubectl describe pod -n kubesphere-devops-worker  base-vn524
Name:                      base-vn524
Namespace:                 kubesphere-devops-worker
Priority:                  0
Node:                      k8snode5/10.10.1.216
Start Time:                Tue, 28 Dec 2021 10:12:53 +0800
Labels:                    ippool.network.kubesphere.io/name=default-ipv4-ippool
                           jenkins=slave
                           jenkins/label=base
                           jenkins/label-digest=3618ad4590b5aeeaf5022be929b8ba84d836466c
Annotations:               cni.projectcalico.org/containerID: 480f7ff60cc4d7dba0b1045d67f35c1aee85bb6ccdc9250522a363b227bd2731
                           cni.projectcalico.org/podIP: 10.233.68.93/32
                           cni.projectcalico.org/podIPs: 10.233.68.93/32
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  30s
IP:                        10.233.68.93
IPs:
  IP:  10.233.68.93
Containers:
  jnlp:
    Container ID:  docker://c30b3563a74b17c4f0d7036e0511a3c8b48ef07db5aff2882015cb59070e775b
    Image:         jenkins/jnlp-slave:3.27-1
    Image ID:      docker-pullable://jenkins/jnlp-slave@sha256:a5f42dab13d74c079a653408e45cda3ca2bc3483200bbaa44b88fae486ad7e05
    Port:          <none>
    Host Port:     <none>
    Command:
      jenkins-slave
    Args:
      7eadef2ab150b43c87cd23fff478d52621e15783c9c71f927fdfae4289ed6bda
      base-vn524
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 28 Dec 2021 10:12:54 +0800
      Finished:     Tue, 28 Dec 2021 10:12:56 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  1536Mi
    Requests:
      cpu:     50m
      memory:  400Mi
    Environment:
      JENKINS_SECRET:         7eadef2ab150b43c87cd23fff478d52621e15783c9c71f927fdfae4289ed6bda
      JENKINS_TUNNEL:         devops-jenkins-agent.kubesphere-devops-system:50000
      JENKINS_AGENT_NAME:     base-vn524
      JENKINS_NAME:           base-vn524
      JENKINS_AGENT_WORKDIR:  /home/jenkins/agent
      JENKINS_URL:            http://devops-jenkins.kubesphere-devops-system:80/
    Mounts:
      /home/jenkins/agent from workspace-volume (rw)
      /root/.sonar/cache from volume-1 (rw)
      /var/run/docker.sock from volume-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dlg4f (ro)
  base:
    Container ID:  docker://6f38ccb87316928113d8afccb411e6c887177898c2d3201ed831ad1e92fb8adb
    Image:         kubesphere/builder-base:v3.2.0
    Image ID:      docker-pullable://kubesphere/builder-base@sha256:669f7b6be37def57565676c7271e213d03db356c65247e04469b7669d78a5d40
    Port:          <none>
    Host Port:     <none>
    Command:
      cat
    State:          Running
      Started:      Tue, 28 Dec 2021 10:12:54 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:                4
      ephemeral-storage:  10Gi
      memory:             8Gi
    Requests:
      cpu:                100m
      ephemeral-storage:  1Gi
      memory:             100Mi
    Environment:          <none>
    Mounts:
      /home/jenkins/agent from workspace-volume (rw)
      /root/.sonar/cache from volume-1 (rw)
      /var/run/docker.sock from volume-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dlg4f (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  volume-0:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:
  volume-1:
    Type:          HostPath (bare host directory volume)
    Path:          /var/data/jenkins_sonar_cache
    HostPathType:
  workspace-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-dlg4f:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/ci:NoSchedule op=Exists
                             node.kubernetes.io/ci:PreferNoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  29s   default-scheduler  Successfully assigned kubesphere-devops-worker/base-vn524 to k8snode5
  Normal  Pulled     28s   kubelet            Container image "jenkins/jnlp-slave:3.27-1" already present on machine
  Normal  Created    28s   kubelet            Created container jnlp
  Normal  Started    28s   kubelet            Started container jnlp
  Normal  Pulled     28s   kubelet            Container image "kubesphere/builder-base:v3.2.0" already present on machine
  Normal  Created    28s   kubelet            Created container base
  Normal  Started    28s   kubelet            Started container base
  Normal  Killing    24s   kubelet            Stopping container base

**Comment by LinuxSuRen** [comment]
I'm wondering if you could get the log of the pod. I didn't see any useful error message from the events.

**Comment by myokok** [comment]
> ```shell
> jnlp
> ```

![image](https://user-images.githubusercontent.com/44723876/147520772-3d2aa02c-92fa-4078-b3df-78ebdd284f99.png)

**Comment by myokok** [comment]
> I'm wondering if you could get the log of the pod. I didn't see any useful error message from the events.

the logs  about  pods   conatiners  jnlp  is above picture  。
pods里容器 jnlp里有错误信息，你看上图。或者我吧日志贴出来：




[root@k8smaster fone]# kubectl logs  -n kubesphere-devops-worker base-c5wmj    -c jnlp
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Warning: SECRET is defined twice in command-line arguments and the environment variable
Warning: AGENT_NAME is defined twice in command-line arguments and the environment variable
Dec 28, 2021 2:21:35 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: base-c5wmj
Dec 28, 2021 2:21:35 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Dec 28, 2021 2:21:35 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3.27
Dec 28, 2021 2:21:35 AM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
Both error and output logs will be printed to /home/jenkins/agent/remoting
Dec 28, 2021 2:21:36 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://devops-jenkins.kubesphere-devops-system:80/]
Dec 28, 2021 2:21:36 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to http://devops-jenkins.kubesphere-devops-system:80/tcpSlaveAgentListener/: Connection refused (Connection refused)
java.io.IOException: Failed to connect to http://devops-jenkins.kubesphere-devops-system:80/tcpSlaveAgentListener/: Connection refused (Connection refused)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:196)
        at hudson.remoting.Engine.innerRun(Engine.java:523)
        at hudson.remoting.Engine.run(Engine.java:474)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:193)
        ... 2 more

**Comment by myokok** [comment]
系统组件devops-jenkins-agent 的报错信息跟这个类似：


![image](https://user-images.githubusercontent.com/44723876/147523340-122c7d03-6c6e-4524-bd7f-3c0a61e01eba.png)

![image](https://user-images.githubusercontent.com/44723876/147523375-cc7b647e-a6aa-466d-b1d5-f082ebb1db42.png)

**Comment by JohnNiang** [comment]
Please try to debug your network issue.

```bash
# Enter any running container
kubectl -n kubesphere-system exec -it deployment/ks-installer -- sh
# Try to request the Jenkins service
curl -v http://devops-jenkins.kubesphere-devops-system:80
```

**Comment by myokok** [comment]
> ```java
> http://devops-jenkins.kubesphere-devops-system:80/tcpSlaveAgentListener/
> ```

[root@k8smaster fone]# kubectl -n kubesphere-system exec -it deployment/ks-installer -- sh
/kubesphere $ curl -v http://devops-jenkins.kubesphere-devops-system:80
*   Trying 10.233.5.247:80...
* Connected to devops-jenkins.kubesphere-devops-system (10.233.5.247) port 80 (#0)
> GET / HTTP/1.1
> Host: devops-jenkins.kubesphere-devops-system
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Tue, 28 Dec 2021 03:17:54 GMT
< X-Content-Type-Options: nosniff
< Set-Cookie: ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=; Path=/; Expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: JSESSIONID.a0730480=node01vzhigcwhya9w1umwfw91qa48k240081.node0; Path=/; HttpOnly
< Content-Type: text/html;charset=utf-8
< X-Hudson: 1.395
< X-Jenkins: 2.249.1
< X-Jenkins-Session: 792cdc2f
< X-Hudson-CLI-Port: 50000
< X-Jenkins-CLI-Port: 50000
< X-Jenkins-CLI2-Port: 50000
< X-You-Are-Authenticated-As: anonymous
< X-You-Are-In-Group-Disabled: JENKINS-39402: use -Dhudson.security.AccessDeniedException2.REPORT_GROUP_HEADERS=true or use /whoAmI to diagnose
< X-Required-Permission: hudson.model.Hudson.Read
< X-Permission-Implied-By: hudson.security.Permission.GenericRead
< X-Permission-Implied-By: hudson.model.Hudson.Administer
< Content-Length: 793
< Server: Jetty(9.4.30.v20200611)
<
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

* Connection #0 to host devops-jenkins.kubesphere-devops-system left intact
</body></html>                                                                                                                                                                                                                                                                                                            /kubesphere $
/kubesphere $

**Comment by myokok** [comment]
> Please try to debug your network issue.
> 
> ```shell
> # Enter any running container
> kubectl -n kubesphere-system exec -it deployment/ks-installer -- sh
> # Try to request the Jenkins service
> curl -v http://devops-jenkins.kubesphere-devops-system:80
> ```

在其他容器里，使用curl这个地址，应该是通的。只有流水线对应的pods里curl这个地址是不通的。我试过了。信息如上所示。
这个该怎么解决啊？

**Comment by JohnNiang** [comment]
> 流水线的类型为base的不行，nodejs的流水线是可以的。

/cc @kubesphere/sig-devops

**Comment by JohnNiang** [comment]
Please confirm that your node running DevOps agent (base) is running properly. For example, check the connection between your node and Jenkins service.

**Comment by myokok** [comment]
> Please confirm that your node running DevOps agent (base) is running properly. For example, check the connection between your node and Jenkins service.

我创建一个最简单的base类型的，都不行。

```
pipeline {
  agent {
    node {
      label 'base'
    }

  }
  stages {
    stage('clone code') {
      agent none
      steps {
        container('base') {
          echo '我是第一步'
        }

      }
    }

    stage('build & push') {
      agent none
      steps {
        container('base') {
          sh '我在第二步骤'
        }

      }
    }

  }
  environment {
    DOCKER_CREDENTIAL_ID = 'dockerhub'
    KUBECONFIG_CREDENTIAL_ID = 'kubeconfig'
    REGISTRY = 'docker.io'
    DOCKERHUB_NAMESPACE = 'shaowenchen'
    APP_NAME = 'devops-python-sample'
    SONAR_CREDENTIAL_ID = 'sonar-token'
  }
  parameters {
    string(name: 'BRANCH_NAME', defaultValue: 'master', description: '')
  }
}
```

**Comment by JohnNiang** [comment]
@myokok please remove `agent none` in your Jenkinsfile.

**Comment by myokok** [comment]
> 

还是不行。

```
pipeline {
  agent {
    node {
      label 'base'
    }

  }
  stages {
    stage('clone code') {
     
      steps {
        container('base') {
          echo '我是第一步'
        }

      }
    }

    stage('build & push') {
      steps {
        container('base') {
          echo '我在第二步骤'
        }

      }
    }

  }
  environment {
    DOCKER_CREDENTIAL_ID = 'dockerhub'
    KUBECONFIG_CREDENTIAL_ID = 'kubeconfig'
    REGISTRY = 'docker.io'
    DOCKERHUB_NAMESPACE = 'shaowenchen'
    APP_NAME = 'devops-python-sample'
    SONAR_CREDENTIAL_ID = 'sonar-token'
  }
  parameters {
    string(name: 'BRANCH_NAME', defaultValue: 'master', description: '')
  }
}
```

**Comment by myokok** [comment]
> @myokok please remove `agent none` in your Jenkinsfile.

不行。base和 go不行。  nodejs和maven可以。

**Comment by LinuxSuRen** [comment]
How many Kuberntes nodes do you have? Do the all Jenkins agent run on the same Kubernetes node?

**Comment by myokok** [comment]
> How many Kuberntes nodes do you have? Do the all Jenkins agent run on the same Kubernetes node?

我有1个master,5个worker节点。这个jenkins agent 运行在哪里，我得跟踪下。因为历史记录里失败的pods会很快被删除掉。

**Comment by myokok** [comment]
> How many Kuberntes nodes do you have? Do the all Jenkins agent run on the same Kubernetes node?

我排查了下，的确是在其中一个node上全部失败。在其他的node节点上是好的。


我是是使用kk安装的k8s+kubesphere，按理说，每个node都是一样的。但是在其中一个node上运行就是报那个错误。感觉相似网络不通。我该如何修复这个有问题的node呢？

**Comment by myokok** [comment]
我重启了这个有问题的node机器后，竟然好了。

**Comment by myokok** [comment]
感谢几位大神的指点，让我学会了排查问题的思路。谢谢。

**Comment by myokok** [comment]
排查问题的思路总结：

1、首先要看下对应的pods运行情况；k8s里所有的上层应用都运行在pods里；所以，遇到问题，首先要排查下pods的运行情况；
一般有几条命令：
(1) 查看命名空间里的pods的运行情况，以及pod所在的node机器；  
kubectl get pods -n xxxnamespace -o wide    

(2) 查看pod的日志 

kubectl  logs  -n xxxnamespace    xxxpodsname

(3) 查看pod的描述

kubectl describe pods  -n xxxnamespace    xxxpodsname

(4) 进入pod的容器内部查看运行情况
kubectl exec -it  xxxpodsname -n   xxxnamespace  /bin/sh  -c xxxcontainername
   

若命令用的不是非常熟练，可以在KubeSphere的 “平台管理---》集群管理---》应用负载---》容器组”里查看相应的pods;


2、pods里若有错误，看下错误信息；尝试排查问题；
3、因为k8s都是集群环境，pods分布在不同的工作节点里，可以在相似的pods里执行相同的命令对比信息，也可以在不同的pods执行相同的命令对比信息；
甚至是不同的node上的pod之间进行对比； 最终定位到某个Node机器上的某个Pod有问题。然后在排查问题。 
4、实在不行，就吧出现问题的节点的Node机器重启下，然后等个10-20分钟左右，再看下情况。尽量不要重启k8s集群的所有机器。
5、k8s里运行的东西比较慢，要有耐心等待几分钟，要确保pods都执行完毕了。 若pod有错误，也不要着急，k8s有自动故障转移和恢复功能，等pods自动愈合。
