### ISSUE TITLE
Kubesphere in version 3.2 uses external Jenkins (version 2.320). Which configuration file of kubesphere needs to be modified?

### ISSUE THREAD

**Issue by tengxunchao** [kubesphere/ks-devops#429]
Now I want to use kubesphere 3.2 connects external Jenkins. I follow the connection tutorial（ https://cloud.tencent.com/developer/article/1779145 ）Jenkins has been set up well. 

Now i need to configure the of kubesphere: do I need to modify kubesphere config or Devops config? Or do both configurations need to be modified?
Now kubesphere config is configured as follows: is my configuration correct?
Do i need to modify the  devopsserviceaddress and endpoint, enable?
Note: http://10.133.67.55:8080 This is the external Jenkins address

devops:
devopsServiceAddress: devops-apiserver. kubesphere-devops-system:9090
enable: false
endpoint: http://devops-apiserver.kubesphere-devops-system:9090
host: http://10.133.67.55:8080/
maxConnections: 100
password: 1133c93065ca0e6948c4455edec15b7525
username: liuhuining

thanks very much!

**Comment by tengxunchao** [comment]
My problem is that pipelines cannot be created in kubesphere.   The status of these pipelines is always < waiting >, and cannot be synchronized to external Jenkins:  
![image](https://user-images.githubusercontent.com/54707265/147800990-10f36702-c10b-4954-955a-37e4533a24fa.png)

I suspect that there is an error in the configuration of kubesphere config or Devops config. Please take a look. Should i need to configure both config?

**Comment by JohnNiang** [comment]
Hi @tengxunchao ,please be aware of ConfigMap `devops-config` introduced since KubeSphere 3.2.0.

**Comment by tengxunchao** [comment]
> Hi @tengxunchao ,please be aware of ConfigMap `devops-config` introduced since KubeSphere 3.2.0.

Do you have a link to the official documentation for the introduction of Devops-Config?

**Comment by LinuxSuRen** [comment]
> Do you have a link to the official documentation for the introduction of Devops-Config?


https://kubesphere.com.cn/docs/devops-user-guide/how-to-use/jenkins-setting/

**Comment by tengxunchao** [comment]
> > Do you have a link to the official documentation for the introduction of Devops-Config?
> 
> https://kubesphere.com.cn/docs/devops-user-guide/how-to-use/jenkins-setting/

Do I need to adjust the configuration of casC?

The link you sent didn't include an introduction to Devops-Config

**Comment by LinuxSuRen** [comment]
> Do you have a link to the official documentation for the introduction of Devops-Config?

Currently, we don't have a document about it. But it has the same structure as `kubesphere-config`, and it is part of that.

**Comment by tengxunchao** [comment]
> > Do you have a link to the official documentation for the introduction of Devops-Config?
> 
> Currently, we don't have a document about it. But it has the same structure as `kubesphere-config`, and it is part of that.


Connect external Jenkins, should  i need to change kubesphere-config?
Or  just   change Devops -config?

**Comment by tengxunchao** [comment]
> > Do you have a link to the official documentation for the introduction of Devops-Config?
> 
> Currently, we don't have a document about it. But it has the same structure as `kubesphere-config`, and it is part of that.

For version 3.2 kubesphere, is there a document explaining how to connect external Jenkins?
What configuration items need to be modified?
In version 3.1, all i  need to do is change kubesphere-config,
However, devops-config was introduced in 3.2. Now I don't know how to configure it. Please help me!

**Comment by tengxunchao** [comment]
> > Do you have a link to the official documentation for the introduction of Devops-Config?
> 
> Currently, we don't have a document about it. But it has the same structure as `kubesphere-config`, and it is part of that.

@LinuxSuRen  
The account and password configured in kubesphre config and Devops config in 3.2.1 can only be the account and password of admin. If other accounts are configured, they will also be converted to or regarded as the password of admin. Is that true? 
Can the password configured in Devops config only be the password of admin?

![image](https://user-images.githubusercontent.com/54707265/149068989-178319cd-03a3-40e0-9ead-7c7166add31d.png)

![image](https://user-images.githubusercontent.com/54707265/149069075-687ae55a-2ca5-428c-a41e-267773269bd3.png)

**Comment by LinuxSuRen** [comment]
The default behavior is to override the token. But you can change it with the following command flag:

`--override-jenkins-token=false`

https://github.com/kubesphere/ks-devops/blob/56aeda5423c825a41027792503d0cdee2bfe4ceb/cmd/tools/jwt/app/jwt_root.go#L40

**Comment by tengxunchao** [comment]
> The default behavior is to override the token. But you can change it with the following command flag:
> 
> `--override-jenkins-token=false`
> 
> https://github.com/kubesphere/ks-devops/blob/56aeda5423c825a41027792503d0cdee2bfe4ceb/cmd/tools/jwt/app/jwt_root.go#L40

Is the usage like this? Add configuration in yaml of Devops config?
![image](https://user-images.githubusercontent.com/54707265/149072142-7f433ae5-8c4f-4781-b8c3-e2968c4882ba.png)

**Comment by LinuxSuRen** [comment]
`jwt` is a tool command.

See also the following references:
* https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/50549eccada6a48ca4d7ffa8631546c75c9bd023/charts/ks-devops/templates/deployment-controller.yaml#L38
* https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/50549eccada6a48ca4d7ffa8631546c75c9bd023/charts/ks-devops/templates/deployment-apiserver.yaml#L49

**Comment by tengxunchao** [comment]
> `jwt` is a tool command.
> 
> See also the following references:
> 
> * https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/50549eccada6a48ca4d7ffa8631546c75c9bd023/charts/ks-devops/templates/deployment-controller.yaml#L38
> * https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/50549eccada6a48ca4d7ffa8631546c75c9bd023/charts/ks-devops/templates/deployment-apiserver.yaml#L49

thank you

**Comment by LinuxSuRen** [comment]
hi @tengxunchao , have you resolved this issue?

**Comment by tengxunchao** [comment]
> hi @tengxunchao , have you resolved this issue?

There is no "override-Jenkins-token" configuration in version 3.2.1, right?
What I need to do is recompile and package with the latest code( with "override-Jenkins-token" configuration), and then in deployment - apiserver yaml, deployment-controller. Configure "override-Jenkins-token" in yaml.  Am I right?

**Comment by LinuxSuRen** [comment]
You don't need to do it by yourself. We have nighly built images.

See also https://github.com/kubesphere/ks-devops/pkgs/container/devops-tools

**Comment by tengxunchao** [comment]
> You don't need to do it by yourself. We have nighly built images.
> 
> See also https://github.com/kubesphere/ks-devops/pkgs/container/devops-tools

with this image?    ghcr.io/kubesphere/devops-tools:nightly-20220112
![image](https://user-images.githubusercontent.com/54707265/149251677-a4fd9729-6bb7-49d9-994d-405a2576f100.png)

**Comment by tengxunchao** [comment]
I configured the image, restarted the Devops apiserver and Devops controller, and still couldn't synchronize with a non admin account.
the result is : 
![image](https://user-images.githubusercontent.com/54707265/149253444-8a1ab522-b83a-4a35-8d3d-a613af61b84c.png)


The configuration is as follows:
devops-controller configuration: 
![image](https://user-images.githubusercontent.com/54707265/149253004-0abb27ea-48b3-4f44-a431-3c651ed17bbc.png)

devops-apiserver configuration: 
![image](https://user-images.githubusercontent.com/54707265/149253386-d946fb9c-eeae-4266-ae1f-24d5929dca23.png)
