### ISSUE TITLE
Request to have a tutorial about how to compile this project

### ISSUE THREAD

**Issue by tengxunchao** [kubesphere/ks-devops#446]
Is there a concise compilation tutorial for this KS Devops project?

I need to compile devops-tools, devops-apiserver and devops-controller

**Comment by JohnNiang** [comment]
You could refer to Makefile:

https://github.com/kubesphere/ks-devops/blob/6cb96cf0debdc4fc2fcc8af60ab324e5bf6c2102/Makefile#L81-L83
https://github.com/kubesphere/ks-devops/blob/6cb96cf0debdc4fc2fcc8af60ab324e5bf6c2102/Makefile#L92-L94
https://github.com/kubesphere/ks-devops/blob/6cb96cf0debdc4fc2fcc8af60ab324e5bf6c2102/Makefile#L103-L105

**Comment by LinuxSuRen** [comment]
It would be great if we could have some video tutorial to explain it:

* How to setup a dev environment on Windows and MacOS
* How to compile this project
* How to build docker images
* How to debug this project
* others

**Comment by JohnNiang** [comment]
Hi @tengxunchao , has your problem been resolved?

**Comment by tengxunchao** [comment]
> Hi @tengxunchao , has your problem been resolved?

using dockfile  ok.

**Comment by LinuxSuRen** [comment]
IMO, we need this issue to be open until we have the tutorial.

/reopen

**Comment by tengxunchao** [comment]
good    We are looking forward to it

**Comment by LinuxSuRen** [comment]
Please feel free to check the GitHub action script.
/close
