### ISSUE TITLE
Request to create a new API to download artifacts from a PipelineRun

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#449]
## Background

Currently, [some APIs](https://github.com/kubesphere/ks-devops/blob/6cb96cf0debdc4fc2fcc8af60ab324e5bf6c2102/pkg/kapis/devops/v1alpha2/register.go#L714) is the proxy of the target Jenkins server.  For instance, the API to download artifacts of a PipelineRun.

Due to the unfriendly API format, we met some problems. See also https://github.com/kubesphere/ks-installer/pull/1890#issuecomment-1017193058

## Proposal

As I mentioned in the title.

```
GET /kapis/devops.kubesphere.io/v1alpha2/pipelineruns/demo-artifact-tt85n/artifacts?filePath=xxx.log
```

* pros
  * Easy to understand, easy to memory, shorter
  * Less to expose the backend tech
  * Have the same permission control pattern (`pipelineruns/artifacts`)
* cons
  * Extra work: both the backend and frontend

## How to

The possible steps are:

* Create an API for the artifacts download
* Use the new API from the frontend

## References
* https://github.com/jenkins-zh/jenkins-client
* https://github.com/kubesphere/ks-devops/issues/430
* https://github.com/kubesphere/ks-installer/pull/1890

/good-first-issue
/kind feature

**Comment by mzmuer** [comment]
I want to do this. 
* Provide an new API to download artifacts.
* internally using the `admin` role to request the Jenkins API, resolve the permission problem of customized role.

**Comment by LinuxSuRen** [comment]
It is good to hear that. Thanks for being interested in it.

/assign @mzmuer 

> internally using the admin role to request the Jenkins API, resolve the permission problem of customized role.

Actually, I prefer to use the corresponding token instead of the token from `admin`.

**Comment by LinuxSuRen** [comment]
hi @mzmuer any updates? Please let us know if you need any help.

**Comment by mzmuer** [comment]
@LinuxSuRen  Very sorry. I have some problems with my own win10 computer `K8s` environment.   It will be submitted after settlement, expected within this week.

**Comment by LinuxSuRen** [comment]
Actually, it's not necessary to install the whole KubeSphere. Instead, I only use k3d and Swagger UI to do the dev and test. I'm going to do a demo show at the SIG meeting this week. Before that, you can try it by yourself. And I'm glad to help you if there are any troubles about that.

**Comment by mzmuer** [comment]
@LinuxSuRen Thanks. Let me try k3d.

**Comment by LinuxSuRen** [comment]
fixed
/close
