### ISSUE TITLE
Request to remove S2I reconcilers from ks-devops

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#450]
As we all know, KubeSphere provides Source-to-Image (S2I) and Binary-to-Image (B2I) features to automate image building and pushing and application deployment. See [here](https://kubesphere.io/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/) for more.

But we already have an [S2I operator](https://github.com/kubesphere/s2ioperator) to take charge of this feature. Of course, I have tested it by disabling DevOps Controller, all functions of S2I and B2I work as normal.

Due to coupling with S2I, we can not remove S2I components now completely, such as S2I types and handlers. However, we could remove S2I reconcilers first or disable them by default.

/kind cleanup

**Comment by mangoGoForward** [comment]
Hi @JohnNiang , I found that we can disable S2I component in this file:

https://github.com/kubesphere/ks-devops/blob/d54a80ebd16c0df7b4698869babb17e41fec681e/cmd/controller/app/options/feature.go#L36-L37

But not found something about S2I reconcilers and somewhere to call:

https://github.com/kubesphere/ks-devops/blob/d54a80ebd16c0df7b4698869babb17e41fec681e/cmd/controller/app/controllers.go#L165-L177

Please correct me If I misunderstand, thanks.

**Comment by JohnNiang** [comment]
Hi @mangoGoForward , thank you for inspecting this issue. I have tried to remove the s2i components from ks-devops, but it's not easy to remove it completely. Please see https://github.com/kubesphere/ks-devops/blob/master/pkg/models/devops/s2ibinary_handler.go.

First thing we need to do is that expose APIs in [s2ioperator](https://github.com/kubesphere/s2ioperator) project, just like https://github.com/kubesphere/api. Then, we can refer the APIs into ks-devops and remove all s2i components but that s2ibinary handler.

**Comment by JohnNiang** [comment]
I agree with you that disabling s2i components is a good step. Can I assign this issue to you, @mangoGoForward : P

**Comment by mangoGoForward** [comment]
It's my pleasure, I will commit a PR to disable s2i components first, and remove it later.
