### ISSUE TITLE
Request to provide more functional Pipeline template

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#454]
At present, our Pipeline template includes two pre-defined templates and one user-defined template. The two pre-defined
templates are defined by the console and can hardly be changed. The user-defined template is equivalent to re-editing an
empty Pipeline template, completely losing the function of template - REUSE. Even though we now have the function of
copying Pipeline, but we still can't solve the problem of Pipeline template:

- The Pipeline template should be managed, like adding, modifying and deleting.
- The Pipeline template shall have flexible input parameters, and system can generate the corresponding Pipeline
  execution definition, Jenkinsfile or others, according to the input and template.

![image](https://user-images.githubusercontent.com/16865714/151110589-a6eaaf08-4177-4001-93ac-e9c02681f8b4.png)

I request to provide more functional Pipeline template, see #452 for more design detail.

/kind feature-request

**Comment by JohnNiang** [comment]
This issue has been fixed by
- https://github.com/kubesphere/ks-devops/pull/453
- https://github.com/kubesphere/ks-devops/pull/460
- https://github.com/kubesphere/ks-devops/pull/462
- https://github.com/kubesphere/ks-devops/pull/468
- https://github.com/kubesphere/ks-devops/pull/483
- https://github.com/kubesphere/console/issues/2946
- https://github.com/kubesphere/console/issues/2967

/close

**Comment by hengeek** [comment]
Bili video above about the go template and Node JS template where can be seen? Can you verify your own use?

**Comment by JohnNiang** [comment]
Hi @hengeek , thanks for your attention! Please see https://github.com/kubesphere-sigs/pipeline-templates for more.
