### ISSUE TITLE
Request to use skywalking-eyes to check LICENSE header

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#457]
I have noticed https://github.com/apache/skywalking-eyes recently which [Skywalking](https://github.com/apache/skywalking/blob/master/.licenserc.yaml) is using for checking LICENSE header. I'm wondering if we can use it to reduce uncertainty.

_Originally posted by @JohnNiang in https://github.com/kubesphere/ks-devops/pull/453#discussion_r792345790_

**Comment by mangoGoForward** [comment]
I'm glad to work on this.

/assign

**Comment by LinuxSuRen** [comment]
Thanks for being interested in this area.
