### ISSUE TITLE
Requires Java 17 Agent

### ISSUE THREAD

**Issue by sslyc** [kubesphere/ks-devops#465]
### What is version of KubeSphere DevOps has the issue?

v3.2.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

KubeKey

### Describe this feature

The devops-system does not support Java 17 so far. It is necessary to add this feature in the next version.

**Comment by JohnNiang** [comment]
Feel free to try this workaround:

```groovy
pipeline {
  agent {
    kubernetes {
      inheritFrom 'maven base'
      containerTemplate {
        name 'maven'
        image 'maven:3.8.4-openjdk-17'
      }
    }
  }
  stages {
    stage('Print JDK version') {
      steps {
        container('maven') {
          sh 'java -version'
        }
        container('base') {
          sh 'git --version'
        }
      }
    }
  }
}
```

**Comment by sslyc** [comment]
> Feel free to try this workaround:
> 
> ```groovy
> pipeline {
>   agent {
>     kubernetes {
>       inheritFrom 'maven base'
>       containerTemplate {
>         name 'maven'
>         image 'maven:3.8.4-openjdk-17'
>       }
>     }
>   }
>   stages {
>     stage('Print JDK version') {
>       steps {
>         container('maven') {
>           sh 'java -version'
>         }
>         container('base') {
>           sh 'git --version'
>         }
>       }
>     }
>   }
> }
> ```

Thx for replying. I've built a java-agent image locally, that already solved the problem. I'll try the way you mentioned as another realization. In my opinion, Java 17 as a LTS version,  the official image may be supplied. 

Thanks a lot.

**Comment by JohnNiang** [comment]
Hi @sslyc , please refer to 
- https://github.com/kubesphere/devops-agent/issues/26.

**Comment by sslyc** [comment]
> Hi @sslyc , please refer to
> 
> * [Discussion: There is no need to maintain so many docker images devops-agent#26](https://github.com/kubesphere/devops-agent/issues/26).

That's quite a nice idea. Hopes it coming true soon. I'll follow that issue. And this one shall be closed.
