### ISSUE TITLE
Add pipeline The added parameters do not take effect and the pipeline cannot run

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/ks-devops#485]
### What is version of KubeSphere DevOps has the issue?

3.2.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

Install using KK

### What happened?

Create a new pipeline and select a parameter such as string 111 and edit jenkinsfile online and the script will remain unrun when it is clicked and Jenkins does not trigger the task in the background and the parameter will come out when it is clicked
![image](https://user-images.githubusercontent.com/65068467/156726823-1e2840c9-eccb-4f97-a811-03d09911af82.png)
![image](https://user-images.githubusercontent.com/65068467/156726840-a10fec80-32e9-4b69-ad8b-4cc6b547cf35.png)
![image](https://user-images.githubusercontent.com/65068467/156726853-0505956b-6e12-411e-9712-ea7dcbecb1a4.png)

**Comment by JohnNiang** [comment]
I'm sure this problem will happen. And it's related with [the feature](https://github.com/kubesphere/ks-devops/pull/210) I developed before.
/assign
