### ISSUE TITLE
Request to support extenal Jenkins for ks-devops

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/ks-devops#493]
I think the built-in Jenkins is not very stable, it will down after changing the configuration. Is it possible to support extenal Jenkins for ks-devops?

**Comment by JohnNiang** [comment]
IMO, it's not possible to support external Jenkins conveniently. At least, you have to install plugins list in [here](https://github.com/kubesphere/ks-jenkins/blob/master/formula.yaml) first.

**Comment by LinuxSuRen** [comment]
hi @freemankevin glad to see you reaching out to us. Perhaps another issue might be able to help you. https://github.com/kubesphere/ks-devops/issues/161

Consider this issue is duplicated with that. I'm going to close this one.
/close
