### ISSUE TITLE
Request change to NewJenkinsClient

### ISSUE THREAD

**Issue by mzmuer** [kubesphere/ks-devops#496]
### What is version of KubeSphere DevOps has the issue?

master

### Describe this feature

I see the `jclient.NewJenkinsClient` function: 
https://github.com/kubesphere/ks-devops/blob/8bb14916fe928db9e8a2f9714390a81f9d485f80/pkg/client/devops/jclient/jenkins.go#L47

Can we replace this down here? 
 https://github.com/kubesphere/ks-devops/blob/8bb14916fe928db9e8a2f9714390a81f9d485f80/cmd/apiserver/app/options/options.go#L114

This gradually replaces the underlying call to a function via JenkinsCore

**Comment by JohnNiang** [comment]
I don't understand why we need to replace that function.

**Comment by mzmuer** [comment]
> I don't understand why we need to replace that function. Can you explain more detail?

I see that #437  introduced the NewJenkinsClient method. Is it a gradual replacement of the old Jenkins client?
but it is not used in `apiserver` , for what reason？

The `devops.PipelineOperator` interface needs to be modified in #479 . after the replacement, the new Jenkins client can be used to invoke the interface and gradually replace the old interface with the new Jenkins client

**Comment by JohnNiang** [comment]
I completely agree with you on replacement of `NewJenkinsClient`.

But IMO, the PR https://github.com/kubesphere/ks-devops/pull/479 should not be blocked by this issue. You can use Jenkins client in API handler directly.
