### ISSUE TITLE
Add a collection of DevOps related projects

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#50]
You can find the projects from the following filters:

* [s2i](https://github.com/kubesphere?q=s2i&type=&language=&sort=)
* [jenkins](https://github.com/kubesphere?q=jenkins&type=&language=&sort=)

## Suggestion

You can create a table to show all those projects. There're two necessary columns, name and description.

And, I prefer to put it into a new markdown file. Then, add a link in the readme file.

**Comment by AbdelouahabMbarki** [comment]
pr #172 opened as a fix for this issue
