### ISSUE TITLE
Request to design icons for Pipeline Templates

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#501]
### What is version of KubeSphere DevOps has the issue?

latest

### Describe this feature

Request to design icons for Pipeline Templates: Node.js, Golang, Maven.

![image](https://user-images.githubusercontent.com/16865714/158922051-aa9250eb-30df-49af-889c-3f7ba4982655.png)

### Additional information

/kind design

**Comment by XiaohuiSept** [comment]
<img width="1440" alt="流水线模板" src="https://user-images.githubusercontent.com/72596911/160101437-201151f0-05bd-4d48-b054-d13166ccfc3c.png">

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170233315-c087ddf0-bbbb-4d19-a708-c44da3a0c10c.png)

version used
nightly-20220524
