### ISSUE TITLE
The content of Run Records table in Devops is out of order with release 3.2.0

### ISSUE THREAD

**Issue by guonic** [kubesphere/ks-devops#511]
**Describe the Bug**
The content of Run Records table in Devops is out of order with release 3.2.0

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
CentOS 7.5 / 1 masters:  16cpu/64g; 3 nodes: 16cpu/64g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Go to some one DevOPS project
2. Click on one pipelines, enter run records table
3. The records in tables was out of order

**Expected behavior**
Records in table should be sort by ID descending.

**Comment by LinuxSuRen** [comment]
hi @guonic thanks for reaching out to us. This issue has been fixed in v3.2.1. I'm wondering if @JohnNiang could help us to find the related PRs or issues. Thanks for your time.

**Comment by JohnNiang** [comment]
Duplicated with
- https://github.com/kubesphere/ks-devops/issues/360

and fixed by
- https://github.com/kubesphere/ks-devops/pull/394
