### ISSUE TITLE
Load pipelines always timeout

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/ks-devops#512]
It happens every day, as long as you haven't visited the assembly line for a while
**System Info**
![image](https://user-images.githubusercontent.com/44914868/153168990-8d47ee0d-112b-4bd0-a1b9-862bd697122e.png)

![VVRXXBC%_5$P4 B@5()S7XG](https://user-images.githubusercontent.com/44914868/153167196-a9013564-941b-4b56-84e7-8df5dc7116c6.png)

**Comment by LinuxSuRen** [comment]
hi @yyt6200 , thanks for reaching out to us. I'm wondering if you could help us to do the troubleshooting work. For example, if you could provide the following information:

* if the deploy `devops-apiserver` keeps health
* if the deploy `devops-jenkins` keeps health
* if you can login Jenkins UI, and if it works well

/kind support

**Comment by LinuxSuRen** [comment]
I'm going to close this issue due to no response for a long time.
/close
