### ISSUE TITLE
Only the admin user can visit the pipeline page, other don't

### ISSUE THREAD

**Issue by 46797536** [kubesphere/ks-devops#514]
![image](https://user-images.githubusercontent.com/46241382/148022861-54391249-d68e-4376-a955-c33354c7e83e.png)
![image](https://user-images.githubusercontent.com/46241382/148023005-64ee6166-b120-43a3-a058-5b9c3efed26b.png)
![image](https://user-images.githubusercontent.com/46241382/148023028-fdb3f3e1-abe5-4d8e-bae9-206499188573.png)
![image](https://user-images.githubusercontent.com/46241382/148023046-5faff411-0a70-4a4b-96c0-3042dd6f6939.png)

**Comment by LinuxSuRen** [comment]
Please feel free to reopen this issue if @46797536 has more clues on this issue.
/close
