### ISSUE TITLE
Requires Node 14 Agent with docker environment

### ISSUE THREAD

**Issue by xfxmcy** [kubesphere/ks-devops#534]
### What is version of KubeSphere DevOps has the issue?

v3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### Describe this feature

//comand result  `docker: not found`

pipeline {
  agent {
    kubernetes {
      inheritFrom 'nodejs base'
      containerTemplate {
        name 'nodejs'
        image 'node:14.19.0'
      }
    }
  }
  stages {

    stage('Run npm install') {
      steps {
        container('nodejs') {
          sh 'npm -v'
          sh 'yarn -v'
          sh 'docker ps'
        }

      }
    }

  }
}

### Additional information

comand result  `docker: not found`, so the pipeline also need stage 'checkout(scm)'  'yarn build' docker build' 'docker push'

where is docs about `containerTemplate`,  I can't have it on https://v3-1.docs.kubesphere.io/zh/docs/devops-user-guide/how-to-use/choose-jenkins-agent/

**Comment by LinuxSuRen** [comment]
hi @xfxmcy , thanks for reaching out to us. We put some common tools (include docker) into the following image:

```
kubesphere/builder-base
```

/close
