### ISSUE TITLE
'Auto-Create Namespace' is not work

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#547]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.0

### What happened?

1、create Continuous Deployment and select 'Auto-Create Namespace'
2、After the CD is running, delete the created namespace

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/163503481-d8520036-e4cc-42d5-9e74-79875bdd57e8.png)

**Expected behavior**
The namespace is automatically created, and the CD works fine

/assign @LinuxSuRen 
/priority high

**Comment by LinuxSuRen** [comment]
hi @wenxin-01 , I cannot reproduce this issue. Please feel free to help to confirm it. Thanks.
