### ISSUE TITLE
‘Continuous Deployment’ page and 'Continuous Deployment Details' page add regular refresh 

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#548]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.1

### What happened?

![image](https://user-images.githubusercontent.com/68640256/163504220-da8af815-83ed-42a9-875c-a1e759e35aab.png)

![image](https://user-images.githubusercontent.com/68640256/163504163-e4c2df20-8707-44a2-8f7a-dfcc284601d9.png)

/assign @kubesphere/sig-console 
/priority low

**Comment by LinuxSuRen** [comment]
I'm not able to the corresponding PRs for this issue. But I'm pretty sure @harrisonliu5  has fixed it.
/close
