### ISSUE TITLE
Show full repository url

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#552]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.1

### What happened?

When using github to import the repository, the repository address is not displayed completely.
![image](https://user-images.githubusercontent.com/68640256/163763384-39080424-1848-4613-908b-65800fec05a1.png)

/priority medium
/assign @kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
This issue was fixed by https://github.com/kubesphere/console/pull/3122

**Comment by wenxin-01** [comment]
This issue was fixed in v3.3.0-alpha.1
