### ISSUE TITLE
The project of member cluster is error in Deployment location

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#558]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.1

### What happened?

![image](https://user-images.githubusercontent.com/68640256/164146015-4b521a8f-a3d9-4bf8-9f77-3313d9b1353b.png)

![image](https://user-images.githubusercontent.com/68640256/164146106-5b8abf4b-4d3e-4b86-a421-0a40b927a9b3.png)

/priority high
/assign @kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
hi @wenxin-01 , it looks like the front-end calls the wrong API. Right?

**Comment by wenxin-01** [comment]
> hi @wenxin-01 , it looks like the front-end calls the wrong API. Right?

Yes, looks like there is no cluster name when requesting project data

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-alpha.2`
![image](https://user-images.githubusercontent.com/68640256/166870056-1df392e3-b54c-4dc8-8686-b037cfe4c010.png)
