### ISSUE TITLE
[Continuous Deployment] cannot list project from the selected cluster

### ISSUE THREAD

**Issue by daixijun** [kubesphere/ks-devops#563]
**Describe the Bug**
"Deployment Location" cannot list project from the selected cluster, only list from the host cluster
<img width="894" alt="image" src="https://user-images.githubusercontent.com/3611220/164964056-3626ee29-b105-4b8a-96c3-00090278ecac.png">

**Versions Used**
KubeSphere: v3.3.0-alpha.1
Kubernetes: v1.20.11

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by LinuxSuRen** [comment]
We have fixed this issue. See https://github.com/kubesphere/console/pull/3168

Please feel free to test it with the image `kubespheredev/ks-console:master` if you want.

**Comment by daixijun** [comment]
> We have fixed this issue. See [kubesphere/console#3168](https://github.com/kubesphere/console/pull/3168)
> 
> Please feel free to test it with the image `kubespheredev/ks-console:master` if you want.

I replace the image to kubespheredev/ks-console:master, but i cannot see the "Continuous Deployments" and "Code Repositories" menus

<img width="323" alt="image" src="https://user-images.githubusercontent.com/3611220/165007535-8d23d2db-3323-4967-b7d9-77b8bd2a08eb.png">

**Comment by LinuxSuRen** [comment]
hi @daixijun , please feel free to try `v3.3.0-alpha.1` again. Thanks!

**Comment by daixijun** [comment]
> hi @daixijun , please feel free to try `v3.3.0-alpha.1` again. Thanks!

I try upgrade to `v3.3.0-alpha.2`, It works

**Comment by LinuxSuRen** [comment]
Given it works well now. I'm going to close this issue. Thanks for your time.
/close
