### ISSUE TITLE
Request  support http reuqest 

### ISSUE THREAD

**Issue by Feeeenng** [kubesphere/ks-devops#564]
### What is version of KubeSphere DevOps has the issue?

3.2.1

### Describe this feature

request support http reqeust

jenkinsfile:
```
pipeline {
  agent {
    node {
      label 'maven'
    }

  }
  stages {
    stage('stage-uyzy1') {
      agent none
      steps {
        container('maven') {
            httpRequest "http://baidu.com"
        }

      }
    }

  }
}

```

logs
![image](https://user-images.githubusercontent.com/14897634/165242368-b59a0f2f-fe46-4006-a4b5-42027432343d.png)

plugin : https://plugins.jenkins.io/http_request

**Comment by LinuxSuRen** [comment]
Directly using the Jenkins plugin to send an HTTP request might not be a good practice. In my opinion, it would be better to use a more common command to do it, for example: `curl`.

In case it is difficult to member the flags of `curl`, we can offer a UI step to users.

**Comment by LinuxSuRen** [comment]
see also https://github.com/kubesphere/ks-devops/issues/602
/close
