### ISSUE TITLE
When importing the gitlab repository, you need to add the suffix ".git" to the repository address

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#567]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.2

### What happened?

When importing the gitlab repository, the url is displayed as `https://gitlab.com/wxsunshine/open-podcasts`, but get error in CD detail.
![image](https://user-images.githubusercontent.com/68640256/165429855-cb3b5fb2-b79e-431c-9074-d1b2779de060.png)

When modify url to `https://gitlab.com/wxsunshine/open-podcasts.git`,  get success.
![image](https://user-images.githubusercontent.com/68640256/165431239-7b3a5188-d6ee-4262-a7ef-6f81a7f5ef61.png)

/priority medium
/assign @kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
Gitlab requires the suffix `.git`. See the following test output:
```shell
[root@node1 test]# /usr/bin/git clone https://gitlab.com/linuxsuren/test
Cloning into 'test'...
error: RPC failed; result=22, HTTP code = 422
fatal: The remote end hung up unexpectedly
[root@node1 test]# /usr/bin/git clone https://gitlab.com/linuxsuren/test.git
Cloning into 'test'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8 (delta 2), reused 8 (delta 2), pack-reused 0
Unpacking objects: 100% (8/8), done.
```
/assign
