### ISSUE TITLE
devops Pipeline  Could not resolve host: gitee.com

### ISSUE THREAD

**Issue by hi163hello** [kubesphere/ks-devops#579]
Jenkinsfile:
sh 'git push http://$GIT_USERNAME:$GIT_PASSWORD@gitee.com/$GITEE_ACCOUNT/gulimall.git --tags --ipv4'

error log:
+ git push http://****:****@gitee.com/****/gulimall.git --tags --ipv4
fatal: unable to access 'http://****:****@gitee.com/****/gulimall.git/': Could not resolve host: gitee.com; Name or service not known
script returned exit code 128

/etc/hosts
180.97.125.228 gitee.com

ping gitee.com
PING 180.97.125.228 (180.97.125.228) 56(84) bytes of data.
64 bytes from 180.97.125.228: icmp_seq=1 ttl=50 time=12.4 ms
64 bytes from 180.97.125.228: icmp_seq=2 ttl=50 time=11.3 ms

**Comment by LinuxSuRen** [comment]
hi @hi163hello , is that possible to provide a simple way to reproduce it? The error output looks pretty clear. And we didn't offer any particular setting against gitee.com.

/kind support

**Comment by LinuxSuRen** [comment]
I tested it in a couple of minutes on v3.3.0-alaph. It works well.

![image](https://user-images.githubusercontent.com/1450685/167074513-cd060e1f-0298-4d00-9023-c8d8ca8c7a95.png)

**Comment by hi163hello** [comment]
Thank you for your answers! 
Is it possible that there is a problem with my DNS configuration?
How to configure DNS in kubesphere?


Operating system information:
Virtual machine, centos7 5,4C/8G

Kubernetes version information:
v17. 3 multi node.

When the container is running:
Use docker / containerd, version 20.10.3

Kubesphere version information:
v2.1.1

**Comment by LinuxSuRen** [comment]
It looks like a common network issue on the Kubernetes. For the DevOps, there are no particular DNS settings. Maybe you can try to find which DSN system are you using? For example, CoreDNS? Then find any useful information via Google.

**Comment by hi163hello** [comment]
I use coredns. How to configure coredns in kubesphere?

**Comment by LinuxSuRen** [comment]
I'm going to close this issue due to no response for a long time.
/close
