### ISSUE TITLE
How to disable CI plugins when devops enabled ?

### ISSUE THREAD

**Issue by codering** [kubesphere/ks-devops#583]
### What is version of KubeSphere DevOps has the issue?

3.3.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

v1.22.7+k3s1

### Describe this feature

I want to only use CD(argocd) without CI when enable devops

**Comment by LinuxSuRen** [comment]
Currently, you can disable the CI backend by providing some command flags:

See also
* https://github.com/kubesphere/ks-devops/blob/a73c8c677b3cc40e13b6922226a36a1aa447b81a/cmd/controller/app/controllers.go#L133
* https://github.com/kubesphere/ks-devops/blob/master/docs/addon.md

It would be good to have this feature in the next version.

**Comment by codering** [comment]
I am not familiar with go language，but I find the devops helm chart config 'jenkins.enabled'，default value is 'true'，is there an easy way to change it to false before I enable devops ？

**Comment by LinuxSuRen** [comment]
One solution is that we can improve it in the `ks-installer`. See also the example [here](https://github.com/kubesphere/ks-installer/blob/0e8a285e4b2e60cae6c1052b4b2208b981147a3e/roles/ks-devops/tasks/main.yaml#L184).

**Comment by codering** [comment]
yes，currently I can try to modify the ks-installer task config and rebuild the installer image？ 

I hope ks-console can surport it.

**Comment by LinuxSuRen** [comment]
This is a good feature request. But I'm afraid that I cannot promise to do it right now. For now, the most important work is to make sure the next version is stable. Please feel free to help with it if you're interested in it.

**Comment by LinuxSuRen** [comment]
Considering this is a question issue. And I already filed a detailed issue for the potential feature request. I'm going to close this issue. And please feel free to follow the new issue. See also https://github.com/kubesphere/ks-devops/issues/697
/close
