### ISSUE TITLE
devops pipeline run exception

### ISSUE THREAD

**Issue by zj452008181** [kubesphere/ks-devops#588]
**Describe the Bug**
Q1、devops pipeline still running but jenkins task already completed,and can't stop in control plane, when i run a new pipeline task,it always waiting.only delete the pipelinerun crd resource task will start
Q2、start a pipeline task，there come out  two sample task and i also can find two different  pipelinerun crd  name with same ‘’devops.kubesphere.io/jenkins-pipelinerun-id‘’

**Versions Used**
KubeSphere: 3.2.1
Kubernetes:v1.20.4

**Expected behavior**

Q2:
![image](https://user-images.githubusercontent.com/26154743/167794152-e2b09caa-5e04-4632-b782-7ea8a555d9f9.png)

**Comment by LinuxSuRen** [comment]
hi @zj452008181 , glad to see you here. This is a known issue of v3.2.1. It was fixed. Please feel free to verify it in the v3.3.0-alpha.

/kind support

**Comment by zj452008181** [comment]
> 
thanks for your reply，one more question：i configured ldap in my host cluster，and i can use ldap user to start host cluster's pipeline，but can't run member cluster's pipeline。i check the kubesphere-config:devops:password in two cluster,they have same value.only found some error in ks-controller-manager  log,please give some suggest

member's ks-controller-manager:
`E0509 17:19:09.312632 1 user_controller.go:347] GET http://devops-jenkins.kubesphere-devops-system.svc/role-strategy/strategy/getRole/?roleName=admin&type=globalRoles: 401 <html>

<head>

<meta http-equiv=“Content-Type” content=“text/html;charset=utf-8”/>

<title>Error 401 Invalid password/token for user: admin</title>

</head>

<body><h2>HTTP ERROR 401 Invalid password/token for user: admin</h2>

<table>

<tr><th>URI:</th><td>/role-strategy/strategy/getRole/</td></tr>

<tr><th>STATUS:</th><td>401</td></tr>

<tr><th>MESSAGE:</th><td>Invalid password/token for user: admin</td></tr>

<tr><th>SERVLET:</th><td>Stapler</td></tr>`

**Comment by LinuxSuRen** [comment]
There're two potential issues and solutions that you can try:
* The account of LDAP was not synced successfully
  * Possible solution: Reset the password of your account
* The JWT token was wrong
  * Possible solution: Restart the deployment of `devops-apiserver` and `devops-controller`

**Comment by zj452008181** [comment]
@LinuxSuRen found out！The JWT token in devops-config was different between two cluster，i copy host‘s  JWT token to member,and restart devops-apiserver and devops-controller,first problem dont resolve，but ks-controller-manager dont print any error，so i just try log out and use ldap user login，problem resolved.thanks a lot

**Comment by LinuxSuRen** [comment]
I still feel confused about the JWT issues. Please let me know if you found any pattern that can help us to fix it for good.

**Comment by zj452008181** [comment]
> 

maybe it changed when i upgrade the cluster,i don't sure what happend,but i tried restart the ks-installer to repair this issue，however it dont work.there has no modify time shows in configmap ui，maybe it's useful when i check the configmap.

**Comment by LinuxSuRen** [comment]
Actually, the secret randomly issue was fixed by https://github.com/kubesphere/ks-devops/pull/591

**Comment by LinuxSuRen** [comment]
I'm going to close this issue due to it was fixed in v3.3.0. Please feel free to open this issue again if you believe it still exists in v3.3.0.
/close
