### ISSUE TITLE
Enterprise Space Administrator Sync Continuous Deployment Fails

### ISSUE THREAD

**Issue by jioce** [kubesphere/ks-devops#595]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-rc.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

v1.21.5

### What happened?

1、There is an account cc, which has the workspace manager permission of the platform, the viewer permission of the enterprise space and the viewer permission of the devops project dev
![image](https://user-images.githubusercontent.com/88183150/169940857-e4685a8b-0875-48bc-b137-3146b99ee5e2.png)

![image](https://user-images.githubusercontent.com/88183150/169940893-93363b50-7fdc-4f69-b3f3-0cb46844d8f9.png)

![image](https://user-images.githubusercontent.com/88183150/169940926-0b5953d4-187c-4497-83da-3d7897f04903.png)

2、Enter the devops project, there is an existing code repository, create a continuous deployment tt, and select automatic synchronization
![image](https://user-images.githubusercontent.com/88183150/169940812-0e3ec8cc-14ca-4ba9-946e-b34fa6c1f183.png)

3、After the creation is successful, click More Actions, Synchronize, select Automatically create a project, click Confirm, and the page prompts an error
![image](https://user-images.githubusercontent.com/88183150/169940343-9c83dc9c-29cf-45dd-b4d9-464306ad4ae4.png)

/priority high

**Comment by jioce** [comment]
issue is fixed

version used 
surenpi/ks-installer:add-gitops-to-global-dev-e9bb1105

**Comment by LinuxSuRen** [comment]
hi @jioce , thanks for helping to verify it. But the PR https://github.com/kubesphere/ks-installer/pull/1997 is still there. I prefer to close this issue until the corresponding issue closed.
