### ISSUE TITLE
Remove the ID column of the DevOps project list

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/ks-devops#614]
The ID column seems not useful for users and should be removed.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/76198553/169804979-4e76262f-5629-4d4c-9bae-a2425f5fddc0.png">

/assign @LinuxSuRen @harrisonliu5

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20220605`

![image](https://user-images.githubusercontent.com/68640256/172128848-b5b23e68-7207-479d-8534-9a120c96fa6d.png)
