### ISSUE TITLE
Request to support cascade deletion of the CD resource

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#621]
**What would you like to be added**:
Add an option to let users choose if they want to delete the corresponding resources as well.

![image](https://user-images.githubusercontent.com/1450685/163502054-4149c004-0f33-4e87-aa81-5f0aefef7f47.png)

## API
The deletion API is:

```
DELETE v1alpha1/namespaces/{namespace}/applications/{application}?cascade=true
```
The API will delete resources as well if the query variable `cascade` is true.

/area devops
/priority high
**Why is this needed**:
Currently, it cannot delete the corresponding resources when users want to delete a CD. Let's assume, there is a deployment in a git repository. The GitOps feature can create the deploy. When users want to delete it, sometimes they might want to delete the resources as well.

**Comment by wenxin-01** [comment]
Issue fixed in `V3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172130130-90e0d6e5-15e6-4367-b4d1-c31077421e25.png)
