### ISSUE TITLE
Suggest to given a tip when the Bitbucket repository list is empty on the DevOps Pipeline page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#629]
**What would you like to be added**:

Suggest to given a tip when the Bitbucket repository list is empty on the DevOps Pipeline page.

![image](https://user-images.githubusercontent.com/1450685/111933289-185ae800-8afa-11eb-9696-d242f2796e15.png)

/area devops
/priority low
/good-first-issue

**Why is this needed**:
A blank page might make people feel that there's something wrong there.

**Comment by chilianyi** [comment]
<img width="995" alt="截屏2023-07-31 10 51 48" src="https://github.com/kubesphere/ks-devops/assets/5917832/cacfb5b2-dac9-46e0-971f-68cea8038788">

Already fixed
