### ISSUE TITLE
Suggestion of menu item on the DevOps project page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#631]
**What would you like to be added**:

As you can see from the following screenshot. IMO, the prefix `DevOps Project` is duplicated with the parent menu. And the most important reason is that no way to mix different projects here. I believe that `Credential` is pretty clear.

![image](https://user-images.githubusercontent.com/1450685/136897615-63d3d55f-b339-4b5e-b6cd-f7ff944bc26f.png)

Below screenshot comes from v3.1.1
![image](https://user-images.githubusercontent.com/1450685/136897779-dd0ad917-163f-451c-9983-b967aec77327.png)

**Why is this needed**:

/area devops
/cc @Felixnoo

**Comment by chilianyi** [comment]
<img width="1436" alt="截屏2023-07-28 19 12 12" src="https://github.com/kubesphere/ks-devops/assets/5917832/eed4b90a-e440-4afb-9d09-4ee779acbfe1">

Already supported
