### ISSUE TITLE
Add verification for devops project name input 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/ks-devops#635]
**Describe the bug**
suggestion: Add verification for name input 
![image](https://user-images.githubusercontent.com/36271543/144190057-f1a7fe60-b6fb-4699-b229-5f628570905b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172132156-c49d54b9-37cf-40b1-967f-4f83e688c934.png)
