### ISSUE TITLE
Failed to upload the binary file (in progress 99%) on the S2I page

### ISSUE THREAD

**Issue by sxxpqp** [kubesphere/ks-devops#648]
**Describe the Bug**
构建镜像器上传99%失败，就卡弹出失败，报500错误

**Versions Used**
KubeSphere:v3.2.0

**Environment**
CentOS 7.9 / 1 masters:  24cpu/128g; 2 nodes: 24cpu/128g

**How To Reproduce**
![image](https://user-images.githubusercontent.com/47712570/171528551-8ef58aff-5344-4361-b7e2-2c5dd09309b8.png)

![image](https://user-images.githubusercontent.com/47712570/171528741-a73fd636-4d6f-4b8c-bb44-8dcaa643f54f.png)

![image](https://user-images.githubusercontent.com/47712570/171528983-a9fccff2-7010-424a-9e43-d29e328b79cc.png)

**Expected behavior**
没有通过ingress，直接使用的nodeport的端口访问的。

**Comment by sxxpqp** [comment]
![image](https://user-images.githubusercontent.com/47712570/171999048-f5e8e958-19e6-48d9-a3e5-a26d52c707ad.png)
ks-apisesrver logs

**Comment by sxxpqp** [comment]
> 
https://user-images.githubusercontent.com/47712570/171999048-f5e8e958-19e6-48d9-a3e5-a26d52c707ad.png

**Comment by LinuxSuRen** [comment]
This feature belongs to the DevOps project. The corresponding code lines are [here](https://github.com/kubesphere/ks-devops/blob/a4c1599d385cfc981bebd0c29fce06b72ae71182/pkg/kapis/devops/v1alpha2/s2ibinary.go#L36).

So, we need the log output of `devops-apiserver` instead of `ks-apiserver`.

**Comment by sxxpqp** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/ks-devops"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/ks-devops] Failed to upload the binary file (in progress 99%) on the S2I page (Issue #648)





 
This feature belongs to the DevOps project. The corresponding code lines are here.
 
So, we need the log output of devops-apiserver instead of ks-apiserver.

**Comment by sxxpqp** [comment]
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "kubesphere/ks-devops"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/ks-devops] Failed to upload the binary file (in progress 99%) on the S2I page (Issue #648)





 
This feature belongs to the DevOps project. The corresponding code lines are here.
 
So, we need the log output of devops-apiserver instead of ks-apiserver.

**Comment by sxxpqp** [comment]
![image](https://user-images.githubusercontent.com/47712570/172748658-fbb4b2c4-169e-460b-99f2-83ed20e76cc2.png)
![image](https://user-images.githubusercontent.com/47712570/172748703-4d16068c-175a-4802-b47e-277f09c40766.png)

**Comment by LinuxSuRen** [comment]
As you can see from the log output. This problem was caused by missing bucket `s2i-binaries` in the minio. You could create it if you didn't find it.

**Comment by sxxpqp** [comment]
Creating s2i-binaries is like ok

**Comment by LinuxSuRen** [comment]
It looks like you have resolved this problem. I'm going to close this issue.
/close
