### ISSUE TITLE
Pipelining and continuous deployment support grayscale releases [blue-green, canary]

### ISSUE THREAD

**Issue by smallersoup** [kubesphere/ks-devops#678]
### What is version of KubeSphere DevOps has the issue?

v3.2.1、v3.3.0-rc、All versions

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

install by kubeasz tool

### Describe this feature

After the image is built, switch from DevOps project to project, open the grayscale release page, and enter the image name to create the blue-green deployment and canary release tasks. I don't think it's more convenient to use the grayscale publishing process this way.

Planning to integrate blue-green deployments and canary releases into continuous deployment to string together the entire release process? That is, every time the pipeline is executed, when the release step is reached, the blue-green or canary release can be selected.

**Comment by LinuxSuRen** [comment]
this was duplicated with https://github.com/kubesphere/ks-devops/issues/682

Considering these two issues both come from you. And #682 has more details. I'm going to close this one.
/close
