### ISSUE TITLE
[FluxCD Integration] Add FluxCD GitRepository Management

### ISSUE THREAD

**Issue by chengleqi** [kubesphere/ks-devops#679]
/kind feature

**Comment by LinuxSuRen** [comment]
hi @chengleqi glad to see you here.


We already have the basic function of Git Repository Management. See also

![image](https://user-images.githubusercontent.com/1450685/174576667-4ace1713-e129-4455-be6d-d2461192ebfb.png)

Please feel free to provide the details that you hope to improve.

**Comment by LinuxSuRen** [comment]
Sorry about closing this issue due I pressed the wrong button.

**Comment by LinuxSuRen** [comment]
hi @chengleqi , thanks for the explanation. That's much clear now.
