### ISSUE TITLE
[Front-end] avoid using API tojson and tojenkinsfile

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#714]

**Comment by LinuxSuRen** [comment]
For this issue, the front-end needs to abandon two APIs:

* `v1alpha2/tojenkinsfile`
* `v1alpha2/tojson`

then you could update the Jenkinsfile with JSON or raw format with the following API. Please feel free to read more details about this API from [the swagger](https://github.com/kubesphere/ks-devops/blob/master/docs/swagger.md).

* `/devops/{devops}/pipelines/{pipeline}/jenkinsfile`

you could get the JSON format of the Jenkinsfile from annotation with key `pipeline.devops.kubesphere.io/jenkinsfile`

**Comment by chilianyi** [comment]
<img width="1440" alt="截屏2023-01-29 23 16 07" src="https://user-images.githubusercontent.com/5917832/215382599-fea1d545-d1c6-4140-b5f8-66b91922dc6b.png">
<img width="1439" alt="截屏2023-01-30 11 40 50" src="https://user-images.githubusercontent.com/5917832/215382766-b4db2dca-04bb-47ad-9608-6720f3dbfc5a.png">

There are still tojson api call，need to remove.

**Comment by chilianyi** [comment]
add jenkinsfile.validate to annotation
valid values are successful and failure

if failure, show like this:
<img width="1056" alt="截屏2023-01-30 14 53 37" src="https://user-images.githubusercontent.com/5917832/217728995-2be98b1a-369a-4cb1-a7e2-36fa5759c55e.png">

if there is no jenkinsfile.validate, due as successful.
