### ISSUE TITLE
Documentation in the Pipelines page 404 not found

### ISSUE THREAD

**Issue by zhouqiu0103** [kubesphere/ks-devops#721]
### What is version of KubeSphere DevOps has the issue?

3.3.0

### Describe this feature

The documentation in the Pipelines page(red marker) is not found.
![111](https://user-images.githubusercontent.com/108912268/178208619-acb09825-ccbb-41f2-8f83-e888a7f3fd1f.png)
![112](https://user-images.githubusercontent.com/108912268/178208868-a20f7254-e739-43ca-a723-520de3985220.png)
The documentation address is https://kubesphere.io/docs/v3.3/devops-user-guide/how-to-use/pipeline-settings/

**Comment by LinuxSuRen** [comment]
Considering this is not a feature request. I'm going to change the label.

/kind-remove feature
/kind bug
/area console

**Comment by PrajwalBorkar** [comment]
I think this should be the link - https://kubesphere.io/docs/v3.3/devops-user-guide/how-to-use/pipelines/pipeline-settings/
But I'm not able to find the Learn more tab.

**Comment by LinuxSuRen** [comment]
> I think this should be the link - https://kubesphere.io/docs/v3.3/devops-user-guide/how-to-use/pipelines/pipeline-settings/ But I'm not able to find the Learn more tab.

You can find the front-end source code from https://github.com/kubesphere/console

**Comment by harrisonliu5** [comment]
you can find the link address from https://github.com/kubesphere/console/blob/master/server/config.yaml#L620

**Comment by PrajwalBorkar** [comment]
> you can find the link address from https://github.com/kubesphere/console/blob/master/server/config.yaml#L620

So I have to make changes in this file and make PR in console repo?

**Comment by LinuxSuRen** [comment]
> So I have to make changes in this file and make PR in console repo?

Yes.

**Comment by LinuxSuRen** [comment]
I'm going to close this issue due to it's fixed. Thanks for your time. @PrajwalBorkar 
/close
