### ISSUE TITLE
Pipeline build records are missing when running the pipeline continuously.

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/ks-devops#737]
### What is version of KubeSphere DevOps has the issue?

v3.3.0

### What happened?

I have 500 pipelines, when I run one every 3 seconds, it reaches the 130th, the build records of the pipelines that ran successfully before disappeared.

logs of devops-jenkins.
![image](https://user-images.githubusercontent.com/68640256/178942120-1bedfc80-5735-4328-9508-367e64b698d2.png)
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/68640256/178942525-18f4dc96-50e4-4f7f-997a-1d3f11b70e97.png">
![image](https://user-images.githubusercontent.com/68640256/178942249-4826fcec-4f80-4e50-aa69-9c06b2ac794c.png)
![image](https://user-images.githubusercontent.com/68640256/178942282-bec753a6-7d28-451c-ae97-efe37fc6659d.png)

**Comment by chilianyi** [comment]
`the build records of the pipelines that ran successfully before disappeared`

You mean the pipelinerun is successfully, and then disappeared?

**Comment by wenxin-01** [comment]
> `the build records of the pipelines that ran successfully before disappeared`
> 
> You mean the pipelinerun is successfully, and then disappeared?

Yes

**Comment by chilianyi** [comment]
# kubectl get cronjob -n kubesphere-devops-system
NAME     SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
devops   0/30 * * * *   False     0        27m             13d

<img width="1103" alt="截屏2022-12-26 11 27 48" src="https://user-images.githubusercontent.com/5917832/209497496-a1d33e3d-d985-44c6-8c9e-b52fa50b7029.png">

Maybe deleted by the cronjob.

We will consider to allow users to set the config in devops project, @yudong2015 already begin the design and upgrade.

**Comment by TIANYUANXIXUE** [comment]
> # kubectl get cronjob -n kubesphere-devops-system
> NAME SCHEDULE SUSPEND ACTIVE LAST SCHEDULE AGE devops 0/30 * * * * False 0 27m 13d
> 
> <img alt="截屏2022-12-26 11 27 48" width="1103" src="https://user-images.githubusercontent.com/5917832/209497496-a1d33e3d-d985-44c6-8c9e-b52fa50b7029.png">
> 
> Maybe deleted by the cronjob.
> 
> We will consider to allow users to set the config in devops project, @yudong2015 already begin the design and upgrade.

我这里出现了，在没有到达流水线配置的超时时间和数量上限的情况下，已经构建成功的记录消失的情况，是否与这个任务有关呢？

**Comment by chilianyi** [comment]
https://github.com/kubesphere/ks-devops/issues/982

**Comment by zjpjly** [comment]
don't select "Delete outdated build records",the records will not be deleted




![Image](https://github.com/kubesphere/ks-devops/assets/18654693/627d8097-5812-46bd-af5a-355360273aee)



![Image](https://github.com/kubesphere/ks-devops/assets/18654693/0a1bd36b-de3a-4b3f-8d7f-414cb5994d9a)
