### ISSUE TITLE
Consider Update the version of controller-runtime

### ISSUE THREAD

**Issue by chengleqi** [kubesphere/ks-devops#751]
I encountered a strange problem when I wrote unit test due to the version of controller-runtime.

I use code like this `r.Client.List(..., &unstructured.UnstructuredList{}, ...)`, It run correctly when the Client is RestClient, but It'll run into error when the client is fake client in the unit test scenario.

I found the root cause is [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/702), but the [PR which fix this issue](https://github.com/kubernetes-sigs/controller-runtime/pull/1521) was merged only in the 0.9.x version of controller-runtime, I tried to update the controller-runtime v0.6.3 => v0.9.7 but It caused too many changes.

So I Added code manually like this in the unit test:

```golang
schema.AddKnownTypeWithName(apischema.GroupVersionKind{
        Group:   "helm.toolkit.fluxcd.io",
        Version: "v2beta1",
        Kind:    "HelmReleaseList",
}, &unstructured.UnstructuredList{})
```

And the fluxcd project actually provide the [module](github.com/fluxcd/helm-controller/api) which include the [HelmRelease type](https://github.com/fluxcd/helm-controller/blob/a2147639031eb1362360b52c6f596c066270ecc4/api/v2beta1/helmrelease_types.go#L923) for convenience. But It also need higher version of controller-runtime.

Is it possible to update the controller-runtime version when it arrive version 1.0 or LTS ?

**Comment by LinuxSuRen** [comment]
We'd better upgrade `controller-runtime` at some point. We already talked about this in https://github.com/kubesphere/ks-devops/issues/353

But as you mentioned, it requires a lot of work on this. I'd like to do it once I got enough time. But please feel free to help on this if there is anyone willing to do it.
