### ISSUE TITLE
Request to support Pipeline log auto scroll

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#752]
As you can see from the following screen. Users need to scroll the log output manually. This is a very bad experience.

![image](https://user-images.githubusercontent.com/1450685/180916645-be20b379-ef0d-459c-a7c6-bc5a88c241be.png)

/area devops
/priority high

**Comment by wenxinll** [comment]
Issue fixed in `v3.5.0-beta.1`

![image](https://github.com/kubesphere/issues/assets/68640256/c2b90360-483e-4c55-b519-a76eec90667f)
