### ISSUE TITLE
DevOps features in 3.3.0 is invisible while use multi-cluster manage member cluster's DevOps project

### ISSUE THREAD

**Issue by imshenyz** [kubesphere/ks-devops#755]
**Describe the Bug**

DevOps features in 3.3.0 is invisible while use multi-cluster manage member cluster's DevOps project.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/1438697/180902086-a1e64cba-c7dc-487e-8c9c-c140d5c478f6.png">

**Versions Used**
KubeSphere: 3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

CentOS 7.9 / 3 masters:  2cpu/4g; 3 nodes: 8cpu/32g

**How To Reproduce**
1. Go to member cluster's workspace
2. Go to DevOps project
3. See left menu

**Expected behavior**

DevOps features in 3.3.0

**Comment by imshenyz** [comment]
> There are some troubleshooting tips below:
> 
> * Make sure you enabled the DevOps feature in your member clusters
> * Make sure all the image of the console is: `kubesphere/ks-console:v3.3.0`
> 
> /kind support

@LinuxSuRen Yes, i was enabled DevOps feature in both host and member clusters and all the image of the console is: `kubesphere/ks-console:v3.3.0`.
In fact, the left menu is visible in host cluster's DevOps projects and also visible in member cluster's DevOps projects while direct access member cluster. But invisible while access member cluster's DevOps projects from host cluster.

**Comment by socrates-hlapolosa** [comment]
Also have exactly the same issue, using the same versions.

**Comment by LinuxSuRen** [comment]
hi @imshenyz , thanks for your details. I'm going to check it later.

**Comment by imshenyz** [comment]
@LinuxSuRen  Ok, i see, thanks for reply.
I think the GitOps feature in both host and member clusters is a good idea.
In my usage scenarios, i created test-workspace in test member clusters, for convenience i also want to manage projects and DevOps projects in same workspace.
On the other hand, I think the main function of host cluster is to manage multiple clusters, and we should avoid running too many applications on it, is it?

**Comment by LinuxSuRen** [comment]
> On the other hand, I think the main function of host cluster is to manage multiple clusters, and we should avoid running too many applications on it, is it?

Yes. Only the host cluster needs GitOps components. And you could manage applications in the host cluster.

**Comment by imshenyz** [comment]
Ok. I got it, thanks.
