### ISSUE TITLE
Avoid calling Jenkins replay API in the apiserver

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#773]
Considering Jenkins is just a CI engine for this project. We are going to remove all Jenkins API calling in the apiserver component.

The old API path: `v1alpha2/devops/{project}/pipelines/{pipeline}/runs/{run}/replay/`

I'd like to suggest a new API:

`v1alpha3/namespaces/{namespace}/pipelineruns/{pipelinerun}/rerun`

## References
* https://github.com/kubesphere/ks-devops/issues/772

/kind feature

**Comment by mzmuer** [comment]
remove all Jenkins API and replace them with Jenkins SDK? Or just replace the URL route

**Comment by LinuxSuRen** [comment]
The point of this issue is that only the controller could communicate with Jenkins. The APIServer should only read and write the CRs.

**Comment by chilianyi** [comment]
https://github.com/kubesphere/ks-devops/issues/714
