### ISSUE TITLE
The right devops project name can't be showed at the secret list

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/ks-devops#775]
### What is version of KubeSphere DevOps has the issue?

3.3.0

### What happened?

![image](https://user-images.githubusercontent.com/41519383/184121981-41238b80-38db-4309-b841-56e12c6af33c.png)
Create a devops project named devops project and create a secret in it;
Enter into the view of the cluster resource managerment list and find the secret and you will see the name couldn't match the real name.

**Comment by LinuxSuRen** [comment]
This page does not belong to DevOps.
/close
