### ISSUE TITLE
We can't select the devops project at the cluster resource management view.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/ks-devops#776]
### What is version of KubeSphere DevOps has the issue?

3.3.0

### What happened?

![image](https://user-images.githubusercontent.com/41519383/184122828-55826e59-8c8d-49a4-900a-fa25d9d1460b.png)
When we need to search the resouce of the devops project at the cluster resource management view ,we can't select the devops project from the _**dropdownlist**_.

**Comment by LinuxSuRen** [comment]
This page does not belong to DevOps.
/close
