### ISSUE TITLE
how to run more than one DevOps pipeline  

### ISSUE THREAD

**Issue by javaXiaoHan** [kubesphere/ks-devops#780]
为什么流水线任务只能开启一个，一个运行的时候，其他的流水线都是在队列中等待。该怎么设置并发运行。
@lshmouse 方便解答下吗

**Comment by LinuxSuRen** [comment]
hi @javaXiaoHan , you could update the following ConfigMap:

`kubesphere-devops-system/jenkins-casc-config`

increase the value to your desired number `jenkins_user.yaml > jenkins.clouds.containerCapStr`

**Comment by javaXiaoHan** [comment]
> hi @javaXiaoHan , you could update the following ConfigMap:
> 
> `kubesphere-devops-system/jenkins-casc-config`
> 
> increase the value to your desired number `jenkins_user.yaml > jenkins.clouds.containerCapStr`

thank u very much!
increase the value to your desired number and then  run 
'kubectl rollout restart -n kubesphere-system'  this command?

**Comment by javaXiaoHan** [comment]
![image](https://user-images.githubusercontent.com/32090060/184590051-c8047093-f0b3-4404-b8dd-d65c165ae079.png)
<img width="956" alt="3E626436-F95F-467d-AC1E-F3A96ACC3AAC" src="https://user-images.githubusercontent.com/32090060/184590081-b327c4a2-7be1-48bc-b7f3-1eea40b8d402.png">
一个流水线工作的时候，我启动另一个还是一直在初始化。

**Comment by LinuxSuRen** [comment]
hi @javaXiaoHan , you don't need to do anything once you updated that value correctly. See also the following document.

https://kubesphere.com.cn/en/docs/v3.3/devops-user-guide/how-to-use/pipelines/jenkins-setting/

**Comment by javaXiaoHan** [comment]
> increase the value to your desired number `jenkins_user.yaml > jenkins.clouds.containerCapStr`

thank you! i find your pr
