### ISSUE TITLE
Pipeline list interface parameter error

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#789]
### What is version of KubeSphere DevOps has the issue?

v3.3.1-rc.0

### What happened?

The limit should be consistent with the number of per page.

![image](https://user-images.githubusercontent.com/68640256/185332547-53808c00-3758-40d7-86ec-8c14d87d6ca4.png)

**Comment by wenxin-01** [comment]
Issue not fixed in `v3.3.1-rc.1`. @harrisonliu5
![image](https://user-images.githubusercontent.com/68640256/187114285-ba60b021-f39f-404b-b8f9-00317924de1d.png)

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
![image](https://user-images.githubusercontent.com/88183150/190577296-902dde29-6390-4bf9-82f1-73d7f0812767.png)
