### ISSUE TITLE
Cannot set the number of displays per page in 'Run Records' page

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#790]
### What is version of KubeSphere DevOps has the issue?

v3.3.1-rc.0

### What happened?

![image](https://user-images.githubusercontent.com/68640256/185335680-4a992bc6-1755-48a3-8012-51326e418e1a.png)

**Comment by wenxin-01** [comment]
Issue not fixed in `v3.3.1-rc.1`. it's not work, after set the number of displays per page. @harrisonliu5 
![image](https://user-images.githubusercontent.com/68640256/187112901-77649bbf-5472-4cad-95b7-9a2c9d8fe4fd.png)

**Comment by weili520** [comment]
![屏幕截图 2022-09-07 210557](https://user-images.githubusercontent.com/33231138/188885603-3e1c0a6b-4ab6-4325-889a-47eab21dd969.png)
