### ISSUE TITLE
The pipeline triggered by Webhook is not shown in the KS running record

### ISSUE THREAD

**Issue by birenchong** [kubesphere/ks-devops#798]
### What is version of KubeSphere DevOps has the issue?

v3.3.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

Amazon Elastic Kubernetes Service

### What happened?

The pipeline triggered by Webhook, which cannot be displayed in the record list, has been running in real time in the Jenkins console

ks console:
![image](https://user-images.githubusercontent.com/69137756/186639634-c545f101-49e2-47b0-b554-b83aa1c2bcff.png)

jenkins console：
![image](https://user-images.githubusercontent.com/69137756/186639799-e23319da-7cb2-4107-b487-3e1d26ca8058.png)

### Additional information

It's similar to this problem
https://github.com/kubesphere/ks-devops/issues/772#issue-1332563233

**Comment by LinuxSuRen** [comment]
See also https://github.com/kubesphere/ks-devops/issues/772#issuecomment-1232493860
/close
