### ISSUE TITLE
Support to disable build status notifications from Jenkins

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#804]
https://github.com/kubesphere/ks-devops/pull/797 support to send a build status notification from ks-devops. But Jenkins will send it too. See the following screenshot

![image](https://user-images.githubusercontent.com/1450685/187151241-3b9c6c74-2aaa-448c-a2df-a5c18c20ae71.png)

Firstly, it's totally not necessary to have both Jenkins and ks-devops build status links. We prefer to have ks-devops link only. So, we need to figure out a solution to disable the Jenkins build status link.

## Solution A

Jenkins plugin [Skip notifications trait](https://github.com/jenkinsci/skip-notifications-trait-plugin) could do that. We could add it to [ks-jenkins](https://github.com/kubesphere/ks-jenkins).

Then, make `githubSkipNotifications` as the default trait. See also https://github.com/kubesphere/ks-devops/blob/f69d2264e742b7b55ae502443396c1281cbf0c81/pkg/client/devops/jenkins/internal/github.go#L43

/good-first-issue

**Comment by gaffeyQiu** [comment]
> ![image](https://user-images.githubusercontent.com/1450685/187151241-3b9c6c74-2aaa-448c-a2df-a5c18c20ae71.png)

How do I simulate this notification？Can I get this jenkinsfile

**Comment by LinuxSuRen** [comment]
You could get the notification once you created a multi-branch Pipeline.
