### ISSUE TITLE
Improve the notification of build result to git provider

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#811]
See also the following screenshot, it would be good to provide more information than the result.

![image](https://user-images.githubusercontent.com/1450685/188053331-6faa0901-b48d-4845-9512-853afd7ba7ce.png)

The relevant source file is https://github.com/kubesphere/ks-devops/blob/796dbc70dffe9f94e37a6e8080aaeedc1c13f852/controllers/gitrepository/pull_request_status_controller.go#L95

/good-first-issue

**Comment by LinuxSuRen** [comment]
We could tell users which stage failed when the Pipeline failed.

**Comment by zhengzehong331** [comment]
I'm very interested in this issue and would like to get involved
/assign

**Comment by LinuxSuRen** [comment]
hi @zhengzehong331 , welcome! Please don't hesitate to tell us if you have any trouble with this issue.

**Comment by zhengzehong331** [comment]
![image](https://user-images.githubusercontent.com/86452570/193200055-8d386755-5c78-4b2a-af9f-da1e83794d49.png)
Is that right？ or i  need other configration?

**Comment by LinuxSuRen** [comment]
The status comes from Jenkins instead of ks-devops. Did you get any log output from the devops controller? It looks like there is no valid gh token.

**Comment by zhengzehong331** [comment]
there something error like this
![image](https://user-images.githubusercontent.com/86452570/193225376-245bfd7e-f8db-4272-8bae-89544105c991.png)
![image](https://user-images.githubusercontent.com/86452570/193225276-43130a80-883a-4c04-88b7-5bf139f28d96.png)
