### ISSUE TITLE
Invalid time duration on the PipelineRun log page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#826]
The time duration is negative when a Pipeline is running.

![image](https://user-images.githubusercontent.com/1450685/191021377-60259144-8cd9-4bce-8189-dd41b927de9b.png)

/good-first-issue
/kind bug

**Comment by chengleqi** [comment]
I'd like to tackle this one.
/assign

**Comment by chengleqi** [comment]
Hi @LinuxSuRen ,I cannot reproduce this kind of bug. Could you describe this situation in more detail?

<img width="873" alt="image" src="https://user-images.githubusercontent.com/53958238/191419880-50779c41-fd19-4ebf-840a-2a45d172e86c.png">

**Comment by LinuxSuRen** [comment]
Please see the time before a step is finished. You don't have to use this step. Any kind of step is ok.

**Comment by chengleqi** [comment]
Hi @LinuxSuRen , It also looks well when the step is running.

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/53958238/191425968-335c16cd-3c37-4de4-87d3-f549433eaf7a.png">

**Comment by LinuxSuRen** [comment]
It looks like not easy to reproduce it. How about avoiding display the negative time?

**Comment by chengleqi** [comment]
> It looks like not easy to reproduce it. How about avoiding displaying the negative time? We could show `-` if the time value is negative.

Yes, this way could be easy. I'll try again for a while.

**Comment by chengleqi** [comment]
I found a problem https://github.com/jenkins-zh/jenkins-client/issues/61 but is not the cause of this bug.

**Comment by chengleqi** [comment]
This situation will appear when run a parallel stage task cause by [jenkins](https://github.com/jenkinsci/blueocean-plugin) itself.

See also:
<img width="1374" alt="WechatIMG60" src="https://user-images.githubusercontent.com/53958238/191708738-d556df80-a8c5-44e0-93fb-a859bd80b8d4.png">

So we will show `-` when this situation happen.
