### ISSUE TITLE
In a multi-cluster environment, users without cluster permissions cannot select the host cluster as the deployment location of the CD task

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#827]
### What is version of KubeSphere DevOps has the issue?

v3.3.1-rc.2

### What happened?

There is a worksapce `wx-ws`, his cluster have host and member.
There is a devops project `dev-h` in the host cluster of wx-ws.
There is a user wxx, his platform role is `platform-regular` and worksapce role is `wx-ws-admin`

Use account wx login ks, and create CD task in devops project dev-h.

**Actual behavior**
The host cluster cannot be selected as the deployment location of the cd task.

![image](https://user-images.githubusercontent.com/68640256/191643937-da64084d-f4f3-4fee-8113-6d7cb430033e.png)

![image](https://user-images.githubusercontent.com/68640256/191644335-e6e09e0f-149a-4fd4-9e00-ff4d0d7d9489.png)

![image](https://user-images.githubusercontent.com/68640256/191643986-4c3c28c4-b762-42b5-9a78-74c7dc12ecf8.png)

![image](https://user-images.githubusercontent.com/68640256/191644203-feef9f1e-9482-42ce-a534-cca7877747e3.png)

**Excepted behavior**
If the user has the operation permission of the devops project in host cluster, then he can deploy the CD task to any cluster where the workspace is located.

**Comment by LinuxSuRen** [comment]
The correct cluster name should be `test-host` instead `host`. This is the reason why got a 404 error.

**Comment by wenxin-01** [comment]
Issue fixed in `ks v3.3.1-rc.3`
![image](https://user-images.githubusercontent.com/68640256/192731382-b0f4de82-1d24-485e-a7e7-7776addbf6e6.png)
