### ISSUE TITLE
Choice parameters Jenkinsfile are not shown on console

### ISSUE THREAD

**Issue by guillermobandres** [kubesphere/ks-devops#828]
Hi after upgrading to 3.2.1 we start experimenting the problem that parameters defined on Jenkinsfile are not shown on the console. We updated to v3.3.0 where is supposed to be fixed but it still happening.

![image](https://user-images.githubusercontent.com/54581507/191685435-d56bb3d2-f0cf-477a-8dc7-ad53aa29b480.png)
![image](https://user-images.githubusercontent.com/54581507/191685576-afdc3daa-7471-482f-959b-3ca8c857f84e.png)

On version 3.1.1 and earlier it works fine.

Thank you!

**Comment by LinuxSuRen** [comment]
hi @guillermobandres , thanks for reporting this issue. Please help to list the relevant images (of deployment):

* `devops-controller`
* `devops-apiserver`
* `ks-console`

**Comment by guillermobandres** [comment]
Hi, this is the list:

devops-controller: kubesphere/devops-controller:v3.3.0
devops-apiserver: kubesphere/devops-apiserver:v3.3.0
ks-console: kubesphere/ks-console:v3.3.0 (we tried also with master, same behaviour)

Also comment, we are running federated clusters, Host cluster (master) doesn't have devops tools installed, the devops tool are installed on a member.

Thank you!

**Comment by LinuxSuRen** [comment]
This is duplicated with https://github.com/kubesphere/ks-devops/issues/828

And it was fixed.

/close

**Comment by guillermobandres** [comment]
Hi, you closed by duplicated with the same ID of this issue.

**Comment by LinuxSuRen** [comment]
> Hi, you closed by duplicated with the same ID of this issue.

Sorry for that. Please see also https://github.com/kubesphere/ks-devops/issues/537
