### ISSUE TITLE
Request to refine Jenkins error message

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#83]
At present, our underlying code depends on the Jenkins client. If there is an error in the Jenkins API, a pile of incomprehensible error (like HTML) prompts will appear on the front end. We should refine the error prompts to provide users with better prompts.

![image](https://user-images.githubusercontent.com/16865714/127586081-e878d1c9-5410-4c90-9a85-9c97e1d1a1fe.png)

/kind optimization

**Comment by LinuxSuRen** [comment]
This issue is not clear enough for others to understand what the problem is, and what should we do.

**Comment by JohnNiang** [comment]
> This issue is not clear enough for others to understand what the problem is, and what should we do.

I've added a screenshot in issue description.

BTW, I've noticed that you have fired another issue <https://github.com/kubesphere-sigs/ks-devops/issues/41>. If <https://github.com/kubesphere-sigs/ks-devops/issues/41> is fixed, this issue will also be resolved.

**Comment by JohnNiang** [comment]
Duplicated with #41. I'm going to close it.

/close
