### ISSUE TITLE
When will the kubesphere devops CI pipeline support containerd containers

### ISSUE THREAD

**Issue by airufei** [kubesphere/ks-devops#833]
### What is version of KubeSphere DevOps has the issue?

3.3.0

### Describe this feature

When will the kubesphere devops CI pipeline support containerd containers？Currently, only the docker container can be used as the kubesphere's devops pipeline runtime, and k8s officially does not support the docker version after version 1.25, which is a matter that needs to be solved

**Comment by LinuxSuRen** [comment]
ks-devops does not have a limitation on the container runtime. And we offered podman as the image build client in the agent images.
