### ISSUE TITLE
User xxx not found in director

### ISSUE THREAD

**Issue by ximenxiaolanggou** [kubesphere/ks-devops#842]
### What is version of KubeSphere DevOps has the issue?

3.1.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

All-In-One

### What happened?

DevOps工程流水线创建，健康状态为异常
![image](https://user-images.githubusercontent.com/49423124/197341113-ea3fe313-1c4a-4e79-b97e-f06ef3dbad1d.png)

### Relevant log output

```shell
User xxx not found in director
```

### Additional information

```markdown
1. 先创建用户
2. 开启DevOps插件(All-In-One安装，默认未启用)
3. 创建流水线，健康状态为异常
4. 后续创建新用户
5. 该用户创建流水线状态为健康状态
```

**Comment by chilianyi** [comment]
I use v3.3.1, same as your operation process，did not encounter the same problem。

There is an issue about this: https://github.com/kubesphere/kubesphere/issues/3105
Already fix in 3.1.1

Is there any other log？
