### ISSUE TITLE
是否有支持containerd容器运行时的计划？

### ISSUE THREAD

**Issue by airufei** [kubesphere/ks-devops#844]
### What is version of KubeSphere DevOps has the issue?

是否有支持containerd容器运行时的计划？

### Describe this feature

k8s 1.24版本已经移除了对docker的直接支持，采用CRI接口与容器集成，当前的CRI容器稳定性比较好的当属containerd，但是在containerd容器下构建镜像存在障碍，导致CI流程需要借助三方工具来实现。比较麻烦。

看看贵组织是否有计划支持containerd这种容器运行时来完成服务的交付流程，谢谢。

**Comment by chilianyi** [comment]
Maybe this will be helpful：https://github.com/kubesphere/ks-devops/issues/67

**Comment by airufei** [comment]
> Maybe this will be helpful：#67

I have solved this problem, thank you
