### ISSUE TITLE
ks-jenkins keep restarting after install ks 3.3.1

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#848]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

There are some feedback from kubesphere bbs:

https://kubesphere.com.cn/forum/d/8993-331-jenkinscrashloopbackoff

https://kubesphere.com.cn/forum/d/9005-v331-devops

KS 3.3.1 upgrade ks-jenkins resource:
https://github.com/kubesphere/ks-installer/commit/7f2d6d75ff45b9ed252ce691aac5ed5968f67766

memory limit from 4g to 8g
cpu limit from 2 to 4

If the node without enough resource, the jenkins will be evited by the kubernetes scheduler.

**Comment by chilianyi** [comment]
maybe modify to:

cpu request = cpu limit = 2
memory request = memory request = 4g

need to verify

**Comment by VioZhang** [comment]
fixed
