### ISSUE TITLE
Devops controller sync data error: metadata.annotations: Too long: must have at most 262144 bytes  

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#853]
### What is version of KubeSphere DevOps has the issue?

v3.3.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

The pipelinerun keep running, while already successful or faild in jenkins.
Try to stop the pipelinerun,  but it had no effect.

The log in ks-devops-controller is:
<img width="1440" alt="截屏2022-11-10 15 42 56" src="https://user-images.githubusercontent.com/5917832/201247609-81c749a6-024d-43ff-b178-6cc6e8976ff5.png">
<img width="1435" alt="截屏2022-11-10 16 17 22" src="https://user-images.githubusercontent.com/5917832/201247649-38cd7e72-9a76-444c-9cc1-64c3203fa710.png">

The limit of annotation is 256K

Try to delete some words of the steps in jenkinsfile, then it works.

**Comment by chilianyi** [comment]
Ralated to https://github.com/kubesphere/ks-devops/pull/825

**Comment by chilianyi** [comment]
Backend：

1. Change jenkins metadata from pipelinerun annotations to configmap.
2. Add create rules for configmap in ClusterRole ks-devops.
3. Sign pipelinerun-data-store to pipelinerun reconciler.

Frontend:
<img width="1437" alt="截屏2022-11-14 14 25 18" src="https://user-images.githubusercontent.com/5917832/201590065-6aea26b6-564b-420b-86f3-da8a3bcb3718.png">

<img width="1440" alt="截屏2022-11-14 14 34 38" src="https://user-images.githubusercontent.com/5917832/201591465-55e050d1-b66e-49c6-973d-e85eb25a2a7e.png">

```
# kubectl get configmap -n starkxhqxb new2-b2j82 -o yaml
apiVersion: v1
data:
  stage: '[{"displayName":"stage-h3p7r","durationInMillis":5535,"id":"6","result":"SUCCESS","startTime":"2022-11-14T05:58:04Z","state":"FINISHED","type":"STAGE","restartable":true,"steps":[{"id":"7","displayName":"Shell
    Script","displayDescription":"ls -l","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2022-11-14T05:58:04Z","durationInMillis":5525}]}]'
  status: '{"causes":[{"_class":"io.jenkins.blueocean.service.embedded.rest.AbstractRunImpl$BlueCauseImpl","shortDescription":"Started
    by user admin","userId":"admin","userName":"admin"}],"durationInMillis":20116,"enQueueTime":"2022-11-14T05:57:50Z","endTime":"2022-11-14T05:58:10Z","startTime":"2022-11-14T05:57:50Z","estimatedDurationInMillis":22776,"id":"7","organization":"jenkins","pipeline":"new2","replayable":true,"result":"SUCCESS","runSummary":"stable","state":"FINISHED","type":"WorkflowRun"}'
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-14T05:58:27Z"
  name: new2-b2j82
  namespace: starkxhqxb
  ownerReferences:
  - apiVersion: devops.kubesphere.io/v1alpha3
    kind: PipelineRun
    name: new2-b2j82
    uid: 74e99bf6-0479-4bea-8090-ae6a02061186
  resourceVersion: "852905"
  uid: d17f1e11-f39e-4e5a-bebc-94cc8f0ed4cd
```

Get stage and status info from configmap with same name and same namespace.

**Comment by chilianyi** [comment]
https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/83

**Comment by yudong2015** [comment]
> Backend：
> 
> 1. Change jenkins metadata from pipelinerun annotations to configmap: [Support to store PipelineRun data into ConfigMap (#825) #855](https://github.com/kubesphere/ks-devops/pull/855)
> 2. Add create rules for configmap in ClusterRole ks-devops: [use configmap to store pipelinerun data kubesphere-sigs/ks-devops-helm-chart#83](https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/83)
> 3. Sign pipelinerun-data-store to pipelinerun reconciler: [7d0f6f0](https://github.com/kubesphere/ks-devops/commit/7d0f6f0a92dad1f3e4e329b753474e25c8c817bc)
> 
> Frontend: <img alt="截屏2022-11-14 14 25 18" width="1437" src="https://user-images.githubusercontent.com/5917832/201590065-6aea26b6-564b-420b-86f3-da8a3bcb3718.png">
> 
> <img alt="截屏2022-11-14 14 34 38" width="1440" src="https://user-images.githubusercontent.com/5917832/201591465-55e050d1-b66e-49c6-973d-e85eb25a2a7e.png">
> 
> ```
> # kubectl get configmap -n starkxhqxb new2-b2j82 -o yaml
> apiVersion: v1
> data:
>   stage: '[{"displayName":"stage-h3p7r","durationInMillis":5535,"id":"6","result":"SUCCESS","startTime":"2022-11-14T05:58:04Z","state":"FINISHED","type":"STAGE","restartable":true,"steps":[{"id":"7","displayName":"Shell
>     Script","displayDescription":"ls -l","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2022-11-14T05:58:04Z","durationInMillis":5525}]}]'
>   status: '{"causes":[{"_class":"io.jenkins.blueocean.service.embedded.rest.AbstractRunImpl$BlueCauseImpl","shortDescription":"Started
>     by user admin","userId":"admin","userName":"admin"}],"durationInMillis":20116,"enQueueTime":"2022-11-14T05:57:50Z","endTime":"2022-11-14T05:58:10Z","startTime":"2022-11-14T05:57:50Z","estimatedDurationInMillis":22776,"id":"7","organization":"jenkins","pipeline":"new2","replayable":true,"result":"SUCCESS","runSummary":"stable","state":"FINISHED","type":"WorkflowRun"}'
> kind: ConfigMap
> metadata:
>   creationTimestamp: "2022-11-14T05:58:27Z"
>   name: new2-b2j82
>   namespace: starkxhqxb
>   ownerReferences:
>   - apiVersion: devops.kubesphere.io/v1alpha3
>     kind: PipelineRun
>     name: new2-b2j82
>     uid: 74e99bf6-0479-4bea-8090-ae6a02061186
>   resourceVersion: "852905"
>   uid: d17f1e11-f39e-4e5a-bebc-94cc8f0ed4cd
> ```
> 
> Get stage and status info from configmap with same name and same namespace.

keep **devops.kubesphere.io/jenkins-pipelinerun-stages-status** in Pipelinerun.metadata.annotations and delete **data.status** in ConfigMap.
