### ISSUE TITLE
Optimize user experience for multi branch pipeline

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#865]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### Describe this feature

<img width="1440" alt="截屏2022-12-07 15 42 09" src="https://user-images.githubusercontent.com/5917832/206120536-e93bb8bc-bd09-4bea-a22f-2d2ed898124b.png">

User need scan the repo first, then show the branch, and is able to run.

Now there is a run on console just after create the multi branch pipeline, user will click the run, and it will show an error.

**Comment by VioZhang** [comment]
design as follow：

**Comment by VioZhang** [comment]
@Bettygogo2021 need-doc
