### ISSUE TITLE
Modify the Chinese version of argocd application status

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#871]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

<img width="1440" alt="截屏2022-10-25 19 44 06" src="https://user-images.githubusercontent.com/5917832/207802745-d21b8396-61aa-4936-854c-3936cb075b41.png">

degrade， 建议改成 被降级， 这里表示 某些资源未达到 健康状态。（healthy 是 100% 所有资源都是健康的， 所以其实 degrade 也算 部分健康 ）
missing， 建议改成 缺失， 这里就是表明 没找到资源， 丢失感觉有点主观概念。
suspended，建议改成 已暂停，比如一个 cronjob，暂停，会处于这种状态，翻译成已下架 不太合适。

**Comment by Bettygogo2021** [comment]
Fixed in https://github.com/kubesphere/console/pull/4011.

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:release-3.3`
![image](https://user-images.githubusercontent.com/68640256/212839292-de75f1e4-61ce-4d15-bff2-ecdf2a77a581.png)
