### ISSUE TITLE
devops-controller start with error

### ISSUE THREAD

**Issue by zj452008181** [kubesphere/ks-devops#873]
### What is version of KubeSphere DevOps has the issue?

3.2.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

v1.20.4

### What happened?

 W0106 09:07:05.778692       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

 I0106 09:07:05.781163       1 server.go:160] setting up manager

 I0106 09:07:05.881856       1 listener.go:44] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":8080"

 I0106 09:07:05.883985       1 server.go:198] Starting cache resource from apiserver...

 I0106 09:07:05.884030       1 server.go:201] Starting the controllers.

 I0106 09:07:07.289575       1 jenkinsconfig_controller.go:125] starting Jenkins config controller

 I0106 09:07:07.289613       1 pipeline_controller.go:187] starting pipeline controller

 I0106 09:07:07.289665       1 jenkinsconfig_controller.go:302] syncing key:kubesphere-devops-system/jenkins-casc-config

 I0106 09:07:07.289667       1 devopsproject_controller.go:185] starting devops project controller

 I0106 09:07:07.290274       1 devopscredential_controller.go:192] starting devopscredential controller

 I0106 09:07:07.290490       1 devopscredential_controller.go:219] namespace 'jusda-cdsd1-sitlxg44/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.291620       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"pipelineRef":null},"status":{}}}

 I0106 09:07:07.292550       1 devopscredential_controller.go:219] namespace 'julink-toolkitsqnhmt/harborid' in work queue no longer exists 

 I0106 09:07:07.292933       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" 

 I0106 09:07:07.292965       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "worker count"=1

 I0106 09:07:07.293165       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"type":""},"status":{}}}

 I0106 09:07:07.293391       1 devopscredential_controller.go:219] namespace 'jusda-lng-sitswszs/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.293470       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"type":""},"status":{}}}

 I0106 09:07:07.297777       1 s2irun_controller.go:172] starting s2irun controller

 I0106 09:07:07.297862       1 s2ibinary_controller.go:170] starting s2ibinary controller

 I0106 09:07:07.289616       1 internal.go:391] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"

 I0106 09:07:07.298338       1 devopscredential_controller.go:219] namespace 'jusda-cdsd1-sitlxg44/harborid' in work queue no longer exists 

 I0106 09:07:07.298413       1 devopscredential_controller.go:219] namespace 'juslink-widgetv22mt/juslink-gitlab-token' in work queue no longer exists 

 I0106 09:07:07.298427       1 devopscredential_controller.go:219] namespace 'jusda-cdsd1-sitlxg44/jusda-dce-cdsd2' in work queue no longer exists 

 I0106 09:07:07.298443       1 devopscredential_controller.go:219] namespace 'juslink-basicservicelqs89/harborid' in work queue no longer exists 

 I0106 09:07:07.298525       1 devopscredential_controller.go:219] namespace 'juslink-waybillp9k6t/juslink-gitlab-token' in work queue no longer exists 

 I0106 09:07:07.298568       1 devopscredential_controller.go:219] namespace 'jusda-lng-sitswszs/jusda-dcs-kylle' in work queue no longer exists 

 I0106 09:07:07.298586       1 devopscredential_controller.go:219] namespace 'jusda-lng-sitswszs/harborid' in work queue no longer exists 

 I0106 09:07:07.298597       1 devopscredential_controller.go:219] namespace 'juslink-basicservicelqs89/juslink-gitlab-token' in work queue no longer exists 

 I0106 09:07:07.299157       1 devopscredential_controller.go:219] namespace 'julink-toolkitsqnhmt/juslink-gitlab-token' in work queue no longer exists 

 I0106 09:07:07.301862       1 devopscredential_controller.go:219] namespace 'juslink-waybillp9k6t/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.301961       1 devopscredential_controller.go:219] namespace 'juslink-widgetv22mt/harborid' in work queue no longer exists 

 I0106 09:07:07.306142       1 devopscredential_controller.go:219] namespace 'juslink-waybillp9k6t/harborid' in work queue no longer exists 

 I0106 09:07:07.307101       1 devopscredential_controller.go:219] namespace 'jusda-srm-sitn9sxc/harborid' in work queue no longer exists 

 I0106 09:07:07.309533       1 devopscredential_controller.go:219] namespace 'jusda-srm-sitn9sxc/jusda-dcs-kylle' in work queue no longer exists 

 I0106 09:07:07.322037       1 devopscredential_controller.go:219] namespace 'jusda-srm-sitn9sxc/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.331028       1 devopscredential_controller.go:219] namespace 'id-generatorvq46p/juslink-gitlab-token' in work queue no longer exists 

 I0106 09:07:07.331774       1 devopscredential_controller.go:219] namespace 'id-generatorvq46p/harborid' in work queue no longer exists 

 I0106 09:07:07.332360       1 devopscredential_controller.go:219] namespace 'julink-toolkitsqnhmt/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.334679       1 devopscredential_controller.go:219] namespace 'id-generatorvq46p/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.353574       1 devopscredential_controller.go:219] namespace 'juslink-widgetv22mt/kubeconfig' in work queue no longer exists 

 I0106 09:07:07.353671       1 devopscredential_controller.go:219] namespace 'juslink-basicservicelqs89/kubeconfig' in work queue no longer exists 

 E0106 09:07:07.384464       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

 goroutine 448 [running]:

 k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1abd840, 0x2c15950)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa6

 k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x86

 panic(0x1abd840, 0x2c15950)

 	/usr/local/go/src/runtime/panic.go:965 +0x1b9

 github.com/beevik/etree.(*Element).Text(0x0, 0x1d2229f, 0x7)

 	/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:426 +0x26

 kubesphere.io/devops/pkg/client/devops/jenkins/internal.GetGitlabSourceFromEtree(0xc000aaf2c0, 0x1d785d3)

 	/workspace/pkg/client/devops/jenkins/internal/gitlab.go:126 +0x5da

 kubesphere.io/devops/pkg/client/devops/jenkins.parseMultiBranchPipelineConfigXml(0xc003eda000, 0x13d9, 0x13d9, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/pipeline_internal.go:453 +0x71e

 kubesphere.io/devops/pkg/client/devops/jenkins.(*Jenkins).GetProjectPipelineConfig(0xc000756b40, 0xc00256e4b0, 0xe, 0xc000c68f94, 0x9, 0x1, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/project_pipeline.go:172 +0x3b7

 kubesphere.io/devops/controllers/pipeline.(*Controller).syncHandler(0xc000880c80, 0xc00256e4b0, 0x18, 0xda466f, 0xc00045d558)

 	/workspace/controllers/pipeline/pipeline_controller.go:265 +0x7b2

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem.func1(0xc000880c80, 0x1a202a0, 0xc002575a50, 0x0, 0x0)

 	/workspace/controllers/pipeline/pipeline_controller.go:157 +0xe7

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem(0xc000880c80, 0x203001)

 	/workspace/controllers/pipeline/pipeline_controller.go:164 +0x4d

 kubesphere.io/devops/controllers/pipeline.(*Controller).worker(...)

 	/workspace/controllers/pipeline/pipeline_controller.go:175

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00175e220)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00175e220, 0x200e280, 0xc001a86360, 0x1, 0xc000ad2180)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0x9b

 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00175e220, 0x3b9aca00, 0x0, 0x1, 0xc000ad2180)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98

 k8s.io/apimachinery/pkg/util/wait.Until(0xc00175e220, 0x3b9aca00, 0xc000ad2180)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d

 created by kubesphere.io/devops/controllers/pipeline.(*Controller).Run

 	/workspace/controllers/pipeline/pipeline_controller.go:195 +0x1f0

 panic: runtime error: invalid memory address or nil pointer dereference [recovered]

 	panic: runtime error: invalid memory address or nil pointer dereference

 [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xc8f506]

 

 goroutine 448 [running]:

 k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x109

 panic(0x1abd840, 0x2c15950)

 	/usr/local/go/src/runtime/panic.go:965 +0x1b9

 github.com/beevik/etree.(*Element).Text(0x0, 0x1d2229f, 0x7)

 	/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:426 +0x26

 kubesphere.io/devops/pkg/client/devops/jenkins/internal.GetGitlabSourceFromEtree(0xc000aaf2c0, 0x1d785d3)

 	/workspace/pkg/client/devops/jenkins/internal/gitlab.go:126 +0x5da

 kubesphere.io/devops/pkg/client/devops/jenkins.parseMultiBranchPipelineConfigXml(0xc003eda000, 0x13d9, 0x13d9, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/pipeline_internal.go:453 +0x71e

 kubesphere.io/devops/pkg/client/devops/jenkins.(*Jenkins).GetProjectPipelineConfig(0xc000756b40, 0xc00256e4b0, 0xe, 0xc000c68f94, 0x9, 0x1, 0x0, 0x0)

 	/workspace/pkg/client/devops/jenkins/project_pipeline.go:172 +0x3b7

 kubesphere.io/devops/controllers/pipeline.(*Controller).syncHandler(0xc000880c80, 0xc00256e4b0, 0x18, 0xda466f, 0xc00045d558)

 	/workspace/controllers/pipeline/pipeline_controller.go:265 +0x7b2

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem.func1(0xc000880c80, 0x1a202a0, 0xc002575a50, 0x0, 0x0)

 	/workspace/controllers/pipeline/pipeline_controller.go:157 +0xe7

 kubesphere.io/devops/controllers/pipeline.(*Controller).processNextWorkItem(0xc000880c80, 0x203001)

 	/workspace/controllers/pipeline/pipeline_controller.go:164 +0x4d

 kubesphere.io/devops/controllers/pipeline.(*Controller).worker(...)

 	/workspace/controllers/pipeline/pipeline_controller.go:175

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00175e220)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f

 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00175e220, 0x200e280, 0xc001a86360, 0x1, 0xc000ad2180)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0x9b

 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00175e220, 0x3b9aca00, 0x0, 0x1, 0xc000ad2180)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98

 k8s.io/apimachinery/pkg/util/wait.Until(0xc00175e220, 0x3b9aca00, 0xc000ad2180)

 	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d

 created by kubesphere.io/devops/controllers/pipeline.(*Controller).Run

 	/workspace/controllers/pipeline/pipeline_controller.go:195 +0x1f0

**Comment by chilianyi** [comment]
The log show panic at：
https://github.com/kubesphere/ks-devops/blob/9c30f4f19eb87bb0d286b7e1261b3e0a4bf55c72/pkg/client/devops/jenkins/internal/gitlab.go#L126

cloneExtension.SelectElement("timeout") is nil
use nil.Text() throw panic

Thanks for your feedback, we will fix it soon.

**Comment by carefree666** [comment]
I also encountered the same problem. What is the reason for the problem? Are there any temporary solutions?

**Comment by yudong2015** [comment]
need to fix panic when timeout is nil in git/github cloneOptions.
