### ISSUE TITLE
The URL is not displayed after the code repositories is created

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#876]
### What is version of KubeSphere DevOps has the issue?

kubespheredev/ks-jenkins:v3.3.0-2.319.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubespheredev/ks-installer:nightly-20230115

### What happened?

![image](https://user-images.githubusercontent.com/68640256/212582808-95177a90-99c8-4358-a5fc-9df1c7dddb72.png)

![image](https://user-images.githubusercontent.com/68640256/212583127-235babaf-3efc-4415-ba61-44717e8b4768.png)

**Comment by wenxin-01** [comment]
Still exit in `kubesphere/devops-controller:v3.3.2`  `kubesphere/devops-apiserver:v3.3.2`

**Comment by yudong2015** [comment]
![WX20230117-163551](https://user-images.githubusercontent.com/14155338/212848739-ee8c752d-ea3a-494e-9673-acd3068a0f2c.png)


**logs in devops-controller**: 

 W0117 07:25:49.778910       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

 I0117 07:25:49.780840       1 server.go:169] setting up manager

 I0117 07:25:49.811648       1 listener.go:44] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":8080"

 I0117 07:25:49.813798       1 server.go:208] Starting cache resource from apiserver...

 I0117 07:25:49.813836       1 server.go:211] Starting the controllers.

 I0117 07:25:49.914443       1 internal.go:391] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"

 I0117 07:25:49.914548       1 devopscredential_controller.go:191] starting devopscredential controller

 I0117 07:25:49.914580       1 devopsproject_controller.go:186] starting devops project controller

 I0117 07:25:49.914721       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="cluster" "reconcilerGroup"="cluster.kubesphere.io" "reconcilerKind"="Cluster" "source"={"Type":{"apiVersion":"cluster.kubesphere.io/v1alpha1","kind":"Cluster"}}

 I0117 07:25:49.914749       1 jenkinsconfig_controller.go:143] starting Jenkins config controller

 I0117 07:25:49.914787       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="application" "reconcilerGroup"="argoproj.io" "reconcilerKind"="Application" "source"={"Type":{"apiVersion":"argoproj.io/v1alpha1","kind":"Application"}}

 I0117 07:25:49.914805       1 jenkinsconfig_controller.go:320] syncing key:kubesphere-devops-system/jenkins-casc-config

 I0117 07:25:49.914726       1 pipeline_controller.go:186] starting pipeline controller

 I0117 07:25:49.915145       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"pipelineRef":null},"status":{}}}

 I0117 07:25:49.915155       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="gitrepository" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="GitRepository" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{}}}

 I0117 07:25:49.915224       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" 

 I0117 07:25:49.915238       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="gitrepository" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="GitRepository" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{}}}

 I0117 07:25:49.915610       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="devopsproject" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="DevOpsProject" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{}}}

 I0117 07:25:49.915871       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="application" "reconcilerGroup"="gitops.kubesphere.io" "reconcilerKind"="Application" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{}}}

 I0117 07:25:49.915963       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"type":""},"status":{}}}

 I0117 07:25:49.915964       1 controller.go:142] controller "msg"="Starting EventSource" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"type":""},"status":{}}}

 I0117 07:25:50.015837       1 controller.go:149] controller "msg"="Starting Controller" "controller"="gitrepository" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="GitRepository" 

 I0117 07:25:50.015868       1 controller.go:149] controller "msg"="Starting Controller" "controller"="cluster" "reconcilerGroup"="cluster.kubesphere.io" "reconcilerKind"="Cluster" 

 I0117 07:25:50.015893       1 controller.go:176] controller "msg"="Starting workers" "controller"="gitrepository" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="GitRepository" "worker count"=1

 I0117 07:25:50.015915       1 controller.go:176] controller "msg"="Starting workers" "controller"="cluster" "reconcilerGroup"="cluster.kubesphere.io" "reconcilerKind"="Cluster" "worker count"=1

 I0117 07:25:50.015922       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipelinerun" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" "worker count"=1

 I0117 07:25:50.016026       1 gitrepository_amend_controller.go:40] git-repository-amend "msg"="start to AmendReconciler: test-devfmgrf/test"  

 I0117 07:25:50.016115       1 controller.go:149] controller "msg"="Starting Controller" "controller"="application" "reconcilerGroup"="gitops.kubesphere.io" "reconcilerKind"="Application" 

 I0117 07:25:50.016135       1 controller.go:149] controller "msg"="Starting Controller" "controller"="application" "reconcilerGroup"="argoproj.io" "reconcilerKind"="Application" 

 I0117 07:25:50.016153       1 controller.go:176] controller "msg"="Starting workers" "controller"="application" "reconcilerGroup"="argoproj.io" "reconcilerKind"="Application" "worker count"=1

 I0117 07:25:50.016178       1 controller.go:149] controller "msg"="Starting Controller" "controller"="devopsproject" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="DevOpsProject" 

 I0117 07:25:50.016216       1 gitrepository_amend_controller.go:40] git-repository-amend "msg"="start to AmendReconciler: test-devfmgrf/test-repo"  

 I0117 07:25:50.016316       1 controller.go:176] controller "msg"="Starting workers" "controller"="application" "reconcilerGroup"="gitops.kubesphere.io" "reconcilerKind"="Application" "worker count"=1

 I0117 07:25:50.016366       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" 

 I0117 07:25:50.016250       1 controller.go:176] controller "msg"="Starting workers" "controller"="devopsproject" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="DevOpsProject" "worker count"=1

 I0117 07:25:50.016386       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "worker count"=1

 I0117 07:25:50.016408       1 gitrepository_amend_controller.go:40] git-repository-amend "msg"="start to AmendReconciler: test-devfmgrf/wx-github"  

 I0117 07:25:50.016214       1 controller.go:149] controller "msg"="Starting Controller" "controller"="gitrepository" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="GitRepository" 

 I0117 07:25:50.016459       1 project_controller.go:52] ArgoCDProjectReconciler "msg"="start to reconcile project: /test-devfmgrf"  

 I0117 07:25:50.016472       1 controller.go:176] controller "msg"="Starting workers" "controller"="gitrepository" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="GitRepository" "worker count"=1

 I0117 07:25:50.016506       1 controller.go:149] controller "msg"="Starting Controller" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" 

 I0117 07:25:50.016514       1 git-repository-controller.go:50] GitRepositoryController "msg"="start to git repository: test-devfmgrf/test"  

 I0117 07:25:50.016530       1 controller.go:176] controller "msg"="Starting workers" "controller"="pipeline" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" "worker count"=1

 I0117 07:25:50.521925       1 git-repository-controller.go:50] GitRepositoryController "msg"="start to git repository: test-devfmgrf/test-repo"  

 I0117 07:25:50.525123       1 git-repository-controller.go:50] GitRepositoryController "msg"="start to git repository: test-devfmgrf/wx-github"  

 <nil>

 <nil>

 I0117 07:27:01.173129       1 jenkinsconfig_controller.go:357] synced key: kubesphere-devops-system/jenkins-casc-config

 I0117 07:27:34.106512       1 git-repository-controller.go:50] GitRepositoryController "msg"="start to git repository: test-devfmgrf/qa"  

 I0117 07:27:34.106512       1 gitrepository_amend_controller.go:40] git-repository-amend "msg"="start to AmendReconciler: test-devfmgrf/qa"  

 I0117 07:27:34.111186       1 git-repository-controller.go:114] GitRepositoryController "msg"="create secret for ArgoCD: argocd/qa-repo"  

 I0117 07:34:49.145976       1 git-repository-controller.go:50] GitRepositoryController "msg"="start to git repository: test-devfmgrf/qa1"  

 I0117 07:34:49.145982       1 gitrepository_amend_controller.go:40] git-repository-amend "msg"="start to AmendReconciler: test-devfmgrf/qa1"  

 I0117 07:34:49.150693       1 git-repository-controller.go:114] GitRepositoryController "msg"="create secret for ArgoCD: argocd/qa1-repo"  

 I0117 07:37:22.185898       1 application_controller.go:57] ApplicationController "msg"="start to reconcile application: test-devfmgrf/qa"  

 I0117 07:37:22.194298       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 E0117 07:37:22.242082       1 controller.go:246] controller "msg"="Reconciler error" "error"="Operation cannot be fulfilled on applications.gitops.kubesphere.io \"qa\": the object has been modified; please apply your changes to the latest version and try again" "controller"="application" "name"="qa" "namespace"="argocd" "reconcilerGroup"="argoproj.io" "reconcilerKind"="Application" 

 I0117 07:37:22.295678       1 application_controller.go:57] ApplicationController "msg"="start to reconcile application: test-devfmgrf/qa"  

 I0117 07:37:23.242783       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:37:27.177065       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:37:27.193153       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:37:28.357855       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:43:08.285917       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:46:07.141404       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:46:07.156595       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:49:07.528236       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:52:07.240848       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:55:07.650067       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 07:58:07.240406       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 08:01:07.759208       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 08:04:07.235262       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"  

 I0117 08:07:07.647123       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/qa"

**Comment by chilianyi** [comment]
<img width="1440" alt="截屏2023-01-28 10 50 11" src="https://user-images.githubusercontent.com/5917832/215238415-631ee340-e111-4cd7-b1bd-db48554cfde0.png">

If I delete url from yaml
<img width="1440" alt="截屏2023-01-28 10 50 21" src="https://user-images.githubusercontent.com/5917832/215238430-bdd8a24a-a2d9-4c9a-8ddf-23ecd86439ac.png">

It will show like this
<img width="1440" alt="截屏2023-01-28 10 50 49" src="https://user-images.githubusercontent.com/5917832/215238438-ac1f44bc-5663-4711-9cdf-7c2dbffb7fee.png">

Maybe we should not allow the url to be none in gitrepositories crd

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/devops-apiserver:ks-v3.3.2-rc.0`

![image](https://user-images.githubusercontent.com/68640256/215414628-f567af51-bf55-4bd7-9c98-108bf555f9fc.png)
