### ISSUE TITLE
Argocd namespace currently does not belong to any enterprise workspace, it should be added to the system-workspace.

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#931]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

Argocd namespace currently does not belong to any enterprise workspace, it should be added to the system-workspace.

<img width="700" alt="wecom-temp-348896-a810f83fdb59127338755d57b50a7c79" src="https://user-images.githubusercontent.com/5917832/228189821-e40d82a5-e0dc-4c7f-a644-66a60317b886.png">

<img width="636" alt="截屏2023-03-28 17 17 33" src="https://user-images.githubusercontent.com/5917832/228189947-e61567ee-78f9-46a1-9359-bded46ac6866.png">

**Comment by chilianyi** [comment]
kubectl label --overwrite namespaces argocd kubesphere.io/workspace=system-workspace

**Comment by wenxinll** [comment]
issue fixed in `kse v3.4.1-rc.1`
![image](https://github.com/kubesphere/ks-devops/assets/68640256/75c6cbda-7b5b-46c4-9902-0cc12d489bf3)

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/ks-devops/assets/24789703/c824b412-856f-421d-b4d6-a15ee1a24ae9)
