### ISSUE TITLE
Optimize the layout of the pipeline run log viewing page

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#945]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### Describe this feature

![wecom-temp-1346721-d36a56dfeedbf67126cbb774b0dfb97d](https://user-images.githubusercontent.com/5917832/234763000-bdfedf2f-1eeb-4743-b28b-7fa08a7badf0.jpg)

![wecom-temp-685409-e4621353529fc7e2a1049127bc5a9ffa](https://user-images.githubusercontent.com/5917832/234763003-36f770e3-3a33-4ee9-b4e8-70dc7ef9e7ad.jpg)

![wecom-temp-1305736-ca46bf3a91a194b38fc211dc95f1ddd0](https://user-images.githubusercontent.com/5917832/234763015-945320e1-1932-42aa-b817-a33aea83cb78.jpg)

When run pipeline, there are two log viewing button, the first is to view step log, the second is to view jenkins setup log

<img width="1436" alt="截屏2023-04-27 10 01 21" src="https://user-images.githubusercontent.com/5917832/234763196-01fc9deb-dcae-493a-86df-0df2d6ac6802.png">

It is hart for user to know the different between the two buttons, need to optimize the name, or optimize the layout.

**Comment by XiaohuiSept** [comment]
这个问题有两种处理方案：

**Comment by XiaohuiSept** [comment]
这部分有两种处理方案，看一下是否可以解决目前的问题 @chilianyi @VioZhang 
----
**1. 仅修改按钮文案（最小化修改）：**[设计图链接](https://www.figma.com/file/N9FlnD8wQjvIMNKcxEenw9/KubeSphere-DevOps?type=design&node-id=3074-226244&t=YElqdvZNJYpygBI2-4)
修改查看日志按钮的文案，流水线运行日志（Pipeline stage log）对应的按钮文案为【查看运行日志】；整个 Pipeline 的完整日志对应的按钮文案为【查看完整日志】。如下图：

<img width="1396" alt="image" src="https://github.com/kubesphere/ks-devops/assets/72596911/dbf1d379-c8d4-4a8a-b89a-23d888ca39e1">

-------

**2. 优化布局并修改文案：**[设计图链接](https://www.figma.com/file/N9FlnD8wQjvIMNKcxEenw9/KubeSphere-DevOps?type=design&node-id=3076-212307&t=YElqdvZNJYpygBI2-4)
将 Pipeline 运行日志（Pipeline stage log）的内容从弹窗中移至页面中，与图形化流水线同一层级，方便用户对应查看流水线每一个 step 图形化状态信息 的日志信息，【查看完整日志】的按钮置于运行日志页面内，作为辅助用户查看全部日志进行排错的入口。如下图：

<img width="1440" alt="release-x x  _ 运行记录" src="https://github.com/kubesphere/ks-devops/assets/72596911/67574a58-117d-4dfa-b380-5773ab7e0564">
<img width="1440" alt="release-x x  _ 运行记录" src="https://github.com/kubesphere/ks-devops/assets/72596911/dfebbf6a-f6f8-4c18-a041-a583a5765bf3">
<img width="1440" alt="流水线日志" src="https://github.com/kubesphere/ks-devops/assets/72596911/ddbd06ad-7136-4369-a728-8e735e62dfe1">

**Comment by chilianyi** [comment]
感觉 2 会更好一些。 @yudong2015  @yazhouio 看下呢。

**Comment by yudong2015** [comment]
我也觉得方案2体验好一些，需要亚洲看下实现上的难度；

**Comment by yazhouio** [comment]
前端已按方案 2 实现。

/kind need-to-verify

**Comment by wenxinll** [comment]
Issue fixed in `kse v3.4.1-rc.2`

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
查看stage 日志
![image](https://github.com/kubesphere/ks-devops/assets/24789703/f2cdadaa-5c58-4396-a1ea-bb44b3496f02)
查看wa完整日志
![image](https://github.com/kubesphere/ks-devops/assets/24789703/0a5d5eaf-6055-428f-aa06-05ef76f2e1bc)
