### ISSUE TITLE
Branches deleted by multi-branch pipelines can still be triggered to run

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#946]
### What is version of KubeSphere DevOps has the issue?

v3.3.2

### What happened?

1. There are 3 branches in the git repository ，create a multi-branch pipeline.
2. Scan the repository and see 3 branches.
3. Deletes a branch in git repository and scans the pipeline.

<img width="368" alt="截屏2023-05-15 17 35 13" src="https://github.com/kubesphere/ks-devops/assets/5917832/697df1cc-d5ca-4695-a80d-29a4014f3738">

<img width="1027" alt="截屏2023-05-15 17 35 43" src="https://github.com/kubesphere/ks-devops/assets/5917832/5bc72be7-fa6b-41de-adb9-82cd4f0e3bfd">

There are still 3 branch in pipeline, branch dev is disabled

Should add a status for the dev branch.

branch dev should be able to open and see old build records

Now is still able to run dev branch :
<img width="743" alt="截屏2023-05-15 17 37 26" src="https://github.com/kubesphere/ks-devops/assets/5917832/d41ee07c-766b-4f9f-8abd-05b531b5b158">

need to fix

**Comment by chilianyi** [comment]
<img width="1052" alt="截屏2023-05-16 14 26 43" src="https://github.com/kubesphere/ks-devops/assets/5917832/f8c39848-8952-4680-ad37-b29d4188fe70">

**Comment by chilianyi** [comment]
1. 流水线`健康状态`：映射 jenkins 中构建晴雨表，晴-健康-最近没有失败， 阴-部分健康-少部分失败，雨-异常-绝大部分失败。
2. 流水线整体`任务状态`：最近一次流水线运行的状态
3. 流水线整体`同步状态`：流水线 cr 与 jenkins 中同步状态
4. 流水线运行记录`状态`：映射 jenkins 中该构建记录的状态
5. 多分支流水线分支`状态`：该分支最近一次流水线运行的状态，若分支从 git 仓库删除，该状态显示为`禁用`
6. 多分支流水线分支`健康状态`: 映射 jenkins 中该分支构建晴雨表，状态同 1
7. 多分支流水线分支`任务状态`：该分支最近一次流水线运行的状态
8. 多分支流水线分支运行记录`状态`：映射 jenkins 中该多分支流水线分支构建记录的状态

**Comment by yudong2015** [comment]
接口get /kapis/clusters/host/devops.kubesphere.io/v1alpha3/devops/devfb9k9/pipelines/eee

metadata.annotations["pipeline.devops.kubesphere.io/jenkins-metadata"] 字段，branchNames 需要过滤已删除的 branchNames
![企业微信截图_7910b116-d72f-427a-afbf-afe95123b082](https://github.com/kubesphere/ks-devops/assets/14155338/67ce8078-22ef-4a13-b8bd-3fcf2e0978a9)

**Comment by wenxinll** [comment]
Issue fixed in `kse v3.4.1-rc.1`
![image](https://github.com/kubesphere/ks-devops/assets/68640256/11f4a806-204b-4043-a33a-ea9c72373a2d)

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/ks-devops/assets/24789703/8237dead-0fc0-49f3-a742-e2afe4d14925)
运行时，不显示已禁用的分支：
![image](https://github.com/kubesphere/ks-devops/assets/24789703/1683a537-b822-4636-9bac-6676fcbb8b74)
