### ISSUE TITLE
when I add a print message to the pipeline, there will be an error message, but i  don't know the detailed error information

### ISSUE THREAD

**Issue by drzhangg** [kubesphere/ks-devops#947]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### What happened?

1. there don't have the detailed error information
2. Although it reported an error, the response status was 200

![Pasted Graphic 13](https://github.com/kubesphere/ks-devops/assets/22233509/c88794bc-eda9-4456-ab00-fc624859d359)
![Pasted Graphic 14](https://github.com/kubesphere/ks-devops/assets/22233509/131caede-6ba1-443a-b05a-d59ba7d36c29)
![image](https://github.com/kubesphere/ks-devops/assets/22233509/d0221500-0b69-4c0e-a62b-25e06a8c4759)

**Comment by yudong2015** [comment]
post /kapis/devops.kubesphere.io/v1alpha3/clustersteptemplates/echo/render

传值 {"message":"\"aa\""}
返回

{
 "data": "{\n  \"arguments\": [\n    {\n      \"key\": \"message\",\n      \"value\": {\n        \"isLiteral\": true,\n        \"value\": \"\"aa\"\"\n      }\n    }\n  ],\n  \"name\": \"echo\"\n}"
}

这个返回值有点问题，前端 JSON 解析报错了
改成这样就不会报错了
{\n  \"arguments\": [\n    {\n      \"key\": \"message\",\n      \"value\": {\n        \"isLiteral\": true,\n        \"value\": \"\\"aa\\"\"\n      }\n    }\n  ],\n  \"name\": \"echo\"\n}

**Comment by chilianyi** [comment]
define in template:

            "value": {{printf "%q" .param.message}}

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/da5d6f0b-7a3e-41fe-9618-ea3e88d06ea0)
