### ISSUE TITLE
I cant see the pipeline detail with a status is cancelled by the id

### ISSUE THREAD

**Issue by drzhangg** [kubesphere/ks-devops#953]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### What happened?

I want to enter a pipeline to see the detail with status is cancelled, but the id is gray and i cant do this by clicking on the id

![Pasted Graphic 17](https://github.com/kubesphere/ks-devops/assets/22233509/81b13b46-4e10-48f7-ab15-a83d1ee5e712)

**Comment by chilianyi** [comment]
<img width="1048" alt="截屏2023-07-20 18 58 39" src="https://github.com/kubesphere/ks-devops/assets/5917832/070ca181-e41a-438b-b570-a0aab9f57783">

A is able to click while B is not able to click

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/abae0539-a9ec-43c1-827e-7bd910d2e3cb)
