### ISSUE TITLE
Jenkins always restarts due to OOM

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#957]
### What is version of KubeSphere DevOps has the issue?

v3.3.2

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

https://github.com/kubesphere-sigs/ks-devops-helm-chart/issues/115

**Comment by wenxinll** [comment]
issue fixed in `kse v3.4.1-rc.2`

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0`
![image](https://github.com/kubesphere/ks-devops/assets/24789703/a18071e3-7da3-4e61-9ae7-9ed06a4893cd)

**Comment by TTcheng** [comment]
problem issue with cgroup2
