### ISSUE TITLE
The text description of deleting expired branches in a multi-branch pipeline setup is inaccurate.

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#971]
### What is version of KubeSphere DevOps has the issue?

v3.3.2

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

<img width="1028" alt="截屏2023-07-07 16 23 39" src="https://github.com/kubesphere/ks-devops/assets/5917832/b3e52515-2455-4382-8416-5015891aa8bc">
<img width="1168" alt="截屏2023-07-07 16 23 12" src="https://github.com/kubesphere/ks-devops/assets/5917832/96b9915e-f0ea-4bb4-8cdc-69da173fbf63">

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/d7310b9d-48d3-4c44-9b4b-e106920304c5)

**Comment by chilianyi** [comment]
抱歉，我之前的描述和理解有误，需要做下更正：

这个位置的感念是：

1. 清理已删除分支（true，false）
2. 已删除分支保留天数
3. 已删除分支保留最大数量。
