### ISSUE TITLE
fail to create kubeconfig secret

### ISSUE THREAD

**Issue by drzhangg** [kubesphere/ks-devops#972]
### What is version of KubeSphere DevOps has the issue?

v3.4.1

### What happened?

In kse version with 3.4.1, the jenkins plugins delete the **kubernetes-cd plugin** and  **Azure Commons plugin**，so when i create kubeconfig secret in devops project, it will be error in jenkins logs.
<img width="1358" alt="企业微信截图_78d1f68e-25ee-441a-9a34-713620c1e295" src="https://github.com/kubesphere/ks-devops/assets/22233509/709b1957-5b9e-4162-b71f-8b2bd8014a8c">

**Comment by chilianyi** [comment]
The kubernetes-cd plugin is not deleted in v3.4.1
