### ISSUE TITLE
When scrolling logs, it is necessary to fix the left step list

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#978]
### What is version of KubeSphere DevOps has the issue?

v3.4.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

<img width="1052" alt="截屏2023-07-24 10 32 24" src="https://github.com/kubesphere/ks-devops/assets/5917832/2d2b3a85-8bb5-4233-8d82-e746ff57853e">

<img width="1055" alt="截屏2023-07-24 10 32 32" src="https://github.com/kubesphere/ks-devops/assets/5917832/c14f3dbc-2bc1-468c-83c0-841ee6456649">

**Comment by wenxinll** [comment]
Issue fixed in `kse v3.5.0-beta.1`
![image](https://github.com/kubesphere/issues/assets/68640256/49e4ea4f-4c78-4d7d-9f92-ae9872915fc4)
