### ISSUE TITLE
当某个流水线曾经设置过“删除过期构建记录”，然后再关闭该功能，Jenkins没有同步配置，依然按照旧规则进行记录清理。

### ISSUE THREAD

**Issue by TIANYUANXIXUE** [kubesphere/ks-devops#981]
### What is version of KubeSphere DevOps has the issue?

3.3.2

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

使用kk 3.0.7在线安装

### What happened?

![image](https://github.com/kubesphere/ks-devops/assets/41897037/2fb600a4-1624-407a-8f67-3590cd3855d6)
![image](https://github.com/kubesphere/ks-devops/assets/41897037/da74f039-8c2a-4b51-b223-64b8dd1a6dd2)
如图所示流水线，一开始我将清理配置设置为365天100条，后来我将该功能关闭，但是Jenkins中配置依然是原来的样子。

**Comment by chilianyi** [comment]
same as： https://github.com/kubesphere/ks-devops/issues/970

**Comment by yudong2015** [comment]
fixed in ks-3.4.0

/close
