### ISSUE TITLE
关于流水线记录清理定时任务，当某个流水线没有开启“删除过期构建记录”功能时，会导致清理任务报错，而尚未检查到的流水线则不会再进行清理。

### ISSUE THREAD

**Issue by TIANYUANXIXUE** [kubesphere/ks-devops#982]
### What is version of KubeSphere DevOps has the issue?

3.3.2

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

使用kk 3.0.7在线安装

### What happened?

![image](https://github.com/kubesphere/ks-devops/assets/41897037/f0c4a175-f2b6-478b-9f85-18192bae8a77)
如图，清理到namespace terminal***的时候，任务终止，但是后面还有namespace ucas***的清理尚未执行
![image](https://github.com/kubesphere/ks-devops/assets/41897037/c119e77f-6184-4937-ae17-1bf67ba953ea)
疑似是因为这里的return

**Comment by chilianyi** [comment]
Yes, the issue needs to be fixed in ks tools. 

This problem should not affect the pipeline; it will only result in an error for pipelines that do not have the deletion information configured.

**Comment by TIANYUANXIXUE** [comment]
> Yes, the issue needs to be fixed in ks tools.
> 
> This problem should not affect the pipeline; it will only result in an error for pipelines that do not have the deletion information configured.

我测试的结果是，假设存在多个devops项目a，b，c。b中有关闭清理的流水线存在，清理报错会导致c也不进行清理。
