### ISSUE TITLE
Kubesphere Jenkins Auth Test Connections Response format error

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/ks-devops#983]
### What is version of KubeSphere DevOps has the issue?

3.4.0

### What happened?

When I create devops pipeline, trigger executes successfully, but the agent pod is not created.

### Additional information

**Comment by yongxingMa** [comment]
<img width="1697" alt="image" src="https://github.com/kubesphere/ks-devops/assets/31605966/b8915484-84d3-4ef3-8761-2c343d5a1862">
<img width="1490" alt="image" src="https://github.com/kubesphere/ks-devops/assets/31605966/a37dc5cc-9127-4297-bdd7-4d932f3ccfbd">

**Comment by LinuxSuRen** [comment]
You don't need to care about the response format error. Do you met any other problems?

**Comment by yudong2015** [comment]
Yes, the Kubesphere Jenkins Auth in jenkins needn't to be updated, and as [LinuxSuRen](https://github.com/LinuxSuRen) above: don't need to care about the response format error.
