### ISSUE TITLE
Clicking the replay button will pop up an error prompt

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#986]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

<img width="1440" alt="截屏2023-08-08 09 38 30" src="https://github.com/kubesphere/ks-devops/assets/5917832/2eea081a-6ce2-4dc2-88c5-c0ee9af85209">

This is a normal pipeline.

**Comment by chilianyi** [comment]
<img width="1440" alt="截屏2023-08-08 09 42 16" src="https://github.com/kubesphere/ks-devops/assets/5917832/f45ee455-e931-46a0-99af-75fbc9fa154a">

The replay button on the details page is invalid

**Comment by wenxinll** [comment]
回放时是出现报错，但是后面无法复现这个错误。 @chilianyi 

![image](https://github.com/kubesphere/ks-devops/assets/68640256/b4e288f3-000b-49b2-883e-375fc6e48daa)

**Comment by chilianyi** [comment]
<img width="1027" alt="截屏2023-09-12 11 58 00" src="https://github.com/kubesphere/ks-devops/assets/5917832/95a283b9-3491-4d49-bd46-fe29684a043e">

我有出现过这个报错， 这是正常的，因为 构建记录已经被清理了。

**Comment by chilianyi** [comment]
> 回放时是出现报错，但是后面无法复现这个错误。 @chilianyi
> 
> ![image](https://user-images.githubusercontent.com/68640256/267199652-b4e288f3-000b-49b2-883e-375fc6e48daa.png)

https://github.com/jenkinsci/blueocean-plugin/blob/2d9003bb3812911eddeeeb487b5674c362274524/blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java#L129

这个报错应该是预期的报错， 因为回放遇到了未知情况，所以报错。 
具体客户遇到时，需要再查 jenkins 看是否有什么异常导致的。 但从前端报错角度，是正常的。 

@yazhouio 这里可以识别下吗，如果有报错，不弹出：开始运行流水线 了。 否则 用户有些疑惑，明明报错了，还是有个运行提示，其实没有运行。

**Comment by yazhouio** [comment]
好的

**Comment by wenxinll** [comment]
Issue fixed in `kse v3.5.0-rc.0`
