### ISSUE TITLE
Argocd server default readiness and liveness probe is too short

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#991]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

![image](https://github.com/kubesphere/ks-devops/assets/5917832/77f5e261-7c6d-4640-8c54-22277f9d8bcb)

![image](https://github.com/kubesphere/ks-devops/assets/5917832/2e5d7dab-6590-43a2-8d4e-3353d2ae5ce9)

Default timeout is 1s

Need change to 10s.

**Comment by chilianyi** [comment]
https://github.com/kubesphere/kse-installer/pull/365/files
https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/119/files

**Comment by wenxinll** [comment]
Issue fixed in `kse v3.5.0-alpha.1`



![Image](https://github.com/kubesphere/ks-devops/assets/68640256/7e606137-1ebd-4746-94b0-4a91802f33ad)

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/ks-devops/assets/18654693/458cf711-600b-443e-8d43-85e0c7755793)
