### ISSUE TITLE
Upgrade jenkins to 2.346.3 & fix groovy security hole

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#992]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### Describe this feature

Upgrade Jenkins and Jenkins plugins

![wecom-temp-1318372-cd4f2d2dd8d7b7c170d2e415638c720a](https://github.com/kubesphere/ks-devops/assets/5917832/a03eebb3-1e88-4387-b584-b23feeca9dda)

**Comment by chilianyi** [comment]
https://github.com/kubesphere/ks-jenkins/commit/b67cb0d9c60e8dabfa43d458029d98e3e863662a

**Comment by wenxinll** [comment]
Issue fixed in `kse v3.5.0-beta.1`

![image](https://github.com/kubesphere/issues/assets/68640256/10a7432a-b647-40d0-b002-d8dacdea57a4)
