### ISSUE TITLE
The devopsproject display error in the recently accessed menu

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#993]
### What is version of KubeSphere DevOps has the issue?

v3.4.0

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

<img width="1438" alt="截屏2023-08-18 14 13 34" src="https://github.com/kubesphere/ks-devops/assets/5917832/761c2bfe-4a20-4da9-9d0c-07fe6006dca0">
<img width="1438" alt="截屏2023-08-18 14 13 21" src="https://github.com/kubesphere/ks-devops/assets/5917832/ee80cc50-825e-4c45-8400-80152420c67a">

The devopsproject name is demo.

**Comment by wenxinll** [comment]
Issue fixed in `v3.5.0-beta.1`

![image](https://github.com/kubesphere/issues/assets/68640256/38350904-2c9a-496c-8e76-7835cc893a10)
